package org.innovateuk.ifs.workflow.domain;

/**
 * Represents a type of Activity that a Process is undergoing
 */
public enum ActivityType {

    APPLICATION_ASSESSMENT,
    PROJECT_SETUP,
    PROJECT_SETUP_COMPANIES_HOUSE_DETAILS,
    PROJECT_SETUP_PROJECT_DETAILS,
    PROJECT_SETUP_MONITORING_OFFICER_ASSIGNMENT,
    PROJECT_SETUP_BANK_DETAILS,
    PROJECT_SETUP_FINANCE_CHECKS,
    PROJECT_SETUP_VIABILITY,
    PROJECT_SETUP_ELIGIBILITY,
    PROJECT_SETUP_SPEND_PROFILE,
    PROJECT_SETUP_GRANT_OFFER_LETTER,
    APPLICATION
}
