## Originally sourced from https://github.com/primait/docker-proxysql/blob/master/1.3/Dockerfile.  Maintained locally to offer more security and additional functionality.
FROM debian:jessie

## Original maintainer Andrea Usuelli <andreausu@gmail.com>
MAINTAINER Duncan Watson <duncan@hiveit.co.uk>

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/sysown/proxysql/releases/download/1.3.0f/proxysql_1.3.0f-debian8_amd64.deb -O /opt/proxysql_1.3.0f-debian8_amd64.deb && \
    dpkg -i /opt/proxysql_1.3.0f-debian8_amd64.deb && \
    apt-get install -y mysql-client && \
    apt-get install -y rsync && \
    apt-get install -y vim && \
    rm -f /opt/proxysql_1.3.0f-debian8_amd64.deb && \
    rm -rf /var/lib/apt/lists/*


RUN mkdir -p /dump/rewrites

COPY proxysql/entrypoint.sh proxysql/make-mysqldump.sh proxysql/make-proxysql-cnf-file.sh /dump/

COPY proxysql/rewrites/* /dump/rewrites

COPY proxysql/proxysql.cnf /etc/

RUN chgrp -R 0 /etc && chmod -R g+rwX /etc
RUN chgrp -R 0 /dump && chmod -R g+rwx /dump
RUN chgrp -R 0 /var/lib/proxysql && chmod -R g+rwX /var/lib/proxysql

ENTRYPOINT ["/dump/entrypoint.sh"]