## Originally sourced from https://github.com/primait/docker-proxysql/blob/master/1.3/Dockerfile.  Maintained locally to offer more security and additional functionality.
FROM debian:8

RUN apt-get update && \
    apt-get install -y mysql-client curl && \
    curl -sLO https://github.com/sysown/proxysql/releases/download/v2.0.8/proxysql_2.0.8-debian8_amd64.deb && \
    cp proxysql_2.0.8-debian8_amd64.deb /opt/ && \
    dpkg -i /opt/proxysql_2.0.8-debian8_amd64.deb && \
    rm -rf /opt/proxysql_2.0.8-debian8_amd64.deb /var/lib/apt/lists/*

RUN mkdir -p /dump/rewrites

COPY entrypoint.sh make-mysqldump.sh make-proxysql-cnf-file.sh rewrite-rule-generator.sh /dump/

COPY rewrites/* /dump/rewrites/

COPY proxysql.cnf /etc/

RUN chgrp -R 0 /etc && chmod -R g+rwX /etc
RUN chgrp -R 0 /dump && chmod -R g+rwx /dump
RUN chgrp -R 0 /var/lib/proxysql && chmod -R g+rwX /var/lib/proxysql

ENTRYPOINT ["/dump/entrypoint.sh"]