FROM davidcaste/alpine-java-unlimited-jce:jdk8
MAINTAINER David Soff <dsoff@worth.systems>
RUN apk --update add curl
EXPOSE 8009
EXPOSE 8000
EXPOSE 8080
ENV JAVA_OPTS -Xmx300m
VOLUME /tmp

ADD management-@version@.jar app.jar
ADD coscale-monitoring.sh /root/coscale-monitoring.sh

ENTRYPOINT exec java $JAVA_OPTS -jar app.jar
