ALTER TABLE project_user ADD COLUMN type ENUM('PROJECT_USER', 'PROJECT_MONITORING_OFFICER');

UPDATE project_user SET type = 'PROJECT_USER'
WHERE project_role IN ( 'PROJECT_PARTNER', 'PROJECT_MANAGER', 'PROJECT_FINANCE_CONTACT' );

UPDATE project_user SET type = 'PROJECT_MONITORING_OFFICER'
WHERE project_role IN ( 'MONITORING_OFFICER');

ALTER TABLE project_user MODIFY COLUMN type ENUM('PROJECT_USER', 'PROJECT_MONITORING_OFFICER') NOT NULL;
