-- IFS-5312 Update eu action types

DELETE from `eu_action_type`;
INSERT INTO `eu_action_type` (`id`, `name`, `description`, `priority`) VALUES

(1,   'COFUND-EJP',        'European Joint Programme Cofund',                                                                                          1),
(2,   'COFUND-PCP',        'CoFunded - Pre Commercial Procurement',                                                                                    2),
(3,   'CS',                'Clean Sky',                                                                                                                3),
(4,   'CSA',               'Coordination and Support Actions',                                                                                         4),
(5,   'CSA-LS',            'Coordination and Support Action Lump Sum',                                                                                 5),
(6,   'EDCTP',             'European & Developing Countries Clinical Trials Partnership',                                                              6),
(7,   'EMPIR',             'European Metrology Programme for Innovation and Research',                                                                 7),
(8,   'ERA-NET-Cofund',    'European Research Agency-NET Cofund',                                                                                      8),
(9,   'ERC-ADG',           'European Research Council Advanced Grant',                                                                                 9),
(10,  'ERC-COG',           'European Research Council Consolidator Grant',                                                                            10),
(11,  'ERC-FR',            'ERC Frontier Research',                                                                                                   11),
(12,  'ERC-POC',           'European Research Council Proof of Concept Grant',                                                                        12),
(13,  'ERC-STG',           'European Research Council Synergy Grant',                                                                                 13),
(14,  'ERC-SyG',           'European Research Council Starting Grant',                                                                                14),
(15,  'FP7',               'Framework Programme 7',                                                                                                   15),
(16,  'FPA',               'Framework Partnership Agreement',                                                                                         16),
(17,  'FTI',               'Fast Track to Innovation',                                                                                                17),
(18,  'H2020-EEN-SGA',     'Enterprise Europe Network - Specific Grant Agreement',                                                                    18),
(19,  'IA',                'Innovation actions',                                                                                                      19),
(20,  'IA-LS',             'Innovation Actions Lump Sum',                                                                                             20),
(21,  'IPr',               'Inducement Prize',                                                                                                        21),
(22,  'ISIB',              'Innovative, Sustainable & Inclusive Bio-economy',                                                                         22),
(23,  'JTI-BBI-CSA',       'Joint Technology Initiative - Bio-based Industries - Coordination and Support action',                                    23),
(24,  'JTI-BBI-IA-DEMO',   'Joint Technology Initiative - Bio-based Industries – Innovation Actions -  Demonstration single stage',                   24),
(25,  'JTI-BBI-IA-FLAG',   'Joint Technology Initiative - Bio-based Industries - Innovation Actions - Flagship',                                      25),
(26,  'JTI-BBI-RIA',       'Joint Technology Initiative - Bio-based Industries – Research & Innovation Actions',                                      26),
(27,  'JTI-CS2-IA',        'Joint Technology Initiative – Clean Sky 2 – Innovation Actions',                                                          27),
(28,  'JTI-CS2-RIA',       'Joint Technology Initiative – Clean Sky 2 – Research & Innovation Actions',                                               28),
(29,  'JTI-ECSEL-IA',      'Joint Technology Initiative - Electronic Components and Systems for European Leadership – Innovation Actions',            29),
(30,  'JTI-ECSEL-RIA',     'Joint Technology Initiative - Electronic Components and Systems for European Leadership – Research & Innovation Actions', 30),
(31,  'JTI-FCH2-CSA',      'Joint Technology Initiative – Fuel Cells and Hydrogen2 - Coordination and Support action',                                31),
(32,  'JTI-FCH2-IA',       'Joint Technology Initiative – Fuel Cells and Hydrogen2 - Innovation actions',                                             32),
(33,  'JTI-FCH2-RIA',      'Joint Technology Initiative – Fuel Cells and Hydrogen2 – Research & Innovation actions',                                  33),
(34,  'JTI-IMI2-CSA',      'Joint Technology Initiative – Innovation Medicine Initiative2 - Coordination and Support action',                         34),
(35,  'JTI-IMI2-RIA',      'Joint Technology Initiative – Innovation Medicine Initiative2 - Research & Innovation actions',                           35),
(36,  'JTI-SESAR-CSA',     'Joint Technology Initiative - Single European Sky ATM Research - Coordination and Support action',                        36),
(37,  'JTI-SESAR-IA',      'Joint Technology Initiative - Single European Sky ATM Research – Innovation actions',                                     37),
(38,  'JTI-SESAR-RIA',     'Joint Technology Initiative - Single European Sky ATM Research - Research & Innovation actions',                          38),
(39,  'JTI-SHIFT2RAIL-IA', 'Joint Technology Initiative – Shift to Rail – Innovation actions',                                                        39),
(40,  'JTI-SHIFT2RAIL-RIA','Joint Technology Initiative – Shift to Rail – Research & Innovation actions',                                             40),
(41,  'KICS',              'Knowledge and Innovation Communities',                                                                                    41),
(42,  'MSCA - Night',      'Marie Sklodowska-Curie actions',                                                                                          42),
(43,  'MSCA-Cofund',       'Marie Sklodowska-Curie actions Cofund',                                                                                   43),
(44,  'MSCA-IF',           'Marie Sklodowska-Curie actions Individual Fellowships',                                                                   44),
(45,  'MSCA-ITN',          'Marie Sklodowska-Curie actions Innovative Training Networks',                                                             45),
(46,  'MSCA-RISE',         'Marie Sklodowska-Curie actions Research and Innovation Staff Exchange',                                                   46),
(47,  'PCP',               'Pre-Commercial Procurement',                                                                                              47),
(48,  'PPI',               'Public Procurement of Innovative solutions',                                                                              48),
(49,  'RFCS',              'Research Fund for Coal and Steel',                                                                                        49),
(50,  'RIA',               'Research and Innovation Actions',                                                                                         50),
(51,  'RPr',               'Recognition Prize',                                                                                                       51),
(52,  'SFS',               'Sustainable Food Security',                                                                                               52),
(53,  'SGA-CSA',           'Specific Grant Agreement – Coordination & Support Actions',                                                               53),
(54,  'SGA-RIA',           'Specific Grant Agreement – Research Innovation Actions',                                                                  54),
(55,  'SME-1',             'SME Instrument phase 1',                                                                                                  55),
(56,  'SME-2',             'SME Instrument phase 2',                                                                                                  56);
