 -- IFS-5940 Create a state for projects to be on hold
ALTER TABLE `activity_state` MODIFY COLUMN `state` enum('CREATED','PENDING','REJECTED','ACCEPTED','WITHDRAWN','OPEN','READY_TO_SUBMIT','SUBMITTED','VERIFIED','NOT_VERIFIED','ASSIGNED','NOT_ASSIGNED','NOT_APPLICABLE','NOT_APPLICABLE_INFORMED','CONFLICT_OF_INTEREST','HANDLED_OFFLINE','COMPLETED_OFFLINE', 'ON_HOLD');

INSERT INTO `activity_state` (id, activity_type, state) VALUES (53, 'PROJECT_SETUP', 'ON_HOLD');