INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Lamda Limited', 5, '10003758');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Surrey', 5, '10007160');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of York', 5, '10007167');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Aston University', 5, '10007759');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Royal College of Music', 5, '10007778');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Chancellor, Masters, and Scholars of the University of Cambridge', 5, '10007788');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Southampton', 5, '10007158');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Brighton', 5, '10000886');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Liverpool', 5, '10006842');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Birmingham City University', 5, '10007140');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Royal Academy of Music', 5, '10007835');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Royal Veterinary College', 5, '10007779');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Sunderland', 5, '10007159');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Queen Mary University of London', 5, '10007775');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Anglia Ruskin University Higher Education Corporation', 5, '10000291');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ("King's College London", 5, '10003645');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Edge Hill University', 5, '10007823');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Royal Central School of Speech and Drama', 5, '10007816');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Bristol', 5, '10007786');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Exeter', 5, '10007792');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Trinity Laban Conservatoire of Music and Dance', 5, '10008017');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Nottingham', 5, '10007154');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Plymouth', 5, '10007801');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Imperial College of Science, Technology and Medicine', 5, '10003270');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Newcastle upon Tyne', 5, '10007799');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ("St. George's Hospital Medical School", 5, '10007782');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University College London', 5, '10007784');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Central Lancashire', 5, '10007141');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of East Anglia', 5, '10007789');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Birmingham', 5, '10006840');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Hull', 5, '10007149');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Leeds', 5, '10007795');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Leicester', 5, '10007796');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Manchester', 5, '10007798');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Chancellor, Masters and Scholars of the University of Oxford', 5, '10007774');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Royal Northern College of Music', 5, '10007837');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Keele', 5, '10007767');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Leeds College of Music', 5, '10034449');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Lancaster', 5, '10007768');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Buckingham', 5, '10007787');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Sheffield', 5, '10007157');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Warwick', 5, '10007163');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Royal Academy of Dramatic Art', 5, '10009292');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('York College', 5, '10007709');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Norland College Limited', 5, '10008397');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('City, University of London', 5, '10001478');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Canterbury Christ Church University', 5, '10001143');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Cranfield University', 5, '10007822');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Leeds Beckett University', 5, '10003861');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Sheffield Hallam University', 5, '10005790');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of St Mark & St John', 5, '10037449');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Weston College of Further and Higher Education', 5, '10007459');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Brunel University London', 5, '10000961');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Norwich University of the Arts', 5, '10004775');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Royal Holloway and Bedford New College', 5, '10005553');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of the West of England, Bristol', 5, '10007164');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Exeter College', 5, '10002370');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Harper Adams University', 5, '10040812');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Middlesex University Higher Education Corporation', 5, '10004351');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Sussex', 5, '10007806');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('York St John University', 5, '10007713');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Leeds Trinity University', 5, '10003863');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Lincoln', 5, '10007151');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Plymouth College of Art', 5, '10005127');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bournemouth University Higher Education Corporation', 5, '10000824');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Gloucestershire College', 5, '10002696');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Falmouth University', 5, '10008640');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Hugh Baird College', 5, '10003193');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Greater Brighton Metropolitan College', 5, '10004736');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Salford', 5, '10007156');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Liverpool Hope University', 5, '10003956');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Manchester Metropolitan University', 5, '10004180');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Myerscough College', 5, '10004478');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Northern College of Acupuncture', 5, '10004740');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bishop Grosseteste University', 5, '10007811');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Liverpool Institute for Performing Arts', 5, '10003945');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Worcester', 5, '10007139');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Sheffield College', 5, '10005788');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Wolverhampton', 5, '10007166');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Sparsholt College', 5, '10006050');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Gloucestershire', 5, '10007145');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Tyne Coast College', 5, '10005999');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('South Gloucestershire and Stroud College', 5, '10036143');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London South Bank University', 5, '10004078');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Middlesbrough College', 5, '10004344');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Cliff College', 5, '10007912');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Kingston University', 5, '10003678');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Loughborough University', 5, '10004113');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The London School of Economics and Political Science', 5, '10004063');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Nelson College London Limited', 5, '10030129');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ("Goldsmiths' College", 5, '10002718');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London Business School', 5, '10007769');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('AECC University College', 5, '10000163');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Joseph Chamberlain Sixth Form College', 5, '10003511');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University College of Estate Management', 5, '10008173');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London School of Hygiene and Tropical Medicine', 5, '10007771');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Leeds Arts University', 5, '10003854');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Ravensbourne University London', 5, '10005389');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Solent University', 5, '10006022');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Liverpool John Moores University', 5, '10003957');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Huddersfield', 5, '10007148');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bath Spa University', 5, '10000571');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Essex', 5, '10007791');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Northumbria at Newcastle', 5, '10001282');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bridgwater and Taunton College', 5, '10000878');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Durham', 5, '10007143');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The School of Oriental and African Studies', 5, '10007780');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of West London', 5, '10006566');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Portsmouth Higher Education Corporation', 5, '10007155');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of the Arts, London', 5, ' London"');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Warwickshire College', 5, '10007859');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Conservatoire for Dance and Drama', 5, '10001653');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Reading', 5, '10007802');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Buckinghamshire New University', 5, '10000975');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Royal Agricultural University', 5, '10005545');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Arts University Bournemouth', 5, '10000385');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Courtauld Institute of Art', 5, '10007761');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Hertfordshire Higher Education Corporation', 5, '10007147');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ("Regent's University London", 5, '10003331');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Bath', 5, '10007850');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Oxford Brookes University', 5, '10004930');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Nottingham Trent University', 5, '10004797');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Birkbeck College', 5, '10007760');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Kent', 5, '10007150');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('De Montfort University Higher Education Corporation', 5, '10001883');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University College Birmingham', 5, '10000712');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Futureworks Training Limited', 5, '10022087');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Coventry University', 5, '10001726');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Chester', 5, '10007848');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Staffordshire University', 5, '10006299');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Rose Bruford College of Theatre and Performance', 5, '10005523');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Bedfordshire', 5, '10007152');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Blackpool and the Fylde College', 5, '10000754');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Harlow College', 5, '10002899');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Nottingham College', 5, '10004577');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Swindon College', 5, '10006463');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('DCG', 5, '10001919');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Lincoln College', 5, '10003928');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Newman University', 5, '10007832');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Derby', 5, '10007851');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Suffolk', 5, '10014001');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Northampton', 5, '10007138');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('ICMP Management Limited', 5, '10035638');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Southport College', 5, '10006038');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Wirral Metropolitan College', 5, '10007553');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('West Herts College', 5, '10007417');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('ALRA', 5, '10000248');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Oaklands College', 5, '10004835');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Roehampton University', 5, '10007776');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Nelson and Colne College', 5, '10004552');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('BPP University Limited', 5, '10031982');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Chesterfield College', 5, '10001378');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Institute of Cancer Research: Royal Cancer Hospital (The)', 5, '10003324');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Loughborough College', 5, '10004112');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Minster Centre', 5, '10032277');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Pearson College Limited', 5, '10042570');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Riverside College Halton', 5, '10002863');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Wakefield College', 5, '10007289');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Walsall College', 5, '10007315');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bury College', 5, '10001005');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Moorlands College', 5, '10023454');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Northern School of Art', 5, '10001503');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Teesside University', 5, '10007161');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Leeds City College', 5, '10024962');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Herefordshire and Ludlow College', 5, '10003023');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bishop Burton College', 5, '10000721');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Warrington & Vale Royal College', 5, '10007339');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Winchester', 5, '10003614');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Westminster', 5, '10007165');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bath College', 5, '10001465');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('South Thames Colleges Group', 5, '10003674');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Reaseheath College', 5, '10005404');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Wiltshire College and University Centre', 5, '10007527');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of Greenwich', 5, '10007146');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Point Blank Limited', 5, '10019178');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Study Group Limited', 5, '10008098');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London Metropolitan University', 5, '10004048');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Bolton', 5, '10006841');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('RNN Group', 5, '10005534');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Nazarene Theological College', 5, '10004538');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Royal College of Art (The)', 5, '10007777');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Wigan and Leigh College', 5, '10007500');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('East Riding College', 5, '10002126');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Southampton City College', 5, '10006020');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('BMC (Brooksby Melton College)', 5, '10000952');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('North Warwickshire and South Leicestershire College', 5, '10004718');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Petroc', 5, '10004676');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Craven College', 5, '10001743');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Moulton College', 5, '10004442');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Farnborough College of Technology', 5, '10002412');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('South Essex College of Further and Higher Education', 5, '10005981');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Preston College', 5, '10005200');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('City College Plymouth', 5, '10005128');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Hereford College of Arts', 5, '10003022');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Chichester', 5, '10007137');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Bradford', 5, '10007785');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Cumbria', 5, '10007842');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('City of Bristol College', 5, '10001467');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of East London', 5, '10007144');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Hadlow College', 5, '10002843');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Leicester College', 5, '10003867');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University of London', 5, '10007797');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Askham Bryan College', 5, '10000415');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Cheshire College South and West', 5, '10005972');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('St Mary’s University, Twickenham', 5, '10007843');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Abingdon and Witney College', 5, '10000055');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Fareham College', 5, '10007928');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('East Surrey College', 5, '10002130');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HY Education Limited', 5, '10041898');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Morley College Limited', 5, '10004432');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Richmond upon Thames College', 5, '10005469');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('North Kent College', 5, '10004721');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University College of Osteopathy (The)', 5, '10000936');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Kingston Maurward College', 5, '10003676');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Selby College', 5, '10005741');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('City College Norwich', 5, '10004772');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Furness College', 5, '10002599');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('New College Stamford', 5, '10006303');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Yeovil College', 5, '10007696');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Solihull College and University Centre', 5, '10005946');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Salford City College', 5, '10005032');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Basingstoke College of Technology', 5, '10000560');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('South Devon College', 5, '10005977');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bedford College', 5, '10000610');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Lakes College West Cumbria', 5, '10003753');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Christie’s Education Limited', 5, '10001419');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Boston College', 5, '10000812');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('SAE Education Limited', 5, '10007839');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Kingham Hill Trust', 5, '10010227');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('DN Colleges Group', 5, '10004695');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('New College Durham', 5, '10004576');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Highbury College Portsmouth', 5, '10007945');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Plumpton College', 5, '10005124');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('EKC Group', 5, '10006570');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Tameside College', 5, '10006494');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('RTC Education Ltd', 5, '10008455');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Oldham College', 5, '10006770');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('National Film and Television School (the)', 5, '10004511');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('West Suffolk College', 5, '10007431');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('NCG', 5, '10004599');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Milton Keynes College', 5, '10004375');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Cambridge Theological Federation', 5, '10032072');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The City of Liverpool College', 5, '10003955');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University for the Creative Arts', 5, '10006427');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Hertford Regional College', 5, '10003035');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Windsor Forest Colleges Group', 5, '10002107');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('North East Surrey College of Technology (NESCOT)', 5, '10004686');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Metanoia Institute', 5, '10004320');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HCUC', 5, '10007193');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('KLC Limited', 5, '10008325');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Writtle University College', 5, '10007657');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The WKCIC Group', 5, '10007455');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bolton College', 5, '10000794');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Barnsley College', 5, '10000536');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('United Colleges Group', 5, '10001476');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('CWR', 5, '10007361');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Edward James Foundation Limited', 5, '10032288');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The University of Law Limited', 5, '10039956');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London School of Management Education Limited', 5, '10022285');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Arts Educational Schools (The)', 5, '10000381');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Institute of Ismaili Studies', 5, '10067388');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bournemouth and Poole College', 5, '10000820');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Colchester Institute', 5, '10001535');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Luther King House Educational Trust', 5, '10009612');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Burnley College', 5, '10001000');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Istituto Marangoni Limited', 5, '10009527');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Cornwall College', 5, '10001696');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Activate Learning', 5, '10004927');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Strode College', 5, '10006378');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Truro and Penwith College', 5, '10007063');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Mid-Kent College', 5, '10004340');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Mountview Academy of Theatre Arts Limited', 5, '10004450');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London School of Academics Ltd', 5, '10032594');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Dudley College of Technology', 5, '10007924');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Queen’s Foundation for Ecumenical Theological Education', 5, '10032282');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Theological Education', 5, '10032282');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bromley College of Further and Higher Education', 5, '10000948');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Arden University Limited', 5, '10005451');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London School of Theology', 5, '10004075');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Royal Academy of Dance', 5, '10005544');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Brit College Limited', 5, '10028216');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Blackburn College', 5, '10000747');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Grimsby Institute of Further and Higher Education', 5, '10007938');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Barnet & Southgate College', 5, '10000533');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('UCK Limited', 5, '10015506');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The London Institute of Banking & Finance', 5, '10008289');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Cardinal Newman Catholic Sixth Form College', 5, '10001165');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bristol Baptist College', 5, '10000894');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('West Nottinghamshire College', 5, '10007427');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bradford College', 5, '10000840');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Open University', 5, '10007773');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Ruskin College', 5, '10005583');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('St Helens College', 5, '10006174');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Kirklees College', 5, '10003189');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Assemblies of God Incorporated', 5, '10020416');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Cambridge Arts & Sciences Limited', 5, '10010308');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('LTE Group', 5, '10023139');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Halesowen College', 5, '10002852');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('All Nations Christian College Limited', 5, '10000216');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Unified Seevic Palmer’s College', 5, '10005736');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Macclesfield College', 5, '10004144');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Kensington and Chelsea College', 5, '10003564');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Le Cordon Bleu Limited', 5, '10003798');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Hopwood Hall College', 5, '10003146');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Calderdale College', 5, '10001093');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Brooklands College', 5, '10000950');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Cambridge Regional College', 5, '10001116');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Kendal College', 5, '10003558');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('BIMM Limited', 5, '10037544');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Birmingham Metropolitan College', 5, '10006442');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('St Mary’s College', 5, '10006226');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Holy Cross College', 5, '10003128');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('West Thames College', 5, '10007434');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Havant and South Downs College', 5, '10005979');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Institute of Art - London Limited', 5, '10013220');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Gateshead College', 5, '10002638');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Royal School of Needlework (The)', 5, '10020436');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London Film School Limited', 5, '10004036');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Richmond, the American International University in London, Inc.', 5, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Markfield Institute of Higher Education', 5, '10023452');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Matrix College of Counselling and Psychotherapy Ltd.', 5, '10023453');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('St Nicholas Montessori Training Limited', 5, '10045289');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Central Bedfordshire College', 5, '10002061');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Aylesbury College', 5, '10000473');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Architectural Association (Incorporated)', 5, '10008071');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Leeds College of Building', 5, '10003855');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Peter Symonds College', 5, '10005072');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Stephenson College', 5, '10006322');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Newcastle and Stafford Colleges Group', 5, '10004603');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Christ the Redeemer College', 5, '10026921');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('St Mellitus College Trust', 5, '10030776');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Hartpury University', 5, '10080811');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Amity Global Education Ltd', 5, '10032036');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('City and Guilds of London Art School Limited', 5, '10039082');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Kaplan Open Learning (Essex) Limited', 5, '10021682');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London Bridge Business Academy Limited', 5, '10013109');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('City of Sunderland College', 5, '10001475');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Heart of Worcestershire College', 5, '10007977');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Peterborough Regional College', 5, '10005077');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Hull College', 5, '10003200');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Telford College', 5, '10006549');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Mont Rose College of Management and Sciences Limited', 5, '10023777');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Trinity College (Bristol) Limited', 5, '10023464');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London Studio Centre Limited', 5, '10004079');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Chichester College Group', 5, '10007817');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Newbury College', 5, '10004596');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Elim Foursquare Gospel Alliance', 5, '10021100');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Sherwood Psychotherapy Training Institute Limited', 5, '10023458');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Havering College of Further and Higher Education', 5, '10002935');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Guildhall School of Music & Drama', 5, '10007825');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Grantham College', 5, '10002743');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Met Film School Limited', 5, '10045476');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('BCNO Limited', 5, '10000911');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Empire College London Limited', 5, '10022047');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('City of Wolverhampton College', 5, '10007578');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('New College Swindon', 5, '10004579');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Sandwell College', 5, '10005669');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('ACM Guildford Ltd', 5, '10067853');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The College of Integrated Chinese Medicine', 5, '10001546');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('NCH at Northeastern Limited', 5, '10048199');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Berkshire College of Agriculture (BCA)', 5, '10000654');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Liverpool School of Tropical Medicine', 5, '10003958');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('East Sussex College Group', 5, '10002923');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Trafford College Group', 5, '10005998');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bishop Auckland College', 5, '10000720');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('London School of Commerce & IT Limited', 5, '10023434');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Shrewsbury Colleges Group', 5, '10005822');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('New City College', 5, '10006963');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Northampton College', 5, '10007011');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The London School of Architecture', 5, '10062810');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Easton and Otley College', 5, '10037344');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Bexhill College', 5, '10000670');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('South & City College Birmingham', 5, '10005967');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Brockenhurst College', 5, '10000944');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Burton and South Derbyshire College', 5, '10001004');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Global Banking School Limited', 5, '10042500');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('North Hertfordshire College', 5, '10004690');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Coventry College', 5, '10003010');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Hult International Business School Ltd', 5, '10003212');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Central Film School London Ltd', 5, '10024024');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('University Centre Peterborough', 5, '10068157');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('ICON College of Technology and Management Ltd', 5, '10003239');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Weymouth College', 5, '10007469');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Salvation Army Trust', 5, '10021256');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('ESCP Europe Business School', 5, '10002313');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Osteopathic Education and Research Limited', 5, '10002344');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Chicken Shed Theatre Trust', 5, '10001386');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Court Theatre Training Company Ltd', 5, '10034324');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Film Education Training Trust Limited', 5, '10004035');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Spurgeon’s College', 5, '10006093');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Croydon College', 5, '10001778');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Ealing, Hammersmith and West London College', 5, '10002094');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Council of the Inns of Court', 5, '10081618');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Navitas UK Holdings Limited', 5, '10053304');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ("The Prince's Foundation", 5, '10083476');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Dyson Technical Training Limited', 5, '10067355');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Itchen College', 5, '10003427');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Cell & Gene Therapy Catapult', 6, '10016023');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Compound Semiconductor Applications Catapult Limited', 6, '10255214');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Connected Places Catapult', 6, '11837978');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Digital Catapult', 6, '7964699');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Energy Systems Catapult Limited', 6, '8705784');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('High Value Manufacturing Catapult', 6, '7708659');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - AFRC', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - AMRC Factory 2020', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - AMRC Training Centre', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - AMRC with Boeing', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - CPI', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - CPI National Formulation Centre', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - CPI National Biologics Manufacturing Centre', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - CPI National Printable Electronics Centre', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - CPI National Printable Electronics, Newton Aycliffe', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - MTC (Coventry)', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - MTC (Liverpool)', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - Nuclear AMRC', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('HVMC Catapult - WMG', 6, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Medicines Discovery Catapult Limited', 6, '9928547');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Offshore Renewable Energy Catapult', 6, '4659351');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Satellite Applications Catapult Limited', 6, '7964746');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Earlham Institute', 3, '6855533');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Freshwater Biological Association', 3, '263162');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('National Oceanography Centre', 3, '11444362');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Quadram Institute Bioscience ( previously Institute of Food Research)', 3, '3009972');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The James Hutton Institute', 3, 'SC374831');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Scottish Association for Marine Science', 3, 'SC009292');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Transport Research Foundation', 3, '3011746');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Agri-Food & Biosciences Institute', 3, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Business Planning Services Limited', 3, '6499141');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('UK Centre for Ecology & Hydrology', 3, '11314957');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Eden Project', 3, '3278093');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Pirbright Institute (previously Institute of Animal Health)', 3, '559784');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Institute of Cancer Research : The Royal Cancer Hospital', 3, '534147');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('John Innes Centre', 3, '511709');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Moredun Research Institute', 3, 'SC149440');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('National Physical Laboratory Limited', 3, '2992144');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Qinetiq Limited', 3, '3796233');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('RAPRA Limited', 3, '159453');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Scottish Crop Research Institute', 3, 'SC029367');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('Smith Institute', 3, '3341743');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The Steel Construction Institute', 3, '1916698');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('TWI Limited', 3, '3859442');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('The National Archives', 3, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('East of Scotland KTP Centre', 3, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('West of Scotland KTP Centre', 3, '');
INSERT INTO knowledge_base (name, organisation_type_id, registration_number) VALUES ('North of Scotland KTP Centre', 3, '');