INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Lamda Limited', 'UNIVERSITY', '10003758');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Surrey', 'UNIVERSITY', '10007160');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of York', 'UNIVERSITY', '10007167');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Aston University', 'UNIVERSITY', '10007759');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Royal College of Music', 'UNIVERSITY', '10007778');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Chancellor, Masters, and Scholars of the University of Cambridge', 'UNIVERSITY', '10007788');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Southampton', 'UNIVERSITY', '10007158');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Brighton', 'UNIVERSITY', '10000886');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Liverpool', 'UNIVERSITY', '10006842');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Birmingham City University', 'UNIVERSITY', '10007140');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Royal Academy of Music', 'UNIVERSITY', '10007835');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Royal Veterinary College', 'UNIVERSITY', '10007779');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Sunderland', 'UNIVERSITY', '10007159');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Queen Mary University of London', 'UNIVERSITY', '10007775');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Anglia Ruskin University Higher Education Corporation', 'UNIVERSITY', '10000291');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ("King's College London", 'UNIVERSITY', '10003645');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Edge Hill University', 'UNIVERSITY', '10007823');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Royal Central School of Speech and Drama', 'UNIVERSITY', '10007816');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Bristol', 'UNIVERSITY', '10007786');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Exeter', 'UNIVERSITY', '10007792');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Trinity Laban Conservatoire of Music and Dance', 'UNIVERSITY', '10008017');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Nottingham', 'UNIVERSITY', '10007154');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Plymouth', 'UNIVERSITY', '10007801');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Imperial College of Science, Technology and Medicine', 'UNIVERSITY', '10003270');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Newcastle upon Tyne', 'UNIVERSITY', '10007799');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ("St. George's Hospital Medical School", 'UNIVERSITY', '10007782');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University College London', 'UNIVERSITY', '10007784');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Central Lancashire', 'UNIVERSITY', '10007141');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of East Anglia', 'UNIVERSITY', '10007789');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Birmingham', 'UNIVERSITY', '10006840');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Hull', 'UNIVERSITY', '10007149');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Leeds', 'UNIVERSITY', '10007795');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Leicester', 'UNIVERSITY', '10007796');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Manchester', 'UNIVERSITY', '10007798');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Chancellor, Masters and Scholars of the University of Oxford', 'UNIVERSITY', '10007774');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Royal Northern College of Music', 'UNIVERSITY', '10007837');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Keele', 'UNIVERSITY', '10007767');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Leeds College of Music', 'UNIVERSITY', '10034449');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Lancaster', 'UNIVERSITY', '10007768');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Buckingham', 'UNIVERSITY', '10007787');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Sheffield', 'UNIVERSITY', '10007157');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Warwick', 'UNIVERSITY', '10007163');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Royal Academy of Dramatic Art', 'UNIVERSITY', '10009292');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('York College', 'UNIVERSITY', '10007709');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Norland College Limited', 'UNIVERSITY', '10008397');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('City, University of London', 'UNIVERSITY', '10001478');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Canterbury Christ Church University', 'UNIVERSITY', '10001143');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cranfield University', 'UNIVERSITY', '10007822');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Leeds Beckett University', 'UNIVERSITY', '10003861');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Sheffield Hallam University', 'UNIVERSITY', '10005790');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of St Mark & St John', 'UNIVERSITY', '10037449');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Weston College of Further and Higher Education', 'UNIVERSITY', '10007459');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Brunel University London', 'UNIVERSITY', '10000961');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Norwich University of the Arts', 'UNIVERSITY', '10004775');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Royal Holloway and Bedford New College', 'UNIVERSITY', '10005553');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of the West of England, Bristol', 'UNIVERSITY', '10007164');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Exeter College', 'UNIVERSITY', '10002370');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Harper Adams University', 'UNIVERSITY', '10040812');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Middlesex University Higher Education Corporation', 'UNIVERSITY', '10004351');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Sussex', 'UNIVERSITY', '10007806');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('York St John University', 'UNIVERSITY', '10007713');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Leeds Trinity University', 'UNIVERSITY', '10003863');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Lincoln', 'UNIVERSITY', '10007151');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Plymouth College of Art', 'UNIVERSITY', '10005127');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bournemouth University Higher Education Corporation', 'UNIVERSITY', '10000824');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Gloucestershire College', 'UNIVERSITY', '10002696');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Falmouth University', 'UNIVERSITY', '10008640');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Hugh Baird College', 'UNIVERSITY', '10003193');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Greater Brighton Metropolitan College', 'UNIVERSITY', '10004736');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Salford', 'UNIVERSITY', '10007156');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Liverpool Hope University', 'UNIVERSITY', '10003956');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Manchester Metropolitan University', 'UNIVERSITY', '10004180');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Myerscough College', 'UNIVERSITY', '10004478');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Northern College of Acupuncture', 'UNIVERSITY', '10004740');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bishop Grosseteste University', 'UNIVERSITY', '10007811');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Liverpool Institute for Performing Arts', 'UNIVERSITY', '10003945');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Worcester', 'UNIVERSITY', '10007139');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Sheffield College', 'UNIVERSITY', '10005788');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Wolverhampton', 'UNIVERSITY', '10007166');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Sparsholt College', 'UNIVERSITY', '10006050');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Gloucestershire', 'UNIVERSITY', '10007145');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Tyne Coast College', 'UNIVERSITY', '10005999');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('South Gloucestershire and Stroud College', 'UNIVERSITY', '10036143');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London South Bank University', 'UNIVERSITY', '10004078');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Middlesbrough College', 'UNIVERSITY', '10004344');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cliff College', 'UNIVERSITY', '10007912');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Kingston University', 'UNIVERSITY', '10003678');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Loughborough University', 'UNIVERSITY', '10004113');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The London School of Economics and Political Science', 'UNIVERSITY', '10004063');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Nelson College London Limited', 'UNIVERSITY', '10030129');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ("Goldsmiths' College", 'UNIVERSITY', '10002718');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London Business School', 'UNIVERSITY', '10007769');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('AECC University College', 'UNIVERSITY', '10000163');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Joseph Chamberlain Sixth Form College', 'UNIVERSITY', '10003511');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University College of Estate Management', 'UNIVERSITY', '10008173');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London School of Hygiene and Tropical Medicine', 'UNIVERSITY', '10007771');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Leeds Arts University', 'UNIVERSITY', '10003854');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Ravensbourne University London', 'UNIVERSITY', '10005389');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Solent University', 'UNIVERSITY', '10006022');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Liverpool John Moores University', 'UNIVERSITY', '10003957');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Huddersfield', 'UNIVERSITY', '10007148');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bath Spa University', 'UNIVERSITY', '10000571');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Essex', 'UNIVERSITY', '10007791');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Northumbria at Newcastle', 'UNIVERSITY', '10001282');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bridgwater and Taunton College', 'UNIVERSITY', '10000878');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Durham', 'UNIVERSITY', '10007143');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The School of Oriental and African Studies', 'UNIVERSITY', '10007780');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of West London', 'UNIVERSITY', '10006566');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Portsmouth Higher Education Corporation', 'UNIVERSITY', '10007155');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of the Arts, London', 'UNIVERSITY', ' London"');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Warwickshire College', 'UNIVERSITY', '10007859');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Conservatoire for Dance and Drama', 'UNIVERSITY', '10001653');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Reading', 'UNIVERSITY', '10007802');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Buckinghamshire New University', 'UNIVERSITY', '10000975');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Royal Agricultural University', 'UNIVERSITY', '10005545');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Arts University Bournemouth', 'UNIVERSITY', '10000385');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Courtauld Institute of Art', 'UNIVERSITY', '10007761');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Hertfordshire Higher Education Corporation', 'UNIVERSITY', '10007147');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ("Regent's University London", 'UNIVERSITY', '10003331');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Bath', 'UNIVERSITY', '10007850');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Oxford Brookes University', 'UNIVERSITY', '10004930');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Nottingham Trent University', 'UNIVERSITY', '10004797');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Birkbeck College', 'UNIVERSITY', '10007760');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Kent', 'UNIVERSITY', '10007150');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('De Montfort University Higher Education Corporation', 'UNIVERSITY', '10001883');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University College Birmingham', 'UNIVERSITY', '10000712');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Futureworks Training Limited', 'UNIVERSITY', '10022087');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Coventry University', 'UNIVERSITY', '10001726');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Chester', 'UNIVERSITY', '10007848');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Staffordshire University', 'UNIVERSITY', '10006299');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Rose Bruford College of Theatre and Performance', 'UNIVERSITY', '10005523');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Bedfordshire', 'UNIVERSITY', '10007152');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Blackpool and the Fylde College', 'UNIVERSITY', '10000754');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Harlow College', 'UNIVERSITY', '10002899');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Nottingham College', 'UNIVERSITY', '10004577');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Swindon College', 'UNIVERSITY', '10006463');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('DCG', 'UNIVERSITY', '10001919');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Lincoln College', 'UNIVERSITY', '10003928');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Newman University', 'UNIVERSITY', '10007832');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Derby', 'UNIVERSITY', '10007851');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Suffolk', 'UNIVERSITY', '10014001');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Northampton', 'UNIVERSITY', '10007138');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('ICMP Management Limited', 'UNIVERSITY', '10035638');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Southport College', 'UNIVERSITY', '10006038');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Wirral Metropolitan College', 'UNIVERSITY', '10007553');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('West Herts College', 'UNIVERSITY', '10007417');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('ALRA', 'UNIVERSITY', '10000248');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Oaklands College', 'UNIVERSITY', '10004835');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Roehampton University', 'UNIVERSITY', '10007776');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Nelson and Colne College', 'UNIVERSITY', '10004552');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('BPP University Limited', 'UNIVERSITY', '10031982');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Chesterfield College', 'UNIVERSITY', '10001378');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Institute of Cancer Research: Royal Cancer Hospital (The)', 'UNIVERSITY', '10003324');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Loughborough College', 'UNIVERSITY', '10004112');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Minster Centre', 'UNIVERSITY', '10032277');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Pearson College Limited', 'UNIVERSITY', '10042570');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Riverside College Halton', 'UNIVERSITY', '10002863');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Wakefield College', 'UNIVERSITY', '10007289');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Walsall College', 'UNIVERSITY', '10007315');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bury College', 'UNIVERSITY', '10001005');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Moorlands College', 'UNIVERSITY', '10023454');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Northern School of Art', 'UNIVERSITY', '10001503');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Teesside University', 'UNIVERSITY', '10007161');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Leeds City College', 'UNIVERSITY', '10024962');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Herefordshire and Ludlow College', 'UNIVERSITY', '10003023');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bishop Burton College', 'UNIVERSITY', '10000721');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Warrington & Vale Royal College', 'UNIVERSITY', '10007339');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Winchester', 'UNIVERSITY', '10003614');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Westminster', 'UNIVERSITY', '10007165');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bath College', 'UNIVERSITY', '10001465');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('South Thames Colleges Group', 'UNIVERSITY', '10003674');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Reaseheath College', 'UNIVERSITY', '10005404');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Wiltshire College and University Centre', 'UNIVERSITY', '10007527');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Greenwich', 'UNIVERSITY', '10007146');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Point Blank Limited', 'UNIVERSITY', '10019178');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Study Group Limited', 'UNIVERSITY', '10008098');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London Metropolitan University', 'UNIVERSITY', '10004048');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Bolton', 'UNIVERSITY', '10006841');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('RNN Group', 'UNIVERSITY', '10005534');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Nazarene Theological College', 'UNIVERSITY', '10004538');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Royal College of Art (The)', 'UNIVERSITY', '10007777');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Wigan and Leigh College', 'UNIVERSITY', '10007500');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('East Riding College', 'UNIVERSITY', '10002126');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Southampton City College', 'UNIVERSITY', '10006020');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('BMC (Brooksby Melton College)', 'UNIVERSITY', '10000952');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('North Warwickshire and South Leicestershire College', 'UNIVERSITY', '10004718');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Petroc', 'UNIVERSITY', '10004676');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Craven College', 'UNIVERSITY', '10001743');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Moulton College', 'UNIVERSITY', '10004442');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Farnborough College of Technology', 'UNIVERSITY', '10002412');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('South Essex College of Further and Higher Education', 'UNIVERSITY', '10005981');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Preston College', 'UNIVERSITY', '10005200');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('City College Plymouth', 'UNIVERSITY', '10005128');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Hereford College of Arts', 'UNIVERSITY', '10003022');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Chichester', 'UNIVERSITY', '10007137');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Bradford', 'UNIVERSITY', '10007785');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Cumbria', 'UNIVERSITY', '10007842');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('City of Bristol College', 'UNIVERSITY', '10001467');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of East London', 'UNIVERSITY', '10007144');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Hadlow College', 'UNIVERSITY', '10002843');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Leicester College', 'UNIVERSITY', '10003867');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of London', 'UNIVERSITY', '10007797');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Askham Bryan College', 'UNIVERSITY', '10000415');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cheshire College South and West', 'UNIVERSITY', '10005972');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('St Mary’s University, Twickenham', 'UNIVERSITY', '10007843');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Abingdon and Witney College', 'UNIVERSITY', '10000055');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Fareham College', 'UNIVERSITY', '10007928');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('East Surrey College', 'UNIVERSITY', '10002130');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HY Education Limited', 'UNIVERSITY', '10041898');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Morley College Limited', 'UNIVERSITY', '10004432');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Richmond upon Thames College', 'UNIVERSITY', '10005469');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('North Kent College', 'UNIVERSITY', '10004721');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University College of Osteopathy (The)', 'UNIVERSITY', '10000936');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Kingston Maurward College', 'UNIVERSITY', '10003676');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Selby College', 'UNIVERSITY', '10005741');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('City College Norwich', 'UNIVERSITY', '10004772');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Furness College', 'UNIVERSITY', '10002599');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('New College Stamford', 'UNIVERSITY', '10006303');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Yeovil College', 'UNIVERSITY', '10007696');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Solihull College and University Centre', 'UNIVERSITY', '10005946');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Salford City College', 'UNIVERSITY', '10005032');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Basingstoke College of Technology', 'UNIVERSITY', '10000560');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('South Devon College', 'UNIVERSITY', '10005977');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bedford College', 'UNIVERSITY', '10000610');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Lakes College West Cumbria', 'UNIVERSITY', '10003753');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Christie’s Education Limited', 'UNIVERSITY', '10001419');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Boston College', 'UNIVERSITY', '10000812');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('SAE Education Limited', 'UNIVERSITY', '10007839');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Kingham Hill Trust', 'UNIVERSITY', '10010227');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('DN Colleges Group', 'UNIVERSITY', '10004695');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('New College Durham', 'UNIVERSITY', '10004576');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Highbury College Portsmouth', 'UNIVERSITY', '10007945');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Plumpton College', 'UNIVERSITY', '10005124');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('EKC Group', 'UNIVERSITY', '10006570');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Tameside College', 'UNIVERSITY', '10006494');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('RTC Education Ltd', 'UNIVERSITY', '10008455');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Oldham College', 'UNIVERSITY', '10006770');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('National Film and Television School (the)', 'UNIVERSITY', '10004511');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('West Suffolk College', 'UNIVERSITY', '10007431');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('NCG', 'UNIVERSITY', '10004599');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Milton Keynes College', 'UNIVERSITY', '10004375');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Cambridge Theological Federation', 'UNIVERSITY', '10032072');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The City of Liverpool College', 'UNIVERSITY', '10003955');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University for the Creative Arts', 'UNIVERSITY', '10006427');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Hertford Regional College', 'UNIVERSITY', '10003035');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Windsor Forest Colleges Group', 'UNIVERSITY', '10002107');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('North East Surrey College of Technology (NESCOT)', 'UNIVERSITY', '10004686');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Metanoia Institute', 'UNIVERSITY', '10004320');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HCUC', 'UNIVERSITY', '10007193');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('KLC Limited', 'UNIVERSITY', '10008325');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Writtle University College', 'UNIVERSITY', '10007657');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The WKCIC Group', 'UNIVERSITY', '10007455');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bolton College', 'UNIVERSITY', '10000794');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Barnsley College', 'UNIVERSITY', '10000536');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('United Colleges Group', 'UNIVERSITY', '10001476');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('CWR', 'UNIVERSITY', '10007361');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Edward James Foundation Limited', 'UNIVERSITY', '10032288');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The University of Law Limited', 'UNIVERSITY', '10039956');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London School of Management Education Limited', 'UNIVERSITY', '10022285');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Arts Educational Schools (The)', 'UNIVERSITY', '10000381');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Institute of Ismaili Studies', 'UNIVERSITY', '10067388');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bournemouth and Poole College', 'UNIVERSITY', '10000820');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Colchester Institute', 'UNIVERSITY', '10001535');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Luther King House Educational Trust', 'UNIVERSITY', '10009612');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Burnley College', 'UNIVERSITY', '10001000');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Istituto Marangoni Limited', 'UNIVERSITY', '10009527');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cornwall College', 'UNIVERSITY', '10001696');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Activate Learning', 'UNIVERSITY', '10004927');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Strode College', 'UNIVERSITY', '10006378');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Truro and Penwith College', 'UNIVERSITY', '10007063');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Mid-Kent College', 'UNIVERSITY', '10004340');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Mountview Academy of Theatre Arts Limited', 'UNIVERSITY', '10004450');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London School of Academics Ltd', 'UNIVERSITY', '10032594');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Dudley College of Technology', 'UNIVERSITY', '10007924');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Queen’s Foundation for Ecumenical Theological Education', 'UNIVERSITY', '10032282');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Theological Education', 'UNIVERSITY', '10032282');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bromley College of Further and Higher Education', 'UNIVERSITY', '10000948');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Arden University Limited', 'UNIVERSITY', '10005451');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London School of Theology', 'UNIVERSITY', '10004075');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Royal Academy of Dance', 'UNIVERSITY', '10005544');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Brit College Limited', 'UNIVERSITY', '10028216');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Blackburn College', 'UNIVERSITY', '10000747');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Grimsby Institute of Further and Higher Education', 'UNIVERSITY', '10007938');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Barnet & Southgate College', 'UNIVERSITY', '10000533');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('UCK Limited', 'UNIVERSITY', '10015506');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The London Institute of Banking & Finance', 'UNIVERSITY', '10008289');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cardinal Newman Catholic Sixth Form College', 'UNIVERSITY', '10001165');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bristol Baptist College', 'UNIVERSITY', '10000894');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('West Nottinghamshire College', 'UNIVERSITY', '10007427');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bradford College', 'UNIVERSITY', '10000840');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Open University', 'UNIVERSITY', '10007773');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Ruskin College', 'UNIVERSITY', '10005583');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('St Helens College', 'UNIVERSITY', '10006174');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Kirklees College', 'UNIVERSITY', '10003189');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Assemblies of God Incorporated', 'UNIVERSITY', '10020416');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cambridge Arts & Sciences Limited', 'UNIVERSITY', '10010308');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('LTE Group', 'UNIVERSITY', '10023139');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Halesowen College', 'UNIVERSITY', '10002852');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('All Nations Christian College Limited', 'UNIVERSITY', '10000216');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Unified Seevic Palmer’s College', 'UNIVERSITY', '10005736');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Macclesfield College', 'UNIVERSITY', '10004144');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Kensington and Chelsea College', 'UNIVERSITY', '10003564');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Le Cordon Bleu Limited', 'UNIVERSITY', '10003798');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Hopwood Hall College', 'UNIVERSITY', '10003146');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Calderdale College', 'UNIVERSITY', '10001093');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Brooklands College', 'UNIVERSITY', '10000950');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cambridge Regional College', 'UNIVERSITY', '10001116');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Kendal College', 'UNIVERSITY', '10003558');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('BIMM Limited', 'UNIVERSITY', '10037544');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Birmingham Metropolitan College', 'UNIVERSITY', '10006442');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('St Mary’s College', 'UNIVERSITY', '10006226');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Holy Cross College', 'UNIVERSITY', '10003128');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('West Thames College', 'UNIVERSITY', '10007434');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Havant and South Downs College', 'UNIVERSITY', '10005979');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Institute of Art - London Limited', 'UNIVERSITY', '10013220');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Gateshead College', 'UNIVERSITY', '10002638');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Royal School of Needlework (The)', 'UNIVERSITY', '10020436');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London Film School Limited', 'UNIVERSITY', '10004036');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Richmond, the American International University in London, Inc.', 'UNIVERSITY', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Markfield Institute of Higher Education', 'UNIVERSITY', '10023452');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Matrix College of Counselling and Psychotherapy Ltd.', 'UNIVERSITY', '10023453');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('St Nicholas Montessori Training Limited', 'UNIVERSITY', '10045289');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Central Bedfordshire College', 'UNIVERSITY', '10002061');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Aylesbury College', 'UNIVERSITY', '10000473');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Architectural Association (Incorporated)', 'UNIVERSITY', '10008071');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Leeds College of Building', 'UNIVERSITY', '10003855');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Peter Symonds College', 'UNIVERSITY', '10005072');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Stephenson College', 'UNIVERSITY', '10006322');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Newcastle and Stafford Colleges Group', 'UNIVERSITY', '10004603');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Christ the Redeemer College', 'UNIVERSITY', '10026921');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('St Mellitus College Trust', 'UNIVERSITY', '10030776');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Hartpury University', 'UNIVERSITY', '10080811');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Amity Global Education Ltd', 'UNIVERSITY', '10032036');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('City and Guilds of London Art School Limited', 'UNIVERSITY', '10039082');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Kaplan Open Learning (Essex) Limited', 'UNIVERSITY', '10021682');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London Bridge Business Academy Limited', 'UNIVERSITY', '10013109');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('City of Sunderland College', 'UNIVERSITY', '10001475');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Heart of Worcestershire College', 'UNIVERSITY', '10007977');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Peterborough Regional College', 'UNIVERSITY', '10005077');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Hull College', 'UNIVERSITY', '10003200');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Telford College', 'UNIVERSITY', '10006549');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Mont Rose College of Management and Sciences Limited', 'UNIVERSITY', '10023777');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Trinity College (Bristol) Limited', 'UNIVERSITY', '10023464');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London Studio Centre Limited', 'UNIVERSITY', '10004079');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Chichester College Group', 'UNIVERSITY', '10007817');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Newbury College', 'UNIVERSITY', '10004596');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Elim Foursquare Gospel Alliance', 'UNIVERSITY', '10021100');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Sherwood Psychotherapy Training Institute Limited', 'UNIVERSITY', '10023458');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Havering College of Further and Higher Education', 'UNIVERSITY', '10002935');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Guildhall School of Music & Drama', 'UNIVERSITY', '10007825');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Grantham College', 'UNIVERSITY', '10002743');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Met Film School Limited', 'UNIVERSITY', '10045476');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('BCNO Limited', 'UNIVERSITY', '10000911');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Empire College London Limited', 'UNIVERSITY', '10022047');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('City of Wolverhampton College', 'UNIVERSITY', '10007578');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('New College Swindon', 'UNIVERSITY', '10004579');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Sandwell College', 'UNIVERSITY', '10005669');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('ACM Guildford Ltd', 'UNIVERSITY', '10067853');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The College of Integrated Chinese Medicine', 'UNIVERSITY', '10001546');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('NCH at Northeastern Limited', 'UNIVERSITY', '10048199');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Berkshire College of Agriculture (BCA)', 'UNIVERSITY', '10000654');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Liverpool School of Tropical Medicine', 'UNIVERSITY', '10003958');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('East Sussex College Group', 'UNIVERSITY', '10002923');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Trafford College Group', 'UNIVERSITY', '10005998');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bishop Auckland College', 'UNIVERSITY', '10000720');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London School of Commerce & IT Limited', 'UNIVERSITY', '10023434');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Shrewsbury Colleges Group', 'UNIVERSITY', '10005822');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('New City College', 'UNIVERSITY', '10006963');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Northampton College', 'UNIVERSITY', '10007011');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The London School of Architecture', 'UNIVERSITY', '10062810');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Easton and Otley College', 'UNIVERSITY', '10037344');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bexhill College', 'UNIVERSITY', '10000670');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('South & City College Birmingham', 'UNIVERSITY', '10005967');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Brockenhurst College', 'UNIVERSITY', '10000944');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Burton and South Derbyshire College', 'UNIVERSITY', '10001004');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Global Banking School Limited', 'UNIVERSITY', '10042500');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('North Hertfordshire College', 'UNIVERSITY', '10004690');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Coventry College', 'UNIVERSITY', '10003010');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Hult International Business School Ltd', 'UNIVERSITY', '10003212');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Central Film School London Ltd', 'UNIVERSITY', '10024024');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University Centre Peterborough', 'UNIVERSITY', '10068157');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('ICON College of Technology and Management Ltd', 'UNIVERSITY', '10003239');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Weymouth College', 'UNIVERSITY', '10007469');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Salvation Army Trust', 'UNIVERSITY', '10021256');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('ESCP Europe Business School', 'UNIVERSITY', '10002313');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Osteopathic Education and Research Limited', 'UNIVERSITY', '10002344');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Chicken Shed Theatre Trust', 'UNIVERSITY', '10001386');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Court Theatre Training Company Ltd', 'UNIVERSITY', '10034324');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Film Education Training Trust Limited', 'UNIVERSITY', '10004035');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Spurgeon’s College', 'UNIVERSITY', '10006093');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Croydon College', 'UNIVERSITY', '10001778');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Ealing, Hammersmith and West London College', 'UNIVERSITY', '10002094');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Council of the Inns of Court', 'UNIVERSITY', '10081618');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Navitas UK Holdings Limited', 'UNIVERSITY', '10053304');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ("The Prince's Foundation", 'UNIVERSITY', '10083476');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Dyson Technical Training Limited', 'UNIVERSITY', '10067355');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Itchen College', 'UNIVERSITY', '10003427');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cell & Gene Therapy Catapult', 'CATAPULT', '10016023');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Compound Semiconductor Applications Catapult Limited', 'CATAPULT', '10255214');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Connected Places Catapult', 'CATAPULT', '11837978');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Digital Catapult', 'CATAPULT', '7964699');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Energy Systems Catapult Limited', 'CATAPULT', '8705784');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('High Value Manufacturing Catapult', 'CATAPULT', '7708659');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - AFRC', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - AMRC Factory 2020', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - AMRC Training Centre', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - AMRC with Boeing', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - CPI', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - CPI National Formulation Centre', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - CPI National Biologics Manufacturing Centre', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - CPI National Printable Electronics Centre', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - CPI National Printable Electronics, Newton Aycliffe', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - MTC (Coventry)', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - MTC (Liverpool)', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - Nuclear AMRC', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('HVMC Catapult - WMG', 'CATAPULT', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Medicines Discovery Catapult Limited', 'CATAPULT', '9928547');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Offshore Renewable Energy Catapult', 'CATAPULT', '4659351');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Satellite Applications Catapult Limited', 'CATAPULT', '7964746');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Earlham Institute', 'RTO', '6855533');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Freshwater Biological Association', 'RTO', '263162');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('National Oceanography Centre', 'RTO', '11444362');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Quadram Institute Bioscience ( previously Institute of Food Research)', 'RTO', '3009972');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The James Hutton Institute', 'RTO', 'SC374831');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Scottish Association for Marine Science', 'RTO', 'SC009292');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Transport Research Foundation', 'RTO', '3011746');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Agri-Food & Biosciences Institute', 'RTO', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Business Planning Services Limited', 'RTO', '6499141');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('UK Centre for Ecology & Hydrology', 'RTO', '11314957');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Eden Project', 'RTO', '3278093');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Pirbright Institute (previously Institute of Animal Health)', 'RTO', '559784');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Institute of Cancer Research : The Royal Cancer Hospital', 'RTO', '534147');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('John Innes Centre', 'RTO', '511709');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Moredun Research Institute', 'RTO', 'SC149440');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('National Physical Laboratory Limited', 'RTO', '2992144');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Qinetiq Limited', 'RTO', '3796233');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('RAPRA Limited', 'RTO', '159453');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Scottish Crop Research Institute', 'RTO', 'SC029367');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Smith Institute', 'RTO', '3341743');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The Steel Construction Institute', 'RTO', '1916698');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('TWI Limited', 'RTO', '3859442');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('The National Archives', 'RTO', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('East of Scotland KTP Centre', 'RTO', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('West of Scotland KTP Centre', 'RTO', '');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('North of Scotland KTP Centre', 'RTO', '');