-- IFS-3450 -- change interview panel states to just ASSIGNED

INSERT INTO activity_state VALUES (56, 'COFUNDER_ASSIGNMENT', 'CREATED');
INSERT INTO activity_state VALUES (57, 'COFUNDER_ASSIGNMENT', 'REJECTED');
INSERT INTO activity_state VALUES (58, 'COFUNDER_ASSIGNMENT', 'ACCEPTED');