INSERT INTO activity_state VALUES (59, 'PROJECT_SETUP_PAYMENT_MILESTONES', 'NOT_VERIFIED');
INSERT INTO activity_state VALUES (60, 'PROJECT_SETUP_PAYMENT_MILESTONES', 'NOT_APPLICABLE');
INSERT INTO activity_state VALUES (61, 'PROJECT_SETUP_PAYMENT_MILESTONES', 'ACCEPTED');
