INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Abertay University', 'UNIVERSITY', '10007849');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Aberystwyth University (Prifysgol Aberystwyth)', 'UNIVERSITY', '10007856');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Bangor University (Prifysgol Bangor)', 'UNIVERSITY', '10007857');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Belfast Metropolitan College', 'UNIVERSITY', '10020680');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cardiff Metropolitan University (Prifysgol Metropolitan Caerdydd)', 'UNIVERSITY', '10007854');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Cardiff University (Prifysgol Caerdydd)', 'UNIVERSITY', '10007814');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Coleg Cambria', 'UNIVERSITY', '10041295');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Edinburgh Napier University', 'UNIVERSITY', '10007772');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Glasgow Caledonian University', 'UNIVERSITY', '10007762');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Glasgow School of Art', 'UNIVERSITY', '10002681');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Glyndŵr University (Prifysgol Glyndŵr)', 'UNIVERSITY', '10007833');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Grwp Llandrillo Menai', 'UNIVERSITY', '10007820');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Heriot-Watt University', 'UNIVERSITY', '10007764');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('North West Regional College', 'UNIVERSITY', '10020634');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Queen Margaret University, Edinburgh', 'UNIVERSITY', '10005337');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Queen\'s University of Belfast', 'UNIVERSITY', '10005343');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Robert Gordon University', 'UNIVERSITY', '10005500');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Rothamsted Research Limited', 'UNIVERSITY', '10066014');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('South Eastern Regional College', 'UNIVERSITY', '10020699');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('South West College', 'UNIVERSITY', '10020685');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Southern Regional College', 'UNIVERSITY', '10020633');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('SRUC (Scotland\'s Rural College)', 'UNIVERSITY', '10005700');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Swansea University (Prifysgol Abertawe)', 'UNIVERSITY', '10007855');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Aberdeen', 'UNIVERSITY', '10007783');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Dundee', 'UNIVERSITY', '10007852');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Edinburgh', 'UNIVERSITY', '10007790');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Glasgow', 'UNIVERSITY', '10007794');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of South Wales/Prifysgol De Cymru', 'UNIVERSITY', '10007793');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of St Andrews', 'UNIVERSITY', '10007803');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Stirling', 'UNIVERSITY', '10007804');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Strathclyde', 'UNIVERSITY', '10007805');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of The Highlands and Islands', 'UNIVERSITY', '10007114');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of the West of Scotland', 'UNIVERSITY', '10007800');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Ulster', 'UNIVERSITY', '10007807');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Wales (Prifysgol Cymru)', 'UNIVERSITY', '10008574');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University of Wales Trinity Saint David (Prifysgol Cymru Y Drindod Dewi Sant)', 'UNIVERSITY', '10007858');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Archbishop of Canterbury, The', 'UNIVERSITY', '10046789');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('ASHRIDGE STRATEGIC MANAGEMENT CENTRE', 'UNIVERSITY', '10013773');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Heythrop College', 'UNIVERSITY', '10007765');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('London Institute of Banking and Finance, The', 'UNIVERSITY', '10008289');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('ROYAL COLLEGE OF NURSING OF THE UNITED KINGDOM (THE)', 'UNIVERSITY', '10007836');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Royal Conservatoire of Scotland', 'UNIVERSITY', '10005561');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('Science And Technology Facilities Council', 'UNIVERSITY', '10028532');
INSERT INTO knowledge_base (name, type, registration_number) VALUES ('University College of Osteopathy', 'UNIVERSITY', '10000936');