kubectl delete deployment --all
kubectl delete svc application-svc
kubectl delete svc data-service
kubectl delete svc idp
kubectl delete svc ifs-database
kubectl delete svc ldap
kubectl delete svc mail
kubectl delete svc shib
kubectl delete svc assessment-svc
kubectl delete svc cache-provider
kubectl delete svc competition-mgt-svc
kubectl delete svc data-service-alerts
kubectl delete svc finance-data-service
kubectl delete svc front-door-svc
kubectl delete svc project-setup-mgt-svc
kubectl delete svc project-setup-svc
kubectl delete svc registration-svc
kubectl delete svc survey-data-svc
kubectl delete svc survey-svc
kubectl delete configmap --all
kubectl delete secrets sp-secrets
kubectl delete secrets sp-keys-secrets
kubectl delete secrets ldap-keys-secrets
kubectl delete secrets idp-keys-secrets
