kustomize build base/auth/ > /dev/null || echo 'xxx error on base auth'
kustomize build base/data-layer/ > /dev/null || echo 'xxx error on base data'
kustomize build base/web-layer/ > /dev/null || echo 'xxx error on base web'
kustomize build base/db-reset/ > /dev/null || echo 'xxx error on base web'
kustomize build base/robot/ > /dev/null || echo 'xxx error on base robot'
kustomize build base/mail/ > /dev/null || echo 'xxx error on base mail'
kustomize build base/cache-provider/ > /dev/null || echo 'xxx error on base cache'


#kustomize build overlays/docker/local/ > /dev/null || echo 'xxx error on local'
#kustomize build overlays/docker/at/ > /dev/null || echo 'xxx error on at'
#kustomize build overlays/demo/ > /dev/null || echo 'xxx error on demo'
#kustomize build overlays/perf/ > /dev/null || echo 'xxx error on perf'
#kustomize build overlays/prod/ > /dev/null || echo 'xxx error on prod'
#kustomize build overlays/sysint/ > /dev/null || echo 'xxx error on sysint'
#kustomize build overlays/uat/ > /dev/null || echo 'xxx error on uat'
