kustomize build base > /dev/null || echo 'xxx error on base'

kustomize build components/auth > /dev/null || echo 'xxx error on base'
kustomize build components/registration-service > /dev/null || echo 'xxx error on reg service'
kustomize build components/cache-provider > /dev/null || echo 'xxx error on base cache'
kustomize build components/data-layer > /dev/null || echo 'xxx error on base data'
kustomize build components/db-reset > /dev/null || echo 'xxx error on base web'
kustomize build components/ifs-database > /dev/null || echo 'xxx error on base web'
kustomize build components/mail > /dev/null || echo 'xxx error on base mail'
kustomize build components/robot > /dev/null || echo 'xxx error on base robot'
kustomize build components/sil-stub > /dev/null || echo 'xxx error on sil'
kustomize build components/web-layer > /dev/null || echo 'xxx error on base web'
kustomize build components/anonymised-db-data > /dev/null || echo 'xxx error on anonymised db dump'

kustomize build patches/new-relic-env-vars-patch > /dev/null || echo 'xxx error on new-relic-env-vars-patch'
kustomize build patches/pull-secrets-patch > /dev/null || echo 'xxx error on pull-secrets-patch'
kustomize build patches/spring-profile-patch > /dev/null || echo 'xxx error on spring-profile-patch'

kustomize build env/stub/local/patches/java-debug-mode-patch > /dev/null || echo 'xxx error on java-debug-mode-patch'
kustomize build env/stub/local/patches/slow-startup-patch > /dev/null || echo 'xxx error on slow-startup-patch'
kustomize build env/stub/local/patches/wait-for-data-service-patch > /dev/null || echo 'xxx error on wait-for-data-service-patch'
kustomize build env/stub/local/patches/resource-limit-patch > /dev/null || echo 'xxx error on resource-limit-patch'

kustomize build env/env-base > /dev/null || echo 'xxx error on env base'
kustomize build env/aws/aws-base > /dev/null || echo 'xxx error on aws base'
kustomize build env/aws/demo > /dev/null || echo 'xxx error on aws demo'
kustomize build env/aws/perf > /dev/null || echo 'xxx error on aws perf'
kustomize build env/aws/prod > /dev/null || echo 'xxx error on aws prod'
kustomize build env/aws/sysint > /dev/null || echo 'xxx error on aws sysint'
kustomize build env/aws/uat > /dev/null || echo 'xxx error on aws uat'

kustomize build env/stub/stub-base > /dev/null || echo 'xxx error on stub base'
kustomize build env/stub/at > /dev/null || echo 'xxx error on stub at'
kustomize build env/stub/custom > /dev/null || echo 'xxx error on custom'
kustomize build env/stub/local/ext > /dev/null || echo 'xxx error on local ext'
kustomize build env/stub/local/local-base > /dev/null || echo 'xxx error on local dev'
kustomize build env/stub/local/dev > /dev/null || echo 'xxx error on local dev'
kustomize build env/stub/local/custom > /dev/null || echo 'xxx error on local custom'
kustomize build env/stub/local/debug > /dev/null || echo 'xxx error on local debug'
kustomize build env/stub/local/min > /dev/null || echo 'xxx error on local min'
