package org.innovateuk.ifs.api.audit;

public enum AuditType {
    MISC,
    LOGIN,
    LOGOUT,
    IFSPA_GRANT_SEND,
    IFSPA_CREATE_PROJECT,
    SIL_LOANS_SUBMISSION,
    SIL_SYNC_CONTACT,
    SIL_DECISION_MATRIX,
    FILE_STORAGE_SUCCESS_EVENT,
    FILE_STORAGE_FAILURE_EVENT;
}
