-- IFS-2540 - Update custom questions (ones that have not been generated by a template) so that they have
-- `mark_as_completed_enabled` set to true. Otherwise, they are set to false and this causes issues with
-- applicants completing the questions properly.

UPDATE question
SET question.mark_as_completed_enabled = 1
WHERE question.mark_as_completed_enabled != 1
      AND question.section_id IN (SELECT id
                                  FROM section
                                  WHERE name = 'Application questions');

