UPDATE guidance_row
SET justification = 'The project costs are entirely appropriate and represent excellent value for money compared to alternative approaches outlined (including doing nothing). The partners have a clear idea of how they will finance their contribution. The balance of costs and grants between partners, and use of subcontractors is justified and reasonable for the proposed project.'
WHERE justification = 'The project costs are entirely appropriate and represent excellent value for money compared to alternative approaches outlined (including doing nothing)..  The partners have a clear idea of how they will finance their contribution.  The balance of costs and grants between partners, and use of subcontractors is justified and reasonable for the proposed project.';

UPDATE guidance_row
SET justification = 'Target customers are identified along with the value proposition to them. The routes to market and how profit, productivity and growth will increase is identified and evidenced. The exploitation and/or dissemination of the main project outputs is outlined.'
WHERE justification = 'Target customers are identified along withthe value proposition  to them.  The routes to market and how profit, productivity and growth will increaseis identified and evidenced. .  The exploitation and/or dissemination of the main project outputs is outlined.';

UPDATE guidance_row
SET justification = 'Target customers are identified along with the value proposition to them. The routes to market and how profit, productivity and growth will increase is identified and evidenced. The exploitation and/or dissemination of the main project outputs is outlined. The Projected Growth table is completed and projections look realistic.'
WHERE justification = 'Target customers are identified along withthe value proposition  to them.  The routes to market and how profit, productivity and growth will increaseis identified and evidenced. .  The exploitation and/or dissemination of the main project outputs is outlined.The Projected Growth table is completed and projections look realistic.'