/* Create the generic competition type  */
INSERT INTO `competition_type` (`name`, `state_aid`, `active`, `template_competition_id`)
VALUES ('Generic', 1, 1, NULL);
SET @competition_type_generic_id=LAST_INSERT_ID();


SET @not_empty_validator = (SELECT `id` FROM form_validator WHERE `clazz_name` = 'org.innovateuk.ifs.validator.NotEmptyValidator');
SET @word_count_validator = (SELECT `id` FROM form_validator WHERE `clazz_name` = 'org.innovateuk.ifs.validator.WordCountValidator');

/* Create the generic competition for template purpose  */
INSERT INTO `competition` (`name`,`max_research_ratio`,`academic_grant_percentage`,`budget_code`,`code`,`paf_code`,`executive_user_id`,`lead_technologist_user_id`,`competition_type_id`,`activity_code`,`innovate_budget`,`multi_stream`,`collaboration_level`,`stream_name`,`resubmission`,`setup_complete`,`full_application_finance`,`assessor_count`,`assessor_pay`,`template`,`use_resubmission_question`) VALUES ('Template for the Generic competition type',0,100,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,1,0,0.00,1,1);
SET @generic_template_id=LAST_INSERT_ID();
UPDATE competition_type SET template_competition_id = @generic_template_id WHERE id = @competition_type_generic_id;


/* Add the required section to the generic competition template  */
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES ('These sections give important background information on the project. They do not need scoring however you do need to mark the scope.','Please provide Innovate UK with information about your project. These sections are not scored but will provide background to the project.',1,'Project details',1,@generic_template_id,NULL,0,'GENERAL');
SET @s_project_details=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES ('Each question should be given a score out of 10. Written feedback should also be given.','These are the 10 questions which will be marked by assessors. Each question is marked out of 10 points.',1,'Application questions',2,@generic_template_id,NULL,0,'GENERAL');
SET @s_application_questions=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES ('Each partner is required to submit their own project finances and funding rates. The overall project costs for all partners can be seen in the Finances overview section','Each partner is required to submit their own project finances and funding rates. The overall project costs for all partners can be seen in the Finances overview section',1,'Finances',3,@generic_template_id,NULL,0,'GENERAL');
SET @s_finances=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Your finances',4,@generic_template_id,@s_finances,1,'FINANCE');
SET @s_your_finances=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,1,'Your project costs',5,@generic_template_id,@s_your_finances,1,'PROJECT_COST_FINANCES');
SET @s_your_project_costs=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,1,'Your organisation',6,@generic_template_id,@s_your_finances,1,'ORGANISATION_FINANCES');
SET @s_your_organisation=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,1,'Your funding',7,@generic_template_id,@s_your_finances,1,'FUNDING_FINANCES');
SET @s_your_funding=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Labour',1,@generic_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_labour=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Overhead costs',2,@generic_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_overheads=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Materials',3,@generic_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_materials=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Capital usage',4,@generic_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_capital_usage=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Subcontracting costs',5,@generic_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_subcontracting=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Travel and subsistence',6,@generic_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_travel=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Other costs',7,@generic_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_other_costs=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,'This is the financial overview of all partners in this collaboration. Each partner should submit their organisation\'s finances in the \'your finances\' section. All partners will see this level of detail.',1,'Finances overview',8,@generic_template_id,@s_finances,1,'OVERVIEW_FINANCES');
SET @s_finance_overview=LAST_INSERT_ID();


/* Project details questions */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'Enter the full title of the project',1,0,'Application details','Application details',1,NULL,@generic_template_id,@s_project_details,NULL,'GENERAL');
SET @q_application_details=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,5,@generic_template_id,1,'Application details',NULL,NULL,0,@q_application_details,'APPLICATION',1);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide a short summary of your project. Make sure you include what is innovative about it.',1,0,'Project summary','Project summary',2,NULL,@generic_template_id,@s_project_details,NULL,'GENERAL');
SET @q_project_summary=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@generic_template_id,1,'Project summary','What should I include in the project summary?','<p>We will not score this summary, but it will give the assessors a useful introduction to your project. It should provide a clear overview of the whole project, including:</p> <ul class=\"list-bullet\">         <li>your vision for the project</li><li>key objectives</li><li>main areas of focus</li><li>details of how it is innovative</li></ul>',0,@q_project_summary,'APPLICATION',1);
SET @main_project_summary=LAST_INSERT_ID();
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_project_summary, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_project_summary, @word_count_validator);


INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide a brief description of your project. If your application is successful, we will publish this description. This question is mandatory but we will not assess this content as part of your application.',1,0,'Public description','Public description',3,NULL,@generic_template_id,@s_project_details,NULL,'GENERAL');
SET @q_public_description=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@generic_template_id,1,'Public description','What should I include in the project public description?','<p>Innovate UK publishes information about projects we have funded. This is in line with government practice on openness and transparency of public-funded activities.</p><p>Describe your project in a way that will be easy for a non-specialist to understand. Don\'t include any information that is confidential, for example, intellectual property or patent details.</p> ',0,@q_public_description,'APPLICATION',1);
SET @main_public_description=LAST_INSERT_ID();
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES (@main_public_description, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_public_description, @word_count_validator);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'If your application doesn\'t align with the scope, we will reject it.',1,0,'How does your project align with the scope of this competition?','Scope',4,NULL,@generic_template_id,@s_project_details,NULL,'GENERAL');
SET @q_scope=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@generic_template_id,1,'How does your project align with the scope of this competition?','What should I include in the project scope?','<p>It is important that you read the following guidance.</p><p>To show how your project aligns with the scope of this competition, you need to:</p><ul class=\"list-bullet\">         <li>read the competition brief in full</li><li>understand the background, challenge and scope of the competition</li><li>address the research objectives in your application</li><li>match your project\'s objectives and activities to these</li></ul> <p>Once you have submitted your application, you should not change this section unless:</p><ul class=\"list-bullet\">         <li>we ask you to provide more information</li><li>we ask you to make it clearer</li></ul> ',0,@q_scope,'APPLICATION',1);
SET @how_does_scope=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,21,@generic_template_id,0,'Please select the research category for this project',NULL,NULL,0,@q_scope,'ASSESSMENT',1);
SET @please_select_scope=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,22,@generic_template_id,0,'Is the application in scope?',NULL,NULL,0,@q_scope,'ASSESSMENT',1);
SET @is_the_scope=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (100,2,@generic_template_id,0,'Feedback','Guidance for assessing scope','Your answer should be based upon the following:',0,@q_scope,'ASSESSMENT',1);
SET @f_scope=LAST_INSERT_ID();
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_scope,'NO','One or more of the above requirements have not been satisfied.',0);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_scope,'YES','The application contains the following:\nIs the consortia business led?\nAre there two or more partners to the collaboration?\nDoes it meet the scope of the competition as defined in the competition brief?',1);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@how_does_scope, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@please_select_scope, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@is_the_scope, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_scope, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@how_does_scope, @word_count_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_scope, @word_count_validator);

/* Application questions
ACTUAL TEMPLATE QUESTIONS */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,1,0,'What is the business opportunity that your project addresses?','Business opportunity',5,1,@generic_template_id,@s_application_questions,10,'GENERAL');
SET @q_business_opportunity=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@generic_template_id,1,'1. What is the business opportunity that your project addresses?','What should I include in the business opportunity section?','<p>You should describe:</p><ul class=\"list-bullet\">         <li>the business opportunity you have identified and how you plan to take advantage of it</li><li>the customer needs you have identified and how your project will meet them</li><li>the challenges you expect to face and how you will overcome them</li></ul>',0,@q_business_opportunity,'APPLICATION',1);
SET @main_business_opportunity=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,23,@generic_template_id,0,'Question score',NULL,NULL,0,@q_business_opportunity,'ASSESSMENT',1);
SET @score_business_opportunity=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,4,@generic_template_id,1,'Appendix','What should I include in the appendix?','<p>You may include an appendix of additional information to support the technical approach the project will undertake.</p><p>You may include, for example, a Gantt chart or project management structure.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 6 sides of A4. Longer appendices will only have the first 6 pages assessed</li><li>be less than 1mb in size</li></ul>',1,@q_business_opportunity,'APPLICATION',0);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (100,2,@generic_template_id,0,'Feedback','Guidance for assessing business opportunity','Your score should be based upon the following:',0,@q_business_opportunity,'ASSESSMENT',1);
SET @f_business_opportunity=LAST_INSERT_ID();
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_business_opportunity,'1,2','There is little or no business drive to the project. The results are not relevant to the target customers or no customer interests are provided.',4);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_business_opportunity,'3,4','The business opportunity is unrealistic or poorly defined. The customer\'s true needs are not well understood and are not linked to the project\'s objectives.',3);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_business_opportunity,'5,6','The business opportunity is plausible but not clearly expressed in terms of customer needs.',2);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_business_opportunity,'7,8','The applicants have a good idea of the potential market and opportunities. The needs of the customer are central to the project\'s objectives.',1);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_business_opportunity,'9,10','The applicants have a very clear understanding of the business opportunity and the problems that must be overcome to enable successful exploitation. The project is well aligned with these needs.',0);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_business_opportunity, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@score_business_opportunity, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_business_opportunity, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_business_opportunity, @word_count_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_business_opportunity, @word_count_validator);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,1,0,'What is the size of the potential market for your project?','Potential market',6,'2',@generic_template_id,@s_application_questions,10,'GENERAL');
SET @q_potential_market=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@generic_template_id,1,'2. What is the size of the potential market for your project?','What should I include in the market opportunity section?','<p>Describe the size of the potential market for your project, including:</p><ul class=\"list-bullet\">         <li>details of your target market, for instance, how competitive and profitable it is</li><li>the current size of the market, with actual and predicted growth rates</li><li>the market share you expect to achieve and the reasons for this estimate</li><li>the wider economic value you expect your project to add to the UK and/or the EEA (European Economic Area)</li></ul><p>Tell us what return on investment you expect your project to achieve. You should base this estimate on relevant industry data and tell us how you have calculated this.</p><p>If you are targeting an undeveloped market, you should also:</p><ul class=\"list-bullet\">         <li>describe how you plan to access this market</li><li>estimate its potential size</li><li>explain how you will explore its potential</li></ul>',0,@q_potential_market,'APPLICATION',1);
SET @main_potential_market=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,23,@generic_template_id,0,'Question score',NULL,NULL,0,@q_potential_market,'ASSESSMENT',1);
SET @score_potential_market=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,4,@generic_template_id,1,'Appendix','What should I include in the appendix?','<p>You may include an appendix of additional information to support the technical approach the project will undertake.</p><p>You may include, for example, a Gantt chart or project management structure.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 6 sides of A4. Longer appendices will only have the first 6 pages assessed</li><li>be less than 1mb in size</li></ul>',1,@q_potential_market,'APPLICATION',0);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (100,2,@generic_template_id,0,'Feedback','Guidance for assessing market opportunity','Your score should be based upon the following:',0,@q_potential_market,'ASSESSMENT',1);
SET @f_potential_market=LAST_INSERT_ID();
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_potential_market,'1,2','The market is not well defined or is wrong. No sensible return on investment is provided.',4);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_potential_market,'3,4','The market size is not quantified but there is some understanding. Return on investment is ill defined or unrealistic.',3);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_potential_market,'5,6','The market size and dynamics are understood but poorly quantified or stated at a level not really relevant for the project. Return on investment is plausible or badly defined.',2);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_potential_market,'7,8','The market size and dynamics are described with some quantification relevant to the project. Market understanding is acceptable and the return on investment is achievable.',1);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_potential_market,'9,10','The market size and dynamics are quantified clearly and to sufficient resolution to be relevant to the project. The market is clearly well understood. The return on investment is clearly stated, quantified and realistic.',0);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_potential_market, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@score_potential_market, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_potential_market, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_potential_market, @word_count_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_potential_market, @word_count_validator);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,1,0,'How will you exploit and market your project?','Project exploitation',7,'3',@generic_template_id,@s_application_questions,10,'GENERAL');
SET @q_project_exploitation=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@generic_template_id,1,'3. How will you exploit and market your project?','What should I include in the project exploitation section?','<p>Describe the potential outputs of the project, such as:</p><ul class=\"list-bullet\">         <li>products or services</li><li>processes</li><li>applications</li></ul><p>Describe how you will exploit these outputs, such as:</p><ul class=\"list-bullet\">         <li>the route to market</li><li>protection of intellectual property rights</li><li>reconfiguration of your organisation\'s value system</li><li>changes to business models and processes</li><li>any other methods of exploitation and protection</li></ul> ',0,@q_project_exploitation,'APPLICATION',1);
SET @main_project_exploitation=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,23,@generic_template_id,0,'Question score',NULL,NULL,0,@q_project_exploitation,'ASSESSMENT',1);
SET @score_project_exploitation=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,4,@generic_template_id,1,'Appendix','What should I include in the appendix?','<p>You may include an appendix of additional information to support the technical approach the project will undertake.</p><p>You may include, for example, a Gantt chart or project management structure.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 6 sides of A4. Longer appendices will only have the first 6 pages assessed</li><li>be less than 1mb in size</li></ul>',1,@q_project_exploitation,'APPLICATION',0);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (100,2,@generic_template_id,0,'Feedback','Guidance for assessing project exploitation','Your score should be based upon the following:',0,@q_project_exploitation,'ASSESSMENT',1);
SET @f_project_exploitation=LAST_INSERT_ID();
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_project_exploitation,'1,2','The exploitation method is missing or un-feasible and unlikely to succeed.',4);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_project_exploitation,'3,4','The exploitation and dissemination methods described are unrealistic or ill-defined.',3);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_project_exploitation,'5,6','An exploitation method is defined but lacking in detail or is only just feasible. Dissemination is mentioned.',2);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_project_exploitation,'7,8','The main exploitable output of the project is identified and a realistic method defined. Some dissemination is also explained.',1);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_project_exploitation,'9,10','The principle exploitable outputs of the project are identified together with clear and achievable exploitation methods. Dissemination opportunities are also identified and appropriate.',0);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_project_exploitation, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@score_project_exploitation, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_project_exploitation, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_project_exploitation, @word_count_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_project_exploitation, @word_count_validator);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,1,0,'What economic, social and environmental benefits do you expect your project to deliver and when?','Economic benefit',8,'4',@generic_template_id,@s_application_questions,10,'GENERAL');
SET @q_economic_benefit=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@generic_template_id,1,'4. What economic, social and environmental benefits do you expect your project to deliver and when?','What should I include in the benefits section?','<p>Describe all the benefits you expect your project to deliver, including:</p><p><strong>Economic</strong> : this is the real impact the project will have on its economic environment. This is not traditional corporate accounting profit and can include cost avoidance. You should identify and quantify any expected benefits to:</p><ul class=\"list-bullet\"><li>users (intermediaries and end users)</li><li>suppliers</li><li>broader industrial markets</li><li>the UK economy</li></ul><p><strong>Social</strong> : quantify any expected social impacts either positive or negative on, for example:</p><ul class=\"list-bullet\"><li>quality of life</li><li>social inclusion/exclusion</li><li>education</li><li>public empowerment</li><li>health and safety</li><li>regulation</li><li>diversity</li><li>government priorities</li></ul><p><strong>Environmental</strong> : show how your project will benefit or have a low impact on the environment. For example, this could include:<p><ul class=\"list-bullet\"><li>careful management of energy consumption</li><li>reductions in carbon emissions</li><li>reducing manufacturing and materials waste</li><li>rendering waste less toxic before disposing of it in a safe and legal manner</li><li>re-manufacturing (cradle to cradle)</li></ul>',0,@q_economic_benefit,'APPLICATION',1);
SET @main_economic_benefit=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,23,@generic_template_id,0,'Question score',NULL,NULL,0,@q_economic_benefit,'ASSESSMENT',1);
SET @score_economic_benefit=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,4,@generic_template_id,1,'Appendix','What should I include in the appendix?','<p>You may include an appendix of additional information to support the technical approach the project will undertake.</p><p>You may include, for example, a Gantt chart or project management structure.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 6 sides of A4. Longer appendices will only have the first 6 pages assessed</li><li>be less than 1mb in size</li></ul>',1,@q_economic_benefit,'APPLICATION',0);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (100,2,@generic_template_id,0,'Feedback','Guidance for assessing economic benefits','Your score should be based upon the following:',0,@q_economic_benefit,'ASSESSMENT',1);
SET @f_economic_benefit=LAST_INSERT_ID();
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_economic_benefit,'1,2','The project is damaging to other stakeholders with no realistic mitigation or balance described.',4);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_economic_benefit,'3,4','The project has no outside benefits or is potentially damaging to other stakeholders. No mitigation or exploitation is suggested.',3);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_economic_benefit,'5,6','Some positive outside benefits are described but the methods to exploit these are not obvious. Or the project is likely to have a negative impact but some mitigation or a balance against the internal benefits is proposed.',2);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_economic_benefit,'7,8','Some positive outside benefits are defined and are realistic. Methods of addressing these opportunities are described.',1);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_economic_benefit,'9,10','Inside and outside benefits are well defined, realistic and of significantly positive economic, environmental or social impact. Routes to exploit these benefits are also provided.',0);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_economic_benefit, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@score_economic_benefit, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_economic_benefit, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_economic_benefit, @word_count_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_economic_benefit, @word_count_validator);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Describe the areas of work and your objectives. List all resource and management needs. Provide an overview of your technical approach.',1,0,'What technical approach will you use and how will you manage your project?','Technical approach',9,'5',@generic_template_id,@s_application_questions,10,'GENERAL');
SET @q_technical_approach=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@generic_template_id,1,'5. What technical approach will you use and how will you manage your project?','What should I include in the technical approach section?','<p>You should:</p><ul class=\"list-bullet\">         <li>describe your technical approach including the main objectives of the work</li><li>explain how and why your approach is appropriate</li><li>tell us how you will make sure that the innovative steps in your project are achievable</li><li>describe rival technologies and alternative R&D strategies</li><li>explain why your proposed approach will offer a better outcome</li></ul>',0,@q_technical_approach,'APPLICATION',1);
SET @main_technical_approach=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,4,@generic_template_id,1,'Appendix','What should I include in the appendix?','<p>You may include an appendix of additional information to support the technical approach the project will undertake.</p><p>You may include, for example, a Gantt chart or project management structure.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 6 sides of A4. Longer appendices will only have the first 6 pages assessed</li><li>be less than 1mb in size</li></ul>',0,@q_technical_approach,'APPLICATION',1);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,23,@generic_template_id,0,'Question score',NULL,NULL,0,@q_technical_approach,'ASSESSMENT',1);
SET @score_technical_approach=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (100,2,@generic_template_id,0,'Feedback','Guidance for assessing technical approach','Your score should be based upon the following:',0,@q_technical_approach,'ASSESSMENT',1);
SET @f_technical_approach=LAST_INSERT_ID();
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_technical_approach,'1,2','The plan is totally unrealistic or fails to meet the objectives of the project.',4);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_technical_approach,'3,4','The plan has serious deficiencies or major missing aspects. The plan has little chance of meeting the objectives of the project.',3);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_technical_approach,'5,6','The plan is not completely described or there may be deficiencies in some aspects. More work will be required before the plan can be said to be realistic.',2);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_technical_approach,'7,8','The plan is well described and complete. There is a reasonable chance that it will meet the objectives of the project.',1);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_technical_approach,'9,10','The project plan is fully described and complete with milestones and timeframes. The plan is realistic and should meet the objectives of the project.',0);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_technical_approach, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@score_technical_approach, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_technical_approach, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_technical_approach, @word_count_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_technical_approach, @word_count_validator);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Explain how your project is innovative in both a commercial and technical sense.',1,0,'What is innovative about your project?','Innovation',10,'6',@generic_template_id,@s_application_questions,10,'GENERAL');
SET @q_innovation=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@generic_template_id,1,'6. What is innovative about your project?','What should I include in the project innovation section?','<p>You should show how your project will:</p><ul class=\"list-bullet\">         <li>push boundaries beyond current leading-edge science and technology</li><li>apply existing technologies in new areas</li></ul><p>Explain the novelty of the research in an industrial and/or academic context.</p><p>You should provide evidence that your proposed work is innovative. This could include patent search results, competitor analyses or literature surveys. If relevant, you should also outline your own intellectual property rights.</p>',0,@q_innovation,'APPLICATION',1);
SET @main_innovation=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,4,@generic_template_id,1,'Appendix','What should I include in the appendix?','<p>You may include an appendix of additional information to support your response to this question. This appendix may include graphics describing the innovation or the nature of the problem. You may want to include evidence of freedom to operate, patent searches or competitor analysis as supporting information.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 5 sides of A4. Longer appendices will only have the first 5 pages assessed</li><li>be less than 1mb in size</li></ul>',0,@q_innovation,'APPLICATION',1);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,23,@generic_template_id,0,'Question score',NULL,NULL,0,@q_innovation,'ASSESSMENT',1);
SET @score_innovation=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (100,2,@generic_template_id,0,'Feedback','Guidance for assessing innovation','Your score should be based upon the following:',0,@q_innovation,'ASSESSMENT',1);
SET @f_innovation=LAST_INSERT_ID();
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_innovation,'1,2','The project is either not innovative or there is no exploitable route due to previous IP.',4);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_innovation,'3,4','The project lacks sufficient innovation both technically and commercially.',3);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_innovation,'5,6','The project is innovative but there is a lack of presented evidence as to the freedom to operate.',2);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_innovation,'7,8','The project will be innovative and relevant to the market. There is high confidence that there is freedom to operate.',1);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_innovation,'9,10','The project is significantly innovative either commercially or technically and will make a substantial contribution to the field. Solid evidence is presented to substantiate the level of innovation.',0);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_innovation, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@score_innovation, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_innovation, @not_empty_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@main_innovation, @word_count_validator);
INSERT INTO `form_input_validator` (form_input_id, form_validator_id) VALUES(@f_innovation, @word_count_validator);

/* No questions for finances section */
/* No questions for your finances section */

/* Your project costs question */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'Only your organisation can see this level of detail. All members of your organisation can access and edit your finances. We recommend assigning completion of your finances to one member of your team. <a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\" rel=\"external\">Find out which project costs are eligible.</a> ',1,1,'Provide the project costs for \'{organisationName}\'','Project finances',15,NULL,@generic_template_id,@s_your_project_costs,NULL,'GENERAL');
SET @q_your_project_costs=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,15,@generic_template_id,1,NULL,'','',0,@q_your_project_costs,'APPLICATION',1);

/* Your organisation question */
SET @staff_count_id = (SELECT id FROM form_input_type WHERE `name` =  'STAFF_COUNT');
SET @staff_turnover_id = (SELECT id FROM form_input_type WHERE `name` =  'ORGANISATION_TURNOVER');
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'To determine the level of funding you are eligible to receive please provide your business size using the <a href=\"http://ec.europa.eu/growth/smes/business-friendly-environment/sme-definition/index_en.htm\" target=\"_blank\" rel=\"external\">EU Definition</a> for guidance.',1,1,'Organisation size','Business size',18,NULL,@generic_template_id,@s_your_organisation,NULL,'GENERAL');
SET @q_your_organisation=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,19,@generic_template_id,1,'Organisation Size',NULL,NULL,0,@q_your_organisation,'APPLICATION',1);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,4,@generic_template_id,1,'Appendix','What should I include in the appendix?','<p>You may include an appendix of additional information to support the technical approach the project will undertake.</p><p>You may include, for example, a Gantt chart or project management structure.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 6 sides of A4. Longer appendices will only have the first 6 pages assessed</li><li>be less than 1mb in size</li></ul>',1,@q_your_organisation,'APPLICATION',0);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,@staff_turnover_id,@generic_template_id,0,'Turnover (£)','Your turnover from the last financial year.','',1,@q_your_organisation,'APPLICATION',1);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,@staff_count_id,@generic_template_id,0,'Full time employees','Number of full time employees at your organisation.','',2,@q_your_organisation,'APPLICATION',1);

/* Add a form input under the organisation size question for all competitions and templates. Default is inactive.
 Financial Year End. Get the form input type and then do an insert for every organisation size question. */
SET @financial_year_end_id = (SELECT id FROM form_input_type WHERE `name` =  'FINANCIAL_YEAR_END');
INSERT INTO form_input (word_count, form_input_type_id, competition_id, included_in_application_summary, description, guidance_title, guidance_answer, priority, question_id, scope, active)
     SELECT null, @financial_year_end_id, q.competition_id, false, "End of last financial year", "Enter the date of your last financial year.", "", (SELECT MAX(priority) + 1 FROM form_input AS fi WHERE q.id = fi.question_id), q.id AS `question_id`, "APPLICATION", false
     FROM question AS q
     WHERE q.id = @q_your_organisation;

/* Financial Overview rows. */
SET @financial_overview_row_id = (SELECT id FROM form_input_type WHERE `name` =  'FINANCIAL_OVERVIEW_ROW');
INSERT INTO form_input (word_count, form_input_type_id, competition_id, included_in_application_summary, description, guidance_title, guidance_answer, priority, question_id, scope, active)
     SELECT null, @financial_overview_row_id, q.competition_id, false, "Annual turnover", "", "", (SELECT MAX(priority) + 1 FROM form_input AS fi WHERE q.id = fi.question_id), q.id AS `question_id`, "APPLICATION", false
     FROM question AS q
     WHERE q.id = @q_your_organisation;
INSERT INTO form_input (word_count, form_input_type_id, competition_id, included_in_application_summary, description, guidance_title, guidance_answer, priority, question_id, scope, active)
     SELECT null, @financial_overview_row_id, q.competition_id, false, "Annual profits", "", "", (SELECT MAX(priority) + 1 FROM form_input AS fi WHERE q.id = fi.question_id), q.id AS `question_id`, "APPLICATION", false
     FROM question AS q
     WHERE q.id = @q_your_organisation;
INSERT INTO form_input (word_count, form_input_type_id, competition_id, included_in_application_summary, description, guidance_title, guidance_answer, priority, question_id, scope, active)
     SELECT null, @financial_overview_row_id, q.competition_id, false, "Annual export", "", "", (SELECT MAX(priority) + 1 FROM form_input AS fi WHERE q.id = fi.question_id), q.id AS `question_id`, "APPLICATION", false
     FROM question AS q
     WHERE q.id = @q_your_organisation;
INSERT INTO form_input (word_count, form_input_type_id, competition_id, included_in_application_summary, description, guidance_title, guidance_answer, priority, question_id, scope, active)
     SELECT null, @financial_overview_row_id, q.competition_id, false, "Research and development spend", "", "", (SELECT MAX(priority) + 1 FROM form_input AS fi WHERE q.id = fi.question_id), q.id AS `question_id`, "APPLICATION", false
     FROM question AS q
     WHERE q.id = @q_your_organisation;

/* Full time employees at year end */
SET @financial_staff_count_id = (SELECT id FROM form_input_type WHERE `name` =  'FINANCIAL_STAFF_COUNT');
INSERT INTO form_input (word_count, form_input_type_id, competition_id, included_in_application_summary, description, guidance_title, guidance_answer, priority, question_id, scope, active)
     SELECT null, @financial_staff_count_id, q.competition_id, false, "Full time employees", "How many full-time employees did you have on the project at the close of your last financial year?", "", (SELECT MAX(priority) + 1 FROM form_input AS fi WHERE q.id = fi.question_id), q.id AS `question_id`, "APPLICATION", false
     FROM question AS q
     WHERE q.id = @q_your_organisation;

/* Connect the validator to the form inputs */
SET @past_month_validator_id = (SELECT id FROM form_validator WHERE title = 'PastMMYYYYValidator');
INSERT INTO form_input_validator (`form_input_id`, `form_validator_id`)
     SELECT fi.id, @past_month_validator_id
     FROM form_input AS fi
    WHERE fi.form_input_type_id IN (@financial_year_end_id)
    AND fi.competition_id=@generic_template_id;

SET @integer_validator_id = (SELECT id FROM form_validator WHERE title = 'SingedLongIntegerValidator');
INSERT INTO form_input_validator (`form_input_id`, `form_validator_id`)
     SELECT fi.id, @integer_validator_id
     FROM form_input AS fi
    WHERE fi.form_input_type_id IN (@financial_overview_row_id)
    AND fi.competition_id=@generic_template_id;

/* Connect the validator to the form inputs */
SET @non_negative_integer_validator_id = (SELECT id FROM form_validator WHERE title = 'NonNegativeLongIntegerValidator');
INSERT INTO form_input_validator (`form_input_id`, `form_validator_id`)
     SELECT fi.id, @non_negative_integer_validator_id
     FROM form_input AS fi
    WHERE fi.form_input_type_id IN (@financial_staff_count_id, @staff_count_id, @staff_turnover_id)
    AND fi.competition_id=@generic_template_id;

SET @financial_year_end_type_id = (SELECT id FROM form_input_type WHERE `name` =  'FINANCIAL_YEAR_END');
SET @financial_overview_row_type_id = (SELECT id FROM form_input_type WHERE `name` =  'FINANCIAL_OVERVIEW_ROW');
SET @financial_staff_count_type_id = (SELECT id FROM form_input_type WHERE `name` =  'FINANCIAL_STAFF_COUNT');

/*  Currently the only competition of type sector is the template - set active to false for all of the relevant
form inputs then change to active for the sector template. */
UPDATE form_input SET active = false
 WHERE competition_id=@generic_template_id
   AND (form_input_type_id=@financial_year_end_type_id OR form_input_type_id=@financial_overview_row_type_id OR form_input_type_id=@financial_staff_count_type_id);


/* Your funding question */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'Please tell us if you have ever applied for or received any other public sector funding for this project. You should also include details of any offers of funding you\'ve received.',1,1,'Other funding','Other funding',20,NULL,@generic_template_id,@s_your_funding,NULL,'COST');
SET @q_other_funding=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,17,@generic_template_id,1,'Other funding','What should I include in the other public funding section?','<p>You must provide details of other public funding that you are currently applying for (or have already applied for) in relation to this project. You do not need to include completed grants that were used to reach this point in the development process. This information is important as other public sector support counts as part of the funding you can receive for your project.</p>',0,@q_other_funding,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'Please enter the funding level that you would like to apply for in this application',1,1,'Funding level','Funding level',19,NULL,@generic_template_id,@s_your_funding,NULL,'GENERAL');
SET @q_funding_level=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,7,@generic_template_id,1,'Please enter the grant % you wish to claim for this project','What funding level should I enter?','<p>For a business or academic organisation, you can apply for any funding percentage between 0% and the maximum allowable for your organisation size. For other organisation types, you can apply for any funding percentage between 0% and 100%. The amount you apply for must reflect other funding you may have received. It must also be within participation levels which you can review on the Finances Overview page.</p>',0,@q_funding_level,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,NULL,1,1,'Upload a pdf copy of the Je-S output confirming a status of \'With Council\'','Je-s Output',20,NULL,@generic_template_id,@s_your_funding,NULL,'GENERAL');
SET @q_jes_output=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,20,@generic_template_id,1,'Upload a pdf copy of the Je-S output form once you have a status of \'With Council\'.','How do I create my Je-S output?','<p>You should include only supporting information in the appendix. You shouldn’t use it to provide your responses to the question.</p><p>Guidance for this section needs to be created</p>',0,@q_jes_output,'APPLICATION',1);

/* Labour question */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You may claim the labour costs of all individuals you have working on your project.</p> <p> If your application is awarded funding, you will need to account for all your labour costs as they occur. For example, you should keep timesheets and payroll records. These should show the actual hours worked by individuals and paid by the organisation.</p>',0,1,NULL,NULL,1,NULL,@generic_template_id,@s_labour,NULL,'GENERAL');
SET @q_labour_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@generic_template_id,1,NULL,'Labour costs guidance','<p>You can include the following labour costs, based upon your PAYE records:</p><ul class=\"list-bullet\"><li>gross salary</li><li>National Insurance</li><li>company pension contribution</li><li>life insurance</li><li>other non-discretionary package costs.</li></ul><p>You can\'t include:</p><ul class=\"list-bullet\"><li>discretionary bonuses</li><li>performance related payments of any kind</li></ul><p>You may include the total number of working days for staff but do not include:</p><ul class=\"list-bullet\"><li>sick days</li><li>waiting time</li><li>training days</li><li>non-productive time</li></ul><p>Enter the total number of working days in the year. List the total days worked by all categories of staff on your project. Describe their role.</p><p>We will review the total amount of time and cost of labour before we approve your application. The terms and conditions of the grant include compliance with these points.</p>',0,@q_labour_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,1,1,'Labour',NULL,2,NULL,@generic_template_id,@s_labour,NULL,'COST');
SET @q_labour_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,8,@generic_template_id,1,'Labour',NULL,NULL,0,@q_labour_cost,'APPLICATION',1);

/* Overheads question */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,0,1,NULL,NULL,1,NULL,@generic_template_id,@s_overheads,NULL,'GENERAL');
SET @q_overhead_empty=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@generic_template_id,1,NULL,NULL,NULL,0,@q_overhead_empty,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You may incur indirect support staff costs linked with your administrative work for the project. To be eligible, these costs should be directly attributable and incremental to the project. Indirect costs associated with commercial activities are not eligible and must not be included. For further information on which costs are eligible please read our <a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\">project costs guidance</a>.</p>',1,1,'Overheads','Indirect costs',2,NULL,@generic_template_id,@s_overheads,NULL,'GENERAL');
SET @q_overhead=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,9,@generic_template_id,1,'Overheads',NULL,NULL,0,@q_overhead,'APPLICATION',1);

/* Materials question */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You can claim the costs of materials used on your project providing:</p><ul class=\"list-bullet\"><li>they are not already purchased or included in the administration support costs</li><li>they are purchased from third parties</li><li>they won’t have a residual/resale value at the end of your project. If they do you can claim the costs minus this value</li></ul><p><a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\" rel=\"external\">Please refer to our guide to project costs for further information.</a></p>',0,1,NULL,NULL,1,NULL,@generic_template_id,@s_materials,NULL,'GENERAL');
SET @q_materials_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@generic_template_id,1,NULL,'Materials costs guidance','<p>Materials supplied by associated companies or project partners should be charged at cost.</p><p>Software that you have purchased specifically for use during your project may be included. If you already own the software then only additional costs which are incurred and paid during your project, will be eligible. For example, installation, training or customisation.</p><p>Material costs must be itemised to justify that they are eligible.</p>',0,@q_materials_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide a breakdown of the materials you expect to use during the project',1,1,'Materials','Materials',2,NULL,@generic_template_id,@s_materials,NULL,'COST');
SET @q_materials_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,10,@generic_template_id,1,'Materials',NULL,NULL,0,@q_materials_cost,'APPLICATION',1);

/* Capital usage */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You should provide details of capital equipment and tools you will buy for, or use on, your project.</p>',0,1,NULL,NULL,1,NULL,@generic_template_id,@s_capital_usage,NULL,'GENERAL');
SET @q_capital_usage_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@generic_template_id,1,NULL,'Capital usage guidance','<p>You will need to calculate a ‘usage’ value for each item. You can do this by deducting its expected value from its original price at the end of your project. If you owned the equipment before the project started then you should use its Net Present Value.</p><p>This value is then multiplied by the amount, in percentages, that is used during the project. This final value represents the eligible cost to your project.</p>',0,@q_capital_usage_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide a breakdown of the capital items you will buy and/or use for the project.',1,1,'Capital Usage','Capital items',2,NULL,@generic_template_id,@s_capital_usage,NULL,'COST');
SET @q_capital_usage_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,11,@generic_template_id,1,'Capital Usage',NULL,NULL,0,@q_capital_usage_cost,'APPLICATION',1);

/* Subcontracting costs */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You may subcontract work if you don’t have the expertise in your consortium. You can also subcontract if it is cheaper than developing your skills in-house.</p>',0,1,NULL,NULL,1,NULL,@generic_template_id,@s_subcontracting,NULL,'GENERAL');
SET @q_subcontracting_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@generic_template_id,1,NULL,'Subcontracting costs guidance','<p>Subcontracting costs relate to work carried out by third party organisations. These organisations are not part of your project or collaboration.</p><p>Subcontracting is eligible providing it’s justified as to why the work cannot be performed by a project partner.</p><p>Where possible you should select a UK based contractor. You should name the subcontractor (where known) and describe what they will be doing. You should also state where the work will be undertaken. We will look at the size of this contribution when assessing your eligibility and level of support.</p>',0,@q_subcontracting_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide details of any work that you expect to subcontract for your project.',1,1,'Sub-contracting costs','Sub-contracts',2,NULL,@generic_template_id,@s_subcontracting,NULL,'COST');
SET @q_subcontracting_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,12,@generic_template_id,1,'Sub-contracting costs',NULL,NULL,0,@q_subcontracting_cost,'APPLICATION',1);

/* Travel costs */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You should include travel and subsistence costs that relate only to this project. </p>',0,1,NULL,NULL,1,NULL,@generic_template_id,@s_travel,NULL,'GENERAL');
SET @q_travel_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@generic_template_id,1,NULL,NULL,NULL,0,@q_travel_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,1,1,'Travel and subsistence',NULL,2,NULL,@generic_template_id,@s_travel,NULL,'COST');
SET @q_travel_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,13,@generic_template_id,1,'Travel and subsistence',NULL,NULL,0,@q_travel_cost,'APPLICATION',1);

/* Other costs */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>Please tell us if you have applied for or received any other public sector funding for this project. Any other funding received will need to be deducted from the total value of any funding you are claiming for this project.</p>',0,1,NULL,NULL,1,NULL,@generic_template_id,@s_other_costs,NULL,'GENERAL');
SET @q_other_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@generic_template_id,1,NULL,'Other costs guidance','<p>Examples of other costs include:</p><p><strong>Training costs:</strong> these costs are eligible for support if they relate to your project. We may support management training for your project but will not support ongoing training.</p><p><strong>Preparation of technical reports:</strong> if, for example, the main aim of your project is standard support or technology transfer. You should show how this is more than you would produce through good project management.</p><p><strong>Market assessment:</strong> we may support market assessments studies. The study will need to help us understand how your project is a good match for your target market. It could also be eligible if it helps commercialise your product.</p><p><strong>Licensing in new technologies:</strong> if new technology makes up a large part of your project, we will expect you to develop that technology. For instance, if the value of the technology is more than &pound;100,000.</p><p><strong>Patent filing costs for New IP generated by your project:</strong> these are eligible for SMEs up to a limit of &pound;7,500 per partner. You should not include legal costs relating to the filing or trademark related expenditure.</p><p>Regulatory compliance costs are eligible if necessary to carry out your project.</p>',0,@q_other_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please note that legal or project audit and accountancy fees are not eligible and should not be included as an \'other cost’. Patent filing costs of New IP relating to the project are limited to £7,500 for SME applicants only.  Please provide estimates of other costs that do not fit within any other cost headings.',1,1,'Other costs','Other costs',2,NULL,@generic_template_id,@s_other_costs,NULL,'COST');
SET @q_other_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,14,@generic_template_id,1,'Other costs',NULL,NULL,0,@q_other_cost,'APPLICATION',1);


/* Finance overview questions */
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,0,0,'FINANCE_SUMMARY_INDICATOR_STRING',NULL,17,NULL,@generic_template_id,@s_finance_overview,NULL,'GENERAL');
SET @q_finance_summary_indicator=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,16,@generic_template_id,1,NULL,NULL,NULL,0,@q_finance_summary_indicator,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'<h2 class=\"heading-medium\">Funding rules for this competition</h2><p>We will fund projects between &pound;500,000 and &pound;1.5 million. We may consider projects with costs outside of this range. We expect projects to last between 12 and 36 months.</p><p>Innovate UK\'s aim is to optimise the level of funding businesses receive. We also recognise the importance of research organisations\' contribution to R&amp;D projects. Therefore we require the following levels of participation:</p><ul class=\"list-bullet\"> <li>at least 70% of the total eligible project costs are incurred by commercial organisations and</li> <li>a maximum of 30% of total eligible project costs are available to research participants. Where there is more than one research participant, this maximum will be shared between them.</li></ul>',0,0,NULL,NULL,16,NULL,@generic_template_id,@s_finance_overview,NULL,'GENERAL');
SET @q_funding_rules=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@generic_template_id,1,NULL,NULL,NULL,0,@q_funding_rules,'APPLICATION',1);

/* Assessor counts for this new competition type */
INSERT INTO `assessor_count_option` (`competition_type_id`, `option_name`, `option_value`, `default_option`)
VALUES
(@competition_type_generic_id, '1', 0, 0),
(@competition_type_generic_id, '3', 0, 0),
(@competition_type_generic_id, '5', 0, 1);
