FROM ifshibdev/idp-base:1.1.15

ENV DEBIAN_FRONTEND=noninteractive \
  HTTP_PORT=9080 \
  HTTPS_PORT=9443 \
  IDP_DOMAIN=idp \
  SP_DOMAIN=ifs.local-dev \

  JAVA_HOME=/usr/lib/jvm/java-8-oracle \
  JAVA_KEYSTORE_PASSWORD="@java_keystore_password@" \

  LDAP_URL="ldaps://ldap:8389" \
  LDAP_PORT="8389" \
  LDAP_USESTARTTLS=false \
  LDAP_USESSL=true \
  LDAP_BASEDN="dc=nodomain" \
  LDAP_BINDDN="cn=admin,dc=nodomain" \
  LDAP_BINDDNCREDENTIAL="default" \
  LDAP_RETURNATTRIBUTES="mail,uid" \
  LDAP_PPOLICYDN="cn=PPolicy,ou=Policies" \
  LDAP_PPOLICY="true" \
  LDAP_USERFILTER="(&(mail={user})(!(employeeType=inactive)))" \
  LDAP_AUTHENTICATOR="anonSearchAuthenticator" \
  LDAP_ATTRIBUTE_SEARCHFILTER="(mail=\$resolutionContext.principal)" \
  LDAP_VALIDATEPERIOD="PT20S" \
  REGAPIKEY=@auth_idp_regapikey@ \

  GOOGLEANALYTICS_TRACKINGID="#" \
  IDP_PROXY_KEY="@auth_idp_proxy_key@" \
  IDP_PROXY_CERTIFICATE="@auth_idp_proxy_certificate@" \
  IDP_PROXY_CACERTIFICATE="@auth_idp_proxy_cacertificate@" \
  SP_PROXY_CERTIFICATE="@auth_sp_proxy_certificate@" \
  IDP_SAML_SIGNING_KEY="@auth_idp_signing_key@" \
  IDP_SAML_SIGNING_CERTIFICATE="@auth_idp_signing_certificate@" \
  IDP_SAML_ENCRYPTION_KEY="@auth_idp_encryption_key@" \
  IDP_SAML_ENCRYPTION_CERTIFICATE="@auth_idp_encryption_certificate@" \
  LDAP_ENCRYPTION_CERTIFICATE="@auth_ldap_encryption_certificate@" \

  JAVA_OPTS="-Xms384M -Xmx768M" \
  MEMCACHE_ENDPOINT=

# shibboleth configuration files \
COPY idp/* /idp/
COPY newrelic.jar /
COPY newrelic.yml /
# Apache layer
COPY apache /apache/
RUN  mkdir /etc/apache2/certs && \
# configure apache \
  rm -f /etc/apache2/sites-enabled/000-default.conf && \
  a2enmod socache_shmcb ssl status proxy_ajp proxy headers rewrite proxy_http reqtimeout && \
  a2disconf other-vhosts-access-log && \
  sed -i -e 's/Listen 80/Listen ${HTTP_PORT}/' -e 's/Listen 443/Listen ${HTTPS_PORT}/' /etc/apache2/ports.conf && \
  mv /apache/z-defaults.conf /etc/apache2/conf-available/ && a2enconf z-defaults.conf && \

# put error pages in place \
  mv /apache/locking /var/www/html/ && \

# configure idp+regapi virtual host \
  mv /idp/idpproxy.conf /etc/apache2/sites-available/ && \
  a2ensite idpproxy && \

# run apache as its own user \
  mkdir -p /var/run/apache2 /run/lock/apache2 && \
  chown -R www-data:0 /etc/apache2 /var/cache/apache2 /run/lock /var/run/apache2 /var/www/html && \
  chmod -R u=rwX,g=rwX,o= /etc/apache2 /var/cache/apache2 /run/lock /var/run/apache2 /var/www/html/ && \

  rm -rf /apache

RUN mkdir /etc/tomcat8/certs && \
# see also certificates and substitutions in entrypoint script \
  mv /idp/server.xml /etc/tomcat8/ && \
  mv /idp/ifs-registration-service-@version@.war /var/lib/tomcat8/webapps/shibboleth-api.war && \
  mkdir /etc/shibboleth && \
  mv /idp/metadata.xml /etc/shibboleth/ && \
  mv /idp/idp.properties /idp/ldap.properties /idp/*.xml /opt/shibboleth-idp/conf/ && \
  mv /idp/regapi.properties /etc/tomcat8/ && \

# run tomcat/idp as its own user
  mkdir -p /var/run/tomcat8 /tmp/tomcat8-tomcat8-tmp && \
  chown -R www-data:0 /etc/shibboleth /opt/shibboleth-idp /var/run/tomcat8 /tmp/tomcat8-tomcat8-tmp /usr/local/bin \
                      /etc/tomcat8 /var/lib/tomcat8 /usr/share/tomcat8 /var/cache/tomcat8 "$JAVA_HOME"/jre/lib/security/cacerts && \
  chmod -R u=rwX,g=rwX,o= /etc/shibboleth /opt/shibboleth-idp /var/run/tomcat8 /tmp/tomcat8-tomcat8-tmp /usr/local/bin \
                          /etc/tomcat8 /var/lib/tomcat8 /usr/share/tomcat8 /var/cache/tomcat8 "$JAVA_HOME"/jre/lib/security/cacerts && \

  rm -rf /idp

# start and other useful scripts
COPY scripts/* /usr/local/bin/

# custom govuk pages
COPY pages/ /opt/shibboleth-idp/
RUN chown -R www-data:0 /opt/shibboleth-idp /usr/local/bin && \
  chmod -R u=rwX,g=rwX,o= /opt/shibboleth-idp /usr/local/bin

#USER www-data
ENTRYPOINT [ "run-idp.sh" ]
