FROM debian:jessie-slim

ENV DEBIAN_FRONTEND=noninteractive \
  JAVAVER=8 \
  JAVAUPD=144 \
  JAVABLD=01 \
  JAVASIG=090f390dda5b47b9b721c7dfaa008135 \
  IDPVER="3.3.1"

ENV JAVA_HOME=/usr/lib/jvm/java-${JAVAVER}-oracle
ENV JRE_HOME=${JAVA_HOME}/jre

# packages and stuff \
COPY idp/default-jre-headless-dummy_1.0_all.deb /idp/
COPY idp/build.xml /idp/
RUN apt-get update --fix-missing && \

# Oracle JDK \
  apt-get -y install ca-certificates java-common openssl unzip curl apt-transport-https bsdtar && \
  curl --connect-timeout 30 -L -s --retry 3 --cacert /etc/ssl/certs/GeoTrust_Global_CA.pem --header "Cookie: oraclelicense=accept-securebackup-cookie;" \
    "http://download.oracle.com/otn-pub/java/jdk/${JAVAVER}u${JAVAUPD}-b${JAVABLD}/${JAVASIG}/jdk-${JAVAVER}u${JAVAUPD}-linux-x64.tar.gz" | bsdtar -C /tmp -xf - && \
  mkdir -p /usr/lib/jvm && mv /tmp/jdk1.${JAVAVER}.0_${JAVAUPD} ${JAVA_HOME} && \
  curl -jksSLH "Cookie: oraclelicense=accept-securebackup-cookie" -o /tmp/unlimited_jce_policy.zip "http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip" && \
  unzip -jo -d ${JAVA_HOME}/jre/lib/security /tmp/unlimited_jce_policy.zip && \
  find ${JAVA_HOME} -name "*src.zip" -delete && \
  find ${JAVA_HOME}/jre/lib -name "*ws*" -delete && \
  find ${JAVA_HOME}/jre/lib -name "*fx*" -delete && \
  rm ${JAVA_HOME}/jre/lib/deploy.jar && \
  rm -Rf ${JAVA_HOME}/db ${JAVA_HOME}/lib/missioncontrol ${JAVA_HOME}/lib/visualvm \
         ${JAVA_HOME}/man ${JAVA_HOME}/jre/plugin ${JAVA_HOME}/jre/lib/deploy && \
  update-alternatives --install "/usr/bin/java" "java" "${JRE_HOME}/bin/java" 1 && \
  update-alternatives --install "/usr/bin/javac" "javac" "${JAVA_HOME}/bin/javac" 1 && \
  update-alternatives --set java "${JRE_HOME}/bin/java" && \
  update-alternatives --set javac "${JAVA_HOME}/bin/javac" && \
# default-jre-headless-dummy_1.0_all.deb prevents openjdk being installed and saves 100MB or so \
  dpkg -i --force-depends /idp/default-jre-headless-dummy_1.0_all.deb && rm -f /idp/default-jre-headless-dummy_1.0_all.deb && \
# tomcat for IDP. Permission changes here due to https://github.com/docker-library/tomcat/issues/35#issuecomment-238014866 \
  apt-get -y install tomcat8 libtcnative-1 tomcat8-common libtomcat8-java libecj-java ucf && \
  rm -Rf /var/lib/tomcat8/webapps/ROOT/ && \
  chown -R www-data:0 /var/cache/tomcat8 && \
  chmod -R u=rwX,g=rwX,o= /var/cache/tomcat8 && \
# jstl lib for IDP status page
  curl --connect-timeout 30 -s -L --retry 3 -O https://build.shibboleth.net/nexus/service/local/repositories/thirdparty/content/javax/servlet/jstl/1.2/jstl-1.2.jar && \
  mv jstl-1.2.jar /usr/share/tomcat8/lib/ && \
# Shibboleth IDP \
  curl --connect-timeout 30 -s -L --retry 3 http://shibboleth.net/downloads/identity-provider/$IDPVER/shibboleth-identity-provider-$IDPVER.tar.gz | bsdtar -C /root -xf - && \
  sed "s/3\.3\.1/$IDPVER/" /idp/build.xml > /root/shibboleth-identity-provider-$IDPVER/bin/build.xml && rm -f /idp/build.xml && \
  (cd /root/shibboleth-identity-provider-$IDPVER/bin; ./install.sh) && rm -rf /root/shibboleth-identity-provider-$IDPVER && \
# apache. not strictly needed \
  apt-get -y install grep lsof net-tools ldap-utils apache2 && \
  apt-get autoclean && apt-get remove --purge --auto-remove -y unzip && apt-get --purge -y autoremove && rm -rf /var/lib/apt/lists/* && \
  rm -rf /tmp/* /var/tmp/* /idp
