FROM adoptopenjdk/openjdk11
EXPOSE 9443

ENV IDPVER="4.1.0"
ENV JAVA_HOME=/opt/java/openjdk
RUN ls -al $JAVA_HOME/lib/security/cacerts

RUN apt-get update -y
RUN apt-get install wget
RUN apt-get install -y libarchive-tools

# packages and stuff \
COPY idp/build.xml /idp/
COPY idp/idp.installation.properties /idp/
RUN apt-get update --fix-missing && \
  echo "noclobber = off" >> wgetrc && \
  echo "dir_prefix = ." >> wgetrc && \
  echo "verbose = off" >> wgetrc && \
  echo "progress = dot:mega" >> wgetrc && \
  echo "tries = 5" >> wgetrc
# Open JDK \
 RUN  apt-get -y install ca-certificates java-common openssl unzip curl wget apt-transport-https

# tomcat for IDP. Permission changes here due to https://github.com/docker-library/tomcat/issues/35#issuecomment-238014866 \
RUN  apt-get -y install tomcat9 libtcnative-1  libecj-java ucf && \
  rm -Rf /var/lib/tomcat9/webapps/ROOT/ && \
  chown -R www-data:0 /var/cache/tomcat9 && \
  chmod -R u=rwX,g=rwX,o= /var/cache/tomcat9
# jstl lib for IDP status page \
RUN  WGETRC=wgetrc wget --continue https://build.shibboleth.net/nexus/service/local/repositories/thirdparty/content/javax/servlet/jstl/1.2/jstl-1.2.jar && \
  mv jstl-1.2.jar /usr/share/tomcat9/lib/
# Shibboleth IDP \
RUN  WGETRC=wgetrc wget --continue -O- https://shibboleth.net/downloads/identity-provider/archive/$IDPVER/shibboleth-identity-provider-$IDPVER.tar.gz | bsdtar -C /root -xf - && \
  mv /idp/idp.installation.properties /root/shibboleth-identity-provider-$IDPVER/ && \
  rm -f /idp/build.xml && \
  (cd /root/shibboleth-identity-provider-$IDPVER/bin; ./install.sh -Didp.src.dir=/root/shibboleth-identity-provider-$IDPVER/  -Didp.property.file=idp.installation.properties) && rm -rf /root/shibboleth-identity-provider-$IDPVER
# apache. not strictly needed \
RUN  apt-get -y install grep lsof net-tools ldap-utils apache2 && \
  apt-get autoclean && apt-get remove --purge --auto-remove -y unzip wget && apt-get --purge -y autoremove && rm -rf /var/lib/apt/lists/* && \
  rm -rf /tmp/* /var/tmp/* /idp

ENV HTTP_PORT=9080 \
  HTTPS_PORT=9443 \
  IDP_DOMAIN=idp \
  SP_DOMAIN=ifs.local-dev \

  JAVA_KEYSTORE_PASSWORD="@java_keystore_password@" \

  LDAP_URL="ldaps://ldap:8389" \
  LDAP_PORT="8389" \
  LDAP_USESTARTTLS=false \
  LDAP_USESSL=true \
  LDAP_BASEDN="dc=nodomain" \
  LDAP_BINDDN="cn=admin,dc=nodomain" \
  LDAP_BINDDNCREDENTIAL="default" \
  LDAP_RETURNATTRIBUTES="mail,uid" \
  LDAP_PPOLICYDN="cn=PPolicy,ou=Policies" \
  LDAP_PPOLICY="true" \
  LDAP_USERFILTER="(&(mail={user})(!(employeeType=inactive)))" \
  LDAP_AUTHENTICATOR="anonSearchAuthenticator" \
  LDAP_ATTRIBUTE_SEARCHFILTER="(mail=\$resolutionContext.principal)" \
  LDAP_VALIDATEPERIOD="PT20S" \

  IFS_WEB_GOOGLEANALYTICS_TRACKINGID="" \
  BUILD_TIMESTAMP="@build_timestamp@" \
  RESOURCE_DOMAIN="@resource_domain@" \

  IDP_LOG_LEVEL=WARN \

  JAVA_OPTS="-Xms384M -Xmx768M" \
  MEMCACHE_ENDPOINT=

# shibboleth configuration files \
COPY idp/ /idp/
COPY newrelic.jar /
COPY newrelic.yml /
# Apache layer
COPY apache /apache/
RUN  mkdir /etc/apache2/certs && \
# configure apache \
  rm -f /etc/apache2/sites-enabled/000-default.conf && \
  a2enmod socache_shmcb ssl status proxy_ajp proxy headers rewrite proxy_http reqtimeout && \
  a2disconf other-vhosts-access-log && \
  sed -i -e 's/Listen 80/Listen ${HTTP_PORT}/' -e 's/Listen 443/Listen ${HTTPS_PORT}/' /etc/apache2/ports.conf && \
  mv /apache/z-defaults.conf /etc/apache2/conf-available/ && a2enconf z-defaults.conf && \

# put error pages in place \
  mv /apache/locking /var/www/html/ && \

# configure idp virtual host \
  mv /idp/idpproxy.conf /etc/apache2/sites-available/ && \
  a2ensite idpproxy && \

# run apache as its own user \
  mkdir -p /var/run/apache2 /run/lock/apache2 && \
  chown -R www-data:0 /etc/apache2 /var/cache/apache2 /run/lock /var/run/apache2 /var/www/html && \
  chmod -R u=rwX,g=rwX,o= /etc/apache2 /var/cache/apache2 /run/lock /var/run/apache2 /var/www/html/ && \

  rm -rf /apache

RUN mkdir /etc/tomcat9/certs && \
# see also certificates and substitutions in entrypoint script \
  mv /idp/server.xml /etc/tomcat9/ && \
  mv /opt/shibboleth-idp/war/idp.war /var/lib/tomcat9/webapps/ && \
  mkdir /etc/shibboleth && \
  mv /idp/metadata.xml /etc/shibboleth/ && \
  mv /idp/idp.properties /idp/ldap.properties /idp/*.xml /opt/shibboleth-idp/conf/ && \

# run tomcat/idp as its own user
  mkdir -p /var/run/tomcat9 /tmp/tomcat9-tomcat9-tmp && \
  chown -R www-data:0 /etc/shibboleth /opt/shibboleth-idp /var/run/tomcat9 /tmp/tomcat9-tomcat9-tmp /usr/local/bin \
                      /etc/tomcat9 /var/lib/tomcat9 /usr/share/tomcat9 /var/cache/tomcat9 "$JAVA_HOME"/lib/security/cacerts && \
  chmod -R u=rwX,g=rwX,o= /etc/shibboleth /opt/shibboleth-idp /var/run/tomcat9 /tmp/tomcat9-tomcat9-tmp /usr/local/bin \
                          /etc/tomcat9 /var/lib/tomcat9 /usr/share/tomcat9 /var/cache/tomcat9 "$JAVA_HOME"/lib/security/cacerts && \

# Move files required for IDP/SP "extras" process which allows multiple IDP/SPs to be created
  mkdir /etc/shibboleth/extras && \
  mkdir -p /idp/templates && mkdir -p /idp/entities && mkdir -p /idp/certs && \
  mv /idp/templates /etc/shibboleth/extras && \
  mv /idp/entities /etc/shibboleth/extras && \
  mv /idp/certs /etc/shibboleth/extras && \

  rm -rf /idp

# start and other useful scripts
COPY scripts/* /usr/local/bin/

# custom govuk pages
COPY pages/ /opt/shibboleth-idp/
RUN chown -R www-data:0 /opt/shibboleth-idp /usr/local/bin && \
  chmod -R u=rwX,g=rwX,o= /opt/shibboleth-idp /usr/local/bin

#USER www-data
HEALTHCHECK --interval=15s --timeout=8s \
  CMD curl -k -f https://localhost:9443/idp/status || exit 1
ENTRYPOINT [ "run-idp.sh" ]
