package org.innovateuk.ifs.async.executor;

import java.util.concurrent.Executor;

/**
 * Interface for a factory whose task it is to create an Executor for handling our @Async tasks.
 *
 * Since we rely on our task Threads to be decorated via our {@link org.innovateuk.ifs.async.executor.AsyncTaskDecorator}
 * in order to function correctly, any Executor created from an implementation of this interface must call
 * setTaskDecorator(asyncTaskDecorator) after acquiring an instance of {@link org.innovateuk.ifs.async.executor.AsyncTaskDecorator}
 * in order to add the decoration behaviour to any threads generated by the Executor.
 */
public interface AsyncExecutorFactory {

    Executor createAsyncExecutor();
}
