INSERT INTO `competition_type` (`NAME`, `state_aid`, `active`) VALUES ('Sector', 1, '1');

INSERT INTO `competition_template`
(`competition_type_id`)
SELECT id from competition_type WHERE NAME = 'Sector';


 INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority)
VALUES ('GENERAL', 'Project details', 'Please provide Innovate UK with information about your project. These sections are not scored but will provide background to the project.', 'These sections give important background information on the project. They do not need scoring.', null,
(SELECT id FROM competition_template WHERE competition_type_id = (SELECT id FROM competition_type WHERE NAME = 'Sector')), 1);

INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority) VALUES ('GENERAL', 'Application questions', 'These are the 10 questions which will be marked by assessors. Each question is marked out of 10 points.', 'Each question should be given a score out of 10. Written feedback should also be given.', null, (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 2);

INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority) VALUES ('ORGANISATION_FINANCES', 'Finances', 'Each partner is required to submit their own project finances and funding rates. The overall project costs for all partners can be seen in the Finances overview section', 'Each partner is required to submit their own project finances and funding rates. The overall project costs for all partners can be seen in the Finances overview section', null, (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 3);

INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority)
VALUES ('FINANCE', 'Your finances', null, null,
(SELECT id FROM (SELECT * FROM `section_template` where name = 'ORGANISATION_FINANCES' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))) as tempalte),
(SELECT id FROM competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 4);

 INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority)
 VALUES ('GENERAL', 'Finances overview', 'This is the financial overview of all partners in this collaboration. Each partner should submit their organisation\'s finances in the \'your finances\' section. All partners will see this level of detail.', null,
 (SELECT id FROM (SELECT * FROM `section_template` where name = 'ORGANISATION_FINANCES' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))) as tempalte),
 (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 5);

 INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority) VALUES ('GENERAL', 'Labour', null, null,
 (SELECT id FROM (SELECT * FROM `section_template` where name = 'FINANCE' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))) as tempalte),
 (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 6);

 INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority) VALUES ('GENERAL', 'Administration support costs', null, null,
 (SELECT id FROM (SELECT * FROM `section_template` where name = 'FINANCE' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))) as tempalte),
 (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 7);

 INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority) VALUES ('GENERAL', 'Materials', null, null,
 (SELECT id FROM (SELECT * FROM `section_template` where name = 'FINANCE' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))) as tempalte),
 (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 8);

 INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority) VALUES ('GENERAL', 'Capital usage', null, null,
 (SELECT id FROM (SELECT * FROM `section_template` where name = 'FINANCE' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))) as tempalte),
 (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 9);

 INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority) VALUES ('GENERAL', 'Subcontracting costs', null, null,
 (SELECT id FROM (SELECT * FROM `section_template` where name = 'FINANCE' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))) as tempalte),
 (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 10);

 INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority) VALUES ('GENERAL', 'Travel and subsistence', null, null,
 (SELECT id FROM (SELECT * FROM `section_template` where name = 'FINANCE' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))) as tempalte),
 (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 11);

 INSERT INTO `section_template` (section_type, name, description, assessor_guidance_description, parent_section_template_id, competition_template_id, priority) VALUES ('GENERAL', 'Other Costs', null, null,
 (SELECT id FROM (SELECT * FROM `section_template` where name = 'FINANCE' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))) as tempalte),
 (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector')), 12);


-- ---------- question_template

INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (1,'1',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))), 'What is the business opportunity that your project addresses?','Business opportunity',NULL,'Guidance for assessing business opportunity','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>The applicants have a very clear understanding of the business opportunity and the problems that must be overcome to enable successful exploitation. The project is well aligned with these needs.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>The applicants have a good idea of the potential market and opportunities. The needs of the customer are central to the project\'s objectives.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>The business opportunity is plausible but not clearly expressed in terms of customer needs.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>The business opportunity is unrealistic or poorly defined. The customer\'s true needs are not well understood and are not linked to the project\'s objectives.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>There is little or no business drive to the project. The results are not relevant to the target customers or no customer interests are provided.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (2,'2',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'What is the size of the potential market for your project?','Potential market',NULL,'Guidance for assessing market opportunity','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>The market size and dynamics are quantified clearly and to sufficient resolution to be relevant to the project. The market is clearly well understood. The return on investment is clearly stated, quantified and realistic.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>The market size and dynamics are described with some quantification relevant to the project. Market understanding is acceptable and the return on investment is achievable.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>The market size and dynamics are understood but poorly quantified or stated at a level not really relevant for the project. Return on investment is plausible or badly defined.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>The market size is not quantified but there is some understanding. Return on investment is ill defined or unrealistic.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>The market is not well defined or is wrong. No sensible return on investment is provided.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (3,'3',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'How will you exploit and market your project?','Project exploitation',NULL,'Guidance for assessing project exploitation','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>The principle exploitable outputs of the project are identified together with clear and achievable exploitation methods. Dissemination opportunities are also identified and appropriate.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>The main exploitable output of the project is identified and a realistic method defined. Some dissemination is also explained.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>An exploitation method is defined but lacking in detail or is only just feasible. Dissemination is mentioned.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>The exploitation and dissemination methods described are unrealistic or ill-defined.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>The exploitation method is missing or un-feasible and unlikely to succeed.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (4,'4',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'What economic, social and environmental benefits do you expect your project to deliver and when?','Economic benefit',NULL,'Guidance for assessing project benefits','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>Inside and outside benefits are well defined, realistic and of significantly positive economic, environmental or social impact. Routes to exploit these benefits are also provided.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>Some positive outside benefits are defined and are realistic. Methods of addressing these opportunities are described.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>Some positive outside benefits are described but the methods to exploit these are not obvious. Or the project is likely to have a negative impact but some mitigation or a balance against the internal benefits is proposed.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>The project has no outside benefits or is potentially damaging to other stakeholders. No mitigation or exploitation is suggested.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>The project is damaging to other stakeholders with no realistic mitigation or balance described.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (5,'5',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'What technical approach will you use and how will you manage your project?','Technical approach','Describe the areas of work and your objectives. List all resource and management needs. Provide an overview of your technical approach.','Guidance for assessing technical approach','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>The project plan is fully described and complete with milestones and timeframes. The plan is realistic and should meet the objectives of the project.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>The plan is well described and complete. There is a reasonable chance that it will meet the objectives of the project.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>The plan is not completely described or there may be deficiencies in some aspects. More work will be required before the plan can be said to be realistic.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>The plan has serious deficiencies or major missing aspects. The plan has little chance of meeting the objectives of the project.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>The plan is totally unrealistic or fails to meet the objectives of the project.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (6,'6',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'What is innovative about your project?','Innovation','Explain how your project is innovative in both a commercial and technical sense.','Guidance for assessing innovation','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>The project is significantly innovative either commercially or technically and will make a substantial contribution to the field. Solid evidence is presented to substantiate the level of innovation.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>The project will be innovative and relevant to the market. There is high confidence that there is freedom to operate.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>The project is innovative but there is a lack of presented evidence as to the freedom to operate.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>The project lacks sufficient innovation both technically and commercially.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>The project is either not innovative or there is no exploitable route due to previous IP.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (7,'7',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'What are the risks (technical, commercial and environmental) to your project\'s success? What is your risk management strategy?','Risks','We recognise that many of the projects we fund are risky. This is why we need to be sure that you have an adequate plan for managing this risk.','Guidance for assessing risks','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>A thorough risk analysis has been presented across all 3 risk categories. The mitigation and risk management strategies proposed are also appropriate and professional.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>A good risk analysis has been carried out and the management methods and mitigation strategies proposed are realistic.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>Most major risks have been identified but there are some gaps or the mitigation and management is insufficient to properly control the risks.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>The risk analysis is poor or misses major areas of risk. The mitigation and management is poor.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>The risk analysis is superficial with minimal mitigation or management suggested.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (8,'8',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Does your project team have the skills, experience and facilities to deliver this project?','Project team','Describe your capability to develop and exploit this technology. Include details of your team\'s track record in managing research and development projects.','Guidance for assessing team skills','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>The consortium is ideally placed to carry out the project AND exploit the results. The skills are well balanced and the partners likely to form a strong consortium with good knowledge transfer.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>The consortium is strong and contains all the required skills and experience. The consortium is likely to work well.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>The consortium has most of the required skills and experience but there are a few gaps. The consortium will need to work hard to maintain a good working relationship.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>There are significant gaps in the consortium or the formation objectives are unclear. There could be some passengers or the balance of work/commitment is poor.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>The consortium is not capable of either carrying out the project or exploiting the results.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (1,NULL,(SELECT id FROM `section_template` where name = 'Project details' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Application details','Application details','Enter the full title of the project',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (2,NULL,(SELECT id FROM `section_template` where name = 'Project details' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Project summary','Project summary\n','Please provide a short summary of your project. Make sure you include what is innovative about it.',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (3,NULL,(SELECT id FROM `section_template` where name = 'Project details' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Public description','Public description\n','Please provide a brief description of your project. If your application is successful, we will publish this description. This question is mandatory but we will not assess this content as part of your application.',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (4,NULL,(SELECT id FROM `section_template` where name = 'Project details' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'How does your project align with the scope of this competition?','Scope','If your application doesn\'t align with the scope, we will reject it.','Guidance for assessing scope','<p>Your answer should be based upon the following:<table><tr><th scope=\"row\">YES<td><p>The application contains the following:<ul><li>Is the consortia business led?<li>Are there two or more partners to the collaboration?<li>Does it meet the scope of the competition as defined in the competition brief?</ul><tr><th scope=\"row\">NO<td><p>One or more of the above requirements have not been satisfied.</table><p class=extra-margin>Your assessment of the project scope should be based upon the <a href=#>competition brief</a>.');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (5,'9',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'What will your project cost?','Funding','Tell us the total costs of the project and how much funding you need from Innovate UK. Please provide details of your expected project costs along with any supporting information. Please justify any large expenditure in your project.','Guidance for assessing financial commitment','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>The project costs are entirely appropriate. Any mix of research and development types (eg industrial research with some work packages of experimental development) is justified and costed correctly.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>The project costs are appropriate and should be sufficient to successfully complete the project. Any mix of research and development types is justified and costed correctly.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>The project costs and justifications are broadly correct but there are some concerns. Any mix of research and development types is just about acceptable.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>The costs are either too high or too low to carry out the project. Poor justification is provided for any research and development type mix.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>The costs are not appropriate or justified. Any mix of research and development type is not justified.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (6,'10',(SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'How does financial support from Innovate UK and its funding partners add value?','Adding value',' ','Guidance for assessing added value','<p>Your score should be based upon the following:<table><tr><th scope=\"row\" style=\"width: 50px\">9-10<td>The project will significantly increase the industrial partners\' R&D spend during the project and afterwards. The additionality arguments are very strong and believable.<tr><th scope=\"row\" style=\"width: 50px\">7-8<td>The project will increase the industrial partners\' commitment to R&D. The additionality arguments are good and justified.<tr><th scope=\"row\" style=\"width: 50px\">5-6<td>The project will improve the industrial partners\' commitment to R&D. The additionality arguments are just about acceptable.<tr><th scope=\"row\" style=\"width: 50px\">3-4<td>There is not likely to be any improvement to the industrial partner\'s commitment to R&D. The additionality arguments are poor or not sufficiently justified.<tr><th scope=\"row\" style=\"width: 50px\">1-2<td>The work should be funded internally and does not deserve state funding.</table>');
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (7,NULL,(SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Provide the project costs for \'{organisationName}\'',NULL,'Only your organisation can see this level of detail. All members of your organisation can access and edit your finances. We recommend assigning completion of your finances to one member of your team. <a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\" rel=\"external\">Find out which project costs are eligible.</a> ',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (8,NULL,(SELECT id FROM `section_template` where name = 'Labour' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),NULL,NULL,'<p>You may claim the labour costs of all individuals you have working on your project.</p> <p> If your application is awarded funding, you will need to account for all your labour costs as they occur. For example, you should keep timesheets and payroll records. These should show the actual hours worked by individuals and paid by the organisation.</p>',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (9,NULL,(SELECT id FROM `section_template` where name = 'Administration support costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),NULL,NULL,NULL,NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (10,NULL,(SELECT id FROM `section_template` where name = 'Materials' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),NULL,NULL,'<p>You can claim the costs of materials used on your project providing:</p><ul class=\"list-bullet\"><li>they are not already purchased or included in the administration support costs</li><li>they are purchased from third parties</li><li>they won’t have a residual/resale value at the end of your project. If they do you can claim the costs minus this value</li></ul><p><a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\" rel=\"external\">Please refer to our guide to project costs for further information.</a></p>',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (10,NULL,(SELECT id FROM `section_template` where name = 'Capital usage' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),NULL,NULL,'<p>You should provide details of capital equipment and tools you will buy for, or use on, your project.</p>',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (10,NULL,(SELECT id FROM `section_template` where name = 'Subcontracting costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),NULL,NULL,'<p>You may subcontract work if you don’t have the expertise in your consortium. You can also subcontract if it is cheaper than developing your skills in-house.</p>',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (10,NULL,(SELECT id FROM `section_template` where name = 'Travel and subsistence' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),NULL,NULL,'<p>You should include travel and subsistence costs that relate only to this project. </p>',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (10,NULL,(SELECT id FROM `section_template` where name = 'Other Costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),NULL,NULL,'<p>Please tell us if you have applied for or received any other public sector funding for this project. Any other funding received will need to be deducted from the total value of any funding you are claiming for this project.</p>',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (11,NULL,(SELECT id FROM `section_template` where name = 'Labour' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Labour',NULL,NULL,NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (12,NULL,(SELECT id FROM `section_template` where name = 'Administration support costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Overheads',NULL,'<p>You may incur indirect support staff costs linked with your administrative work for the project. To be eligible, these costs should be directly attributable and incremental to the project. Indirect costs associated with commercial activities are not eligible and must not be included. For further information on which costs are eligible please read our <a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\">project costs guidance</a>.</p>',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (13,NULL,(SELECT id FROM `section_template` where name = 'Materials' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Materials',NULL,'Please provide a breakdown of the materials you expect to use during the project',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (14,NULL,(SELECT id FROM `section_template` where name = 'Capital usage' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Capital Usage',NULL,'Please provide a breakdown of the capital items you will buy and/or use for the project.',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (15,NULL,(SELECT id FROM `section_template` where name = 'Subcontracting costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Sub-contracting costs',NULL,'Please provide details of any work that you expect to subcontract for your project.',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (16,NULL,(SELECT id FROM `section_template` where name = 'Travel and subsistence' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Travel and subsistence',NULL,NULL,NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (17,NULL,(SELECT id FROM `section_template` where name = 'Other Costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Other costs',NULL,'Please note that legal or project audit and accountancy fees are not eligible and should not be included as an \'other cost’. Patent filing costs of NEW IP relating to the project are limited to £7,500 for SME applicants only.  Please provide estimates of other costs that do not fit within any other cost headings.',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (18,NULL,(SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Other funding',NULL,'Please tell us if you have ever applied for or received any other public sector funding for this project. You should also include details of any offers of funding you\'ve received.',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (19,NULL,(SELECT id FROM `section_template` where name = 'Finances overview' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'FINANCE_SUMMARY_INDICATOR_STRING',NULL,NULL,NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (20,NULL,(SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Funding level',NULL,'Please enter the funding level that you would like to apply for in this application',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (21,NULL,(SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Organisation Size',NULL,'To determine the level of funding you are eligible to receive please provide your business sizing using the <a href=\"http://ec.europa.eu/growth/smes/business-friendly-environment/sme-definition/index_en.htm\" target=\"_blank\" rel=\"external\">EU Definition</a> for guidance.',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (22,NULL,(SELECT id FROM `section_template` where name = 'Finances overview' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),NULL,NULL,'<h2 class=\"heading-medium\">Funding rules for this competition</h2><p>We will fund projects between &pound;500,000 and &pound;1.5 million. We may consider projects with costs outside of this range. We expect projects to last between 12 and 36 months.</p><p>Innovate UK\'s aim is to optimise the level of funding businesses receive. We also recognise the importance of research organisations\' contribution to R&amp;D projects. Therefore we require the following levels of participation:</p><ul class=\"list-bullet\"> <li>at least 70% of the total eligible project costs are incurred by commercial organisations and</li> <li>a maximum of 30% of total eligible project costs are available to research participants. Where there is more than one research participant, this maximum will be shared between them.</li></ul>',NULL,NULL);
INSERT INTO `question_template` (`priority`,`question_number`,`section_template_id`,`name`,`short_name`,`description`,`assessor_guidance_question`,`assessor_guidance_answer`) VALUES (23,NULL,(SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))),'Upload a pdf copy of the Je-S output confirming a status of \'With Council\'',NULL,NULL,NULL,NULL);
UPDATE `question_template` SET `short_name`='Je-s Output' WHERE id = LAST_INSERT_ID();

-- ---------- form input tempates, question tempate mapping to form input template and form input validators
-- 1
INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the business opportunity section?','<p>You should describe:</p><ul class=\"list-bullet\">         <li>the business opportunity you have identified and how you plan to take advantage of it</li><li>the customer needs you have identified and how your project will meet them</li><li>the challenges you expect to face and how you will overcome them</li></ul>','1. What is the business opportunity that your project addresses?',1);
INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
VALUES ((SELECT id from `question_template` where priority = 1 and question_number = '1'
and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
, LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

-- 2
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the market opportunity section?','<p>Describe the size of the potential market for your project, including:</p><ul class=\"list-bullet\">         <li>details of your target market, for instance, how competitive and profitable it is</li><li>the current size of the market, with actual and predicted growth rates</li><li>the market share you expect to achieve and the reasons for this estimate</li><li>the wider economic value you expect your project to add to the UK and/or the EEA (European Economic Area)</li></ul><p>Tell us what return on investment you expect your project to achieve. You should base this estimate on relevant industry data and tell us how you have calculated this.</p><p>If you are targeting an undeveloped market, you should also:</p><ul class=\"list-bullet\">         <li>describe how you plan to access this market</li><li>estimate its potential size</li><li>explain how you will explore its potential</li></ul>','2. What is the size of the potential market for your project?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 2 and question_number = '2'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

-- 3
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the project exploitation section?','<p>Describe the potential outputs of the project, such as:</p><ul class=\"list-bullet\">         <li>products or services</li><li>processes</li><li>applications</li></ul><p>Describe how you will exploit these outputs, such as:</p><ul class=\"list-bullet\">         <li>the route to market</li><li>protection of intellectual property rights</li><li>reconfiguration of your organisation\'s value system</li><li>changes to business models and processes</li><li>any other methods of exploitation and protection</li></ul> ','3. How will you exploit and market your project?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 3 and question_number = '3'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

-- 4
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the benefits section?','<p>Describe all the benefits you expect your project to deliver, including:</p><p><strong>Economic</strong> : this is the real impact the project will have on its economic environment. This is not traditional corporate accounting profit and can include cost avoidance. You should identify and quantify any expected benefits to:</p><ul class=\"list-bullet\"><li>users (intermediaries and end users)</li><li>suppliers</li><li>broader industrial markets</li><li>the UK economy</li></ul><p><strong>Social</strong> : quantify any expected social impacts either positive or negative on, for example:</p><ul class=\"list-bullet\"><li>quality of life</li><li>social inclusion/exclusion</li><li>education</li><li>public empowerment</li><li>health and safety</li><li>regulation</li><li>diversity</li><li>government priorities</li></ul><p><strong>Environmental</strong> : show how your project will benefit or have a low impact on the environment. For example, this could include:<p><ul class=\"list-bullet\"><li>careful management of energy consumption</li><li>reductions in carbon emissions</li><li>reducing manufacturing and materials waste</li><li>rendering waste less toxic before disposing of it in a safe and legal manner</li><li>re-manufacturing (cradle to cradle)</li></ul>','4. What economic, social and environmental benefits do you expect your project to deliver and when?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 4 and question_number = '4'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

-- 5
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the technical approach section?','<p>You should:</p><ul class=\"list-bullet\">         <li>describe your technical approach including the main objectives of the work</li><li>explain how and why your approach is appropriate</li><li>tell us how you will make sure that the innovative steps in your project are achievable</li><li>describe rival technologies and alternative R&D strategies</li><li>explain why your proposed approach will offer a better outcome</li></ul>','5. What technical approach will you use and how will you manage your project?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 5 and question_number = '5'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

-- 6
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the project innovation section?','<p>You should show how your project will:</p><ul class=\"list-bullet\">         <li>push boundaries beyond current leading-edge science and technology</li><li>apply existing technologies in new areas</li></ul><p>Explain the novelty of the research in an industrial and/or academic context.</p><p>You should provide evidence that your proposed work is innovative. This could include patent search results, competitor analyses or literature surveys. If relevant, you should also outline your own intellectual property rights.</p>','6. What is innovative about your project?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 6 and question_number = '6'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

-- 7
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the project risks section?','<p>Please describe your plans for limiting and managing risk. You need to:</p><ul class=\"list-bullet\">         <li>identify the project\'s main risks and uncertainties</li><li>detail specific technical, commercial, managerial and environmental risks</li><li>list any other uncertainties such as ethical issues associated with the project</li><li>provide a detailed risk analysis</li><li>rate the main risks as high, medium or low</li><li>show how you\'ll limit the main risks</li><li>identify the project management resources you\'ll use to minimise operational risk</li><li>include arrangements for managing the project team and its partners</li></ul>','7. What are the risks (technical, commercial and environmental) to your project\'s success? What is your risk management strategy?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 7 and question_number = '7'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

-- 8
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the project skills section?','<p>You should show your project team:</p><ul class=\"list-bullet\"><li>has the right mix of skills and experience to complete the project</li><li>has clear objectives</li><li>would have been formed even without Innovate UK investment</li></ul><p>If you are part of a consortium, describe the benefits of the collaboration, for example, increased knowledge transfer.</p>','8. Does your project team have the skills, experience and facilities to deliver this project?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 8 and question_number = '8'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

-- 9
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,5,NULL,NULL,'Application details',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 1 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Project details' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 10
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the project summary?','<p>We will not score this summary, but it will give the assessors a useful introduction to your project. It should provide a clear overview of the whole project, including:</p> <ul class=\"list-bullet\">         <li>your vision for the project</li><li>key objectives</li><li>main areas of focus</li><li>details of how it is innovative</li></ul>','Project summary',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 2 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Project details' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

-- 11
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the project public description?','<p>Innovate UK publishes information about projects we have funded. This is in line with government practice on openness and transparency of public-funded activities.</p><p>Describe your project in a way that will be easy for a non-specialist to understand. Don\'t include any information that is confidential, for example, intellectual property or patent details.</p> ','Public description',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 3 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Project details' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

 -- 12
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the project scope?','<p>It is important that you read the following guidance.</p><p>To show how your project aligns with the scope of this competition, you need to:</p><ul class=\"list-bullet\">         <li>read the competition brief in full</li><li>understand the background, challenge and scope of the competition</li><li>address the research objectives in your application</li><li>match your project\'s objectives and activities to these</li></ul> <p>Once you have submitted your application, you should not change this section unless:</p><ul class=\"list-bullet\">         <li>we ask you to provide more information</li><li>we ask you to make it clearer</li></ul> ','How does your project align with the scope of this competition?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 3 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Project details' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

 -- 13
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,4,'What should I include in the appendix?','<p>You may include an appendix of additional information to support the technical approach the project will undertake.</p><p>You may include, for example, a Gantt chart or project management structure.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 6 sides of A4. Longer appendices will only have the first 6 pages assessed</li><li>be less than 1mb in size</li></ul>','Appendix',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 5 and question_number = '5'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 14
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the project cost section?','<p>You must:</p><ul class=\"list-bullet\"><li>show how your budget is realistic for the scale and complexity of the project</li><li>make sure the funding you need from Innovate UK is within the limit set by this competition</li><li>justify any significant costs in the project, such as subcontractors</li><li>show how much funding there will be from other sources</li><li>provide a realistic budget breakdown</li><li>describe and justify individual work packages</li></ul><p>Find out which <a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\">project costs are eligible.</a></p><p>If your project spans more than one type of research category, you must break down the costs as separate \'work packages\'. For example, industrial research or experimental development. </p><p>You can find more information in the  <a href=\"https://www.gov.uk/guidance/innovate-uk-funding-general-guidance-for-applicants#funding-rules\">funding rules section</a> of this website.</p>','9. What will your project cost?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 5 and question_number = '9'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);


 -- 15
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,2,'What should I include in the financial support from Innovate UK section?','Justify why you\'re unable to fund the project yourself from commercial resources. Explain the difference this funding will make to your project. For example, will it lower the risk for you or speed up the process of getting your product to market? Tell us why this will benefit the UK.','10. How does financial support from Innovate UK and its funding partners add value?',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 6 and question_number = '10'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 2);
 INSERT INTO `form_input_template_form_validator` (`form_input_template_id`, `form_validator_id`) VALUES ((SELECT MAX(id) from `form_input_template`), 3);

 -- 16
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,4,'What should I include in the appendix?','<p>You may include an appendix of additional information to support your response to this question. This appendix may include graphics describing the innovation or the nature of the problem. You may want to include evidence of freedom to operate, patent searches or competitor analysis as supporting information.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 5 sides of A4. Longer appendices will only have the first 5 pages assessed</li><li>be less than 1mb in size</li></ul>','Appendix',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 6 and question_number = '6'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

 -- 17
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,4,'What should I include in the appendix?','<p>You may include an appendix of additional information to provide details of the specific expertise and track record of each project partner and each subcontractor. Academic collaborators may refer to their research standing.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>include up to half an A4 page per partner describing the skills and experience of the main people who will be working on the project</li><li>be less than 1mb in size</li></ul>','Appendix',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 8 and question_number = '8'
 and section_template_id = (SELECT id FROM `section_template` where name = 'Application questions' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

 -- 18
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,15,'','',NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 7 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

 -- 19
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,6,'Labour costs guidance','<p>You can include the following labour costs, based upon your PAYE records:</p><ul class=\"list-bullet\"><li>gross salary</li><li>National Insurance</li><li>company pension contribution</li><li>life insurance</li><li>other non-discretionary package costs.</li></ul><p>You can\'t include:</p><ul class=\"list-bullet\"><li>discretionary bonuses</li><li>performance related payments of any kind</li></ul><p>You may include the total number of working days for staff but do not include:</p><ul class=\"list-bullet\"><li>sick days</li><li>waiting time</li><li>training days</li><li>non-productive time</li></ul><p>Enter the total number of working days in the year. List the total days worked by all categories of staff on your project. Describe their role.</p><p>We will review the total amount of time and cost of labour before we approve your application. The terms and conditions of the grant include compliance with these points.</p>',NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 8 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Labour' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 20
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,6,NULL,NULL,NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 9 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Administration support costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 21
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,6,'Materials costs guidance','<p>Materials supplied by associated companies or project partners should be charged at cost.</p><p>Software that you have purchased specifically for use during your project may be included. If you already own the software then only additional costs which are incurred and paid during your project, will be eligible. For example, installation, training or customisation.</p><p>Material costs must be itemised to justify that they are eligible.</p>',NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 10 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Materials' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 22
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,6,'Capital usage guidance','<p>You will need to calculate a ‘usage’ value for each item. You can do this by deducting its expected value from its original price at the end of your project. If you owned the equipment before the project started then you should use its Net Present Value.</p><p>This value is then multiplied by the amount, in percentages, that is used during the project. This final value represents the eligible cost to your project.</p>',NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 10 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Capital usage' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 23
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,6,'Subcontracting costs guidance','<p>Subcontracting costs relate to work carried out by third party organisations. These organisations are not part of your project or collaboration.</p><p>Subcontracting is eligible providing it’s justified as to why the work cannot be performed by a project partner.</p><p>Where possible you should select a UK based contractor. You should name the subcontractor (where known) and describe what they will be doing. You should also state where the work will be undertaken. We will look at the size of this contribution when assessing your eligibility and level of support.</p>',NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 10 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Subcontracting costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
, LAST_INSERT_ID());

-- 24
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,6,NULL,NULL,NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 10 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Travel and subsistence' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 25
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,6,'Other costs guidance','<p>Examples of other costs include:</p><p><strong>Training costs:</strong> these costs are eligible for support if they relate to your project. We may support management training for your project but will not support ongoing training.</p><p><strong>Preparation of technical reports:</strong> if, for example, the main aim of your project is standard support or technology transfer. You should show how this is more than you would produce through good project management.</p><p><strong>Market assessment:</strong> we may support market assessments studies. The study will need to help us understand how your project is a good match for your target market. It could also be eligible if it helps commercialise your product.</p><p><strong>Licensing in new technologies:</strong> if new technology makes up a large part of your project, we will expect you to develop that technology. For instance, if the value of the technology is more than &pound;100,000.</p><p><strong>Patent filing costs for NEW IP generated by your project:</strong> these are eligible for SMEs up to a limit of &pound;7,500 per partner. You should not include legal costs relating to the filing or trademark related expenditure.</p><p>Regulatory compliance costs are eligible if necessary to carry out your project.</p>',NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 10 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Other Costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 26
  INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,8,NULL,NULL,'Labour',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 11 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Labour' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 27
  INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,9,NULL,NULL,'Overheads',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 12 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Administration support costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 28
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,10,NULL,NULL,'Materials',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 13 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Materials' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 29
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,11,NULL,NULL,'Capital Usage',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 14 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Capital usage' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 30
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,12,NULL,NULL,'Sub-contracting costs',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 15 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Subcontracting costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 31
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,13,NULL,NULL,'Travel and subsistence',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 16 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Travel and subsistence' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 32
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,14,NULL,NULL,'Other costs',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 17 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Other Costs' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 33
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,17,'What should I include in the other public funding section?','<p>You must provide details of other public funding that you are currently applying for (or have already applied for) in relation to this project. You do not need to include completed grants that were used to reach this point in the development process. This information is important as other public sector support counts as part of the funding you can receive for your project.</p>','Other funding',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 18 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 34
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,16,NULL,NULL,NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 19 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Finances overview' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 35
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,7,'What funding level should I enter?','<p>For a business or academic organisation, you can apply for any funding percentage between 0% and the maximum allowable for your organisation size. For other organisation types, you can apply for any funding percentage between 0% and 100%. The amount you apply for must reflect other funding you may have received. It must also be within participation levels which you can review on the Finances Overview page.</p>','Please enter the grant % you wish to claim for this project',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 20 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 36
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,19,NULL,NULL,'Organisation Size',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 21 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 37
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,6,NULL,NULL,NULL,1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 22 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Finances overview' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());

-- 38
 INSERT INTO `form_input_template` (`priority`,`form_input_type_id`,`guidance_question`,`guidance_answer`,`description`,`included_in_application_summary`) VALUES (0,20,'How do I create my Je-S output?','<p>You should include only supporting information in the appendix. You shouldn’t use it to provide your responses to the question.</p><p>Guidance for this section needs to be created</p>','Upload a pdf copy of the Je-S output form once you have a status of \'With Council\'.',1);
 INSERT INTO `question_template_form_input_template` (`question_template_id`, `form_input_template_id`)
 VALUES ((SELECT id from `question_template` where priority = 23 and question_number IS NULL
 and section_template_id = (SELECT id FROM `section_template` where name = 'Your finances' and competition_template_id = (SELECT id from competition_template where competition_type_id = (SELECT id from competition_type WHERE NAME = 'Sector'))))
 , LAST_INSERT_ID());


