-- Updating each name by selecting it by it's old name
--UPDATE category SET name='Emerging and enabling' WHERE name='Emerging and enabling technologies';
--UPDATE category SET name='Digital industries' WHERE name='Digital Industries';
--UPDATE category SET name='Satellite applications' WHERE name='Satellite Applications';
--UPDATE category SET name='Emerging technology' WHERE name='Emerging Technology';
--UPDATE category SET name='Robotics and autonomous systems' WHERE name='Robotics and Autonomous Systems';
--UPDATE category SET name='Electronics, sensors and photonics' WHERE name='Electronics, Sensors & Photonics';
--UPDATE category SET name='Creative industries' WHERE name='Creative Industries';
--UPDATE category SET name='Digital technology' WHERE name='Digital Technology';