*** Settings ***
Library           Selenium2Library
Library           XvfbRobot
Library           IFS_Selenium_Extension
Library           ../libs/ImapLibrary.py
Library           Collections
Library           ExcelLibrary
Library           FtpLibrary
Library           OperatingSystem
Library           ../libs/XlsxLibrary.py
Library           ../libs/IfsLibrary.py
Library           DatabaseLibrary
Library           robot.libraries.DateTime
Library           String
Library           CsvLibrary
Library           ../libs/Debugging.py
Library           ../libs/WaitUntilLibrary.py
Library           ../libs/EmailExtensionLibrary.py
Library           PdfLibrary