INSERT INTO activity_state (activity_type, state) VALUES
('PROJECT_SETUP_SPEND_PROFILE', 'PENDING'),
('PROJECT_SETUP_SPEND_PROFILE', 'GENERATED'),
('PROJECT_SETUP_SPEND_PROFILE', 'SUBMITTED'),
('PROJECT_SETUP_SPEND_PROFILE', 'ACCEPTED'),
('PROJECT_SETUP_SPEND_PROFILE', 'REJECTED');
