-- IFS-2647 rename in_assessment_panel flag
ALTER TABLE activity_state
MODIFY COLUMN
  activity_type TEXT NOT NULL;

UPDATE activity_state
  SET activity_type='ASSESSMENT_REVIEW'
  WHERE activity_type='ASSESSMENT_PANEL_APPLICATION_INVITE';

ALTER TABLE activity_state
  MODIFY COLUMN
  activity_type enum(
  'APPLICATION_ASSESSMENT','PROJECT_SETUP','PROJECT_SETUP_COMPANIES_HOUSE_DETAILS','PROJECT_SETUP_PROJECT_DETAILS',
  'PROJECT_SETUP_MONITORING_OFFICER_ASSIGNMENT','PROJECT_SETUP_BANK_DETAILS','PROJECT_SETUP_FINANCE_CHECKS',
  'PROJECT_SETUP_VIABILITY','PROJECT_SETUP_ELIGIBILITY','PROJECT_SETUP_SPEND_PROFILE',
  'PROJECT_SETUP_GRANT_OFFER_LETTER','APPLICATION','ASSESSMENT_REVIEW',
  'ASSESSMENT_INTERVIEW_PANEL','ASSESSMENT_INTERVIEW'
) NOT NULL;


INSERT INTO activity_state (activity_type, state) VALUES
('ASSESSMENT_INTERVIEW_PANEL', 'CREATED'),
('ASSESSMENT_INTERVIEW_PANEL', 'PENDING'),
('ASSESSMENT_INTERVIEW_PANEL', 'SUBMITTED');
