ALTER TABLE activity_state
MODIFY COLUMN
  activity_type enum(
    'APPLICATION_ASSESSMENT','PROJECT_SETUP','PROJECT_SETUP_COMPANIES_HOUSE_DETAILS','PROJECT_SETUP_PROJECT_DETAILS',
    'PROJECT_SETUP_MONITORING_OFFICER_ASSIGNMENT','PROJECT_SETUP_BANK_DETAILS','PROJECT_SETUP_FINANCE_CHECKS',
    'PROJECT_SETUP_VIABILITY','PROJECT_SETUP_ELIGIBILITY','PROJECT_SETUP_SPEND_PROFILE',
    'PROJECT_SETUP_GRANT_OFFER_LETTER','APPLICATION','ASSESSMENT_PANEL_APPLICATION_INVITE',
    'ASSESSMENT_INTERVIEW_PANEL'
) NOT NULL;

INSERT INTO activity_state (activity_type, state) VALUES
('ASSESSMENT_INTERVIEW_PANEL', 'CREATED'),
('ASSESSMENT_INTERVIEW_PANEL', 'PENDING'),
('ASSESSMENT_INTERVIEW_PANEL', 'SUBMITTED');
