-- IFS-3950 - adding missing constraints to the form_input_response table to improve data integrity
--IFS-4304: There are issues with adding NOT NULL constraints to application id. As a result, the SQL statements in this file,
--have been removed (as this has not yet been run on production)