-- IFS-5508 Change funder from string value to enum
ALTER TABLE competition_funder
MODIFY COLUMN funder
ENUM('ADVANCED_PROPULSION_CENTRE_APC',
  'AEROSPACE_TECHNOLOGY_INSTITUTE_ATI',
  'CENTRE_FOR_CONNECTED_AND_AUTONOMOUS_VEHICLES_CCAV',
  'DEPARTMENT_FOR_BUSINESS_ENERGY_AND_INDUSTRIAL_STRATEGY_BEIS',
  'DEPARTMENT_FOR_DIGITAL_CULTURE_MEDIA_AND_SPORT_DCMS',
  'EUROPEAN_EUREKA_EUROSTARS_AND_OTHER_EU',
  'INDUSTRIAL_STRATEGY_CHALLENGE_FUND_ISCF',
  'INNOVATE_UK_CORE_BUDGET',
  'INTEGRATED_DELIVERY_PLATFORM_IDP',
  'INTERNATIONAL',
  'OFFICE_FOR_LIFE_SCIENCES_OLS',
  'SMALL_BUSINESS_RESEARCH_INITIATIVE_SBRI',
  'SMART_OPEN',
  'OTHER_DELIVERY_PARTNERS',
  'OTHER_STAKEHOLDERS');