-- IFS-5820

CREATE TABLE activity_log (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  application_id bigint(20) NOT NULL,
  type enum('APPLICATION_SUBMITTED',
            'PROJECT_DETAILS_COMPLETE',
            'DOCUMENT_UPLOADED',
            'DOCUMENT_APPROVED',
            'MONITORING_OFFICER_ASSIGNED',
            'BANK_DETAILS_SUBMITTED',
            'BANK_DETAILS_APPROVED',
            'VIABILITY_APPROVED',
            'ELIGIBILITY_APPROVED',
            'FINANCE_QUERY',
            'SPEND_PROFILE_GENERATED',
            'SPEND_PROFILE_EDIT',
            'SPEND_PROFILE_COMPLETE',
            'SPEND_PROFILE_REVIEWED',
            'SPEND_PROFILE_SENT',
            'SPEND_PROFILE_APPROVED',
            'FINANCE_REVIEWER_ADDED',
            'GRANT_OFFER_LETTER_UPLOADED',
            'GRANT_OFFER_LETTER_PUBLISHED',
            'GRANT_OFFER_LETTER_SIGNED',
            'GRANT_OFFER_LETTER_APPROVED') NOT NULL,
  created_on DATETIME NOT NULL,
  created_by bigint(20) NOT NULL,
  organisation_id bigint(20),
  thread_id bigint(20),
  document_config_id bigint(20),
  CONSTRAINT fk_activity_log_application_id FOREIGN KEY (application_id) REFERENCES application(id),
  CONSTRAINT fk_activity_log_user_id FOREIGN KEY (created_by) REFERENCES user(id),
  CONSTRAINT fk_activity_log_organisation_id FOREIGN KEY (organisation_id) REFERENCES organisation(id),
  CONSTRAINT fk_activity_log_thread_id FOREIGN KEY (thread_id) REFERENCES thread(id),
  CONSTRAINT fk_activity_log_document_config_id FOREIGN KEY (document_config_id) REFERENCES document_config(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
