ALTER TABLE competition ADD COLUMN competition_assessment_config_id BIGINT(20) DEFAULT NULL;
ALTER TABLE competition ADD UNIQUE KEY competition_assessment_config_id_UNIQUE (competition_assessment_config_id);
ALTER TABLE competition ADD CONSTRAINT fk_competition_assessment_config FOREIGN KEY(competition_assessment_config_id) REFERENCES competition_assessment_config(id);