ALTER TABLE finance_row MODIFY COLUMN type ENUM (
    'LABOUR',
    'OVERHEADS',
    'PROCUREMENT_OVERHEADS',
    'MATERIALS',
    'CAPITAL_USAGE',
    'SUBCONTRACTING_COSTS',
    'TRAVEL',
    'OTHER_COSTS',
    'FINANCE',
    'OTHER_FUNDING',
    'YOUR_FINANCE',
    'VAT',
    'GRANT_CLAIM_AMOUNT',
    'PREVIOUS_FUNDING'
);

ALTER TABLE competition_finance_row_types MODIFY COLUMN finance_row_type enum (
    'LABOUR',
    'OVERHEADS',
    'PROCUREMENT_OVERHEADS',
    'MATERIALS',
    'CAPITAL_USAGE',
    'SUBCONTRACTING_COSTS',
    'TRAVEL',
    'OTHER_COSTS',
    'FINANCE',
    'OTHER_FUNDING',
    'YOUR_FINANCE',
    'VAT',
    'GRANT_CLAIM_AMOUNT',
    'PREVIOUS_FUNDING'
) NOT NULL;

