CREATE TABLE simple_organisation (
  id bigint(20) PRIMARY KEY AUTO_INCREMENT,
  name varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE profile ADD COLUMN simple_organisation_id BIGINT(20);
ALTER TABLE profile ADD CONSTRAINT fk_profile_simple_organisation FOREIGN KEY (simple_organisation_id) REFERENCES simple_organisation(id);

ALTER TABLE activity_state MODIFY COLUMN activity_type enum('APPLICATION_ASSESSMENT','PROJECT_SETUP','PROJECT_SETUP_COMPANIES_HOUSE_DETAILS',
'PROJECT_SETUP_PROJECT_DETAILS','PROJECT_SETUP_MONITORING_OFFICER_ASSIGNMENT','PROJECT_SETUP_BANK_DETAILS','PROJECT_SETUP_FINANCE_CHECKS',
'PROJECT_SETUP_VIABILITY','PROJECT_SETUP_ELIGIBILITY','PROJECT_SETUP_SPEND_PROFILE','PROJECT_SETUP_GRANT_OFFER_LETTER','APPLICATION',
'ASSESSMENT_REVIEW','ASSESSMENT_INTERVIEW_PANEL','ASSESSMENT_INTERVIEW', 'COFUNDER_ASSIGNMENT');
