ALTER TABLE competition_user MODIFY COLUMN type ENUM('ASSESSOR', 'INNOVATION_LEAD', 'STAKEHOLDER', 'INTERVIEW_PARTICIPANT', 'REVIEW_PARTICIPANT', 'EXTERNAL_FINANCE') NOT NULL;


ALTER TABLE competition_user MODIFY COLUMN competition_role ENUM('ASSESSOR', 'INNOVATION_LEAD', 'PANEL_ASSESSOR', 'INTERVIEW_ASSESSOR', 'STAKEHOLDER', 'EXTERNAL_FINANCE') NOT NULL;