ALTER TABLE application ADD COLUMN application_external_application_config_id BIGINT(20) DEFAULT NULL;
ALTER TABLE application ADD UNIQUE KEY application_external_application_config_id (application_external_application_config_id);
ALTER TABLE application ADD CONSTRAINT fk_application_external_application_config FOREIGN KEY(application_external_application_config_id) REFERENCES application_external_config(id);
