CREATE TABLE application_heukar_location
(
    id             BIGINT(20) NOT NULL AUTO_INCREMENT,
    application_id BIGINT(20),
    location       ENUM( 'ENGLAND',
        'NORTH_EAST',
        'NORTH_WEST',
        'YORKSHIRE_AND_HUMBER',
        'EAST_MIDLANDS',
        'WEST_MIDLANDS',
        'EAST_OF_ENGLAND',
        'GREATER_LONDON',
        'SOUTH_EAST',
        'SOUTH_WEST',
        'WALES',
        'SCOTLAND',
        'NORTHERN_IRELAND',
        'BRITISH_OVERSEAS_TERRITORY',
        'ANGUILA',
        'BERMUDA',
        'BRITISH_ANTARCTIC_TERRITORY',
        'BRITISH_INDIAN_OCEAN_TERRITORY',
        'BRITISH_VIRGIN_ISLANDS',
        'CAYMAN_ISLANDS',
        'SOVEREIGN_BASE_AREAS_OF_AKROTIRI_AND_DHEKELIA',
        'FALKLAND_ISLANDS',
        'GIBRALTAR',
        'MONTSERRAT',
        'PITCAIRN_ISLANDS',
        'SAINT_HELENA',
        'SOUTH_GEORGIA',
        'TURKS_AND_CAICOS_ISLANDS',
        'CROWN_DEPENDENCY',
        'JERSEY',
        'GUERNSEY',
        'ISLE_OF_MAN'
        ),
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;