ALTER TABLE activity_state
    MODIFY COLUMN state
    ENUM('CREATED','PENDING','REJECTED','ACCEPTED','WITHDRAWN','OPEN','READY_TO_SUBMIT','SUBMITTED','VERIFIED','NOT_VERIFIED','ASSIGNED','NOT_ASSIGNED')
        NOT NULL;

INSERT INTO activity_state (activity_type, state) VALUES
            ('APPLICATION_ASSESSMENT', 'CREATED'),
            ('APPLICATION_ASSESSMENT', 'WITHDRAWN')