-- new activity_state type 'ASSESSMENT_PANEL_APPLICATION_INVITE', and state 'CONFLICT_OF_INTEREST'
ALTER TABLE activity_state
    MODIFY COLUMN activity_type
        ENUM('APPLICATION_ASSESSMENT',
        'PROJECT_SETUP',
        'PROJECT_SETUP_COMPANIES_HOUSE_DETAILS',
        'PROJECT_SETUP_PROJECT_DETAILS',
        'PROJECT_SETUP_MONITORING_OFFICER_ASSIGNMENT',
        'PROJECT_SETUP_BANK_DETAILS',
        'PROJECT_SETUP_FINANCE_CHECKS',
        'PROJECT_SETUP_VIABILITY',
        'PROJECT_SETUP_ELIGIBILITY',
        'PROJECT_SETUP_SPEND_PROFILE',
        'PROJECT_SETUP_GRANT_OFFER_LETTER',
        'APPLICATION',
        'ASSESSMENT_PANEL_APPLICATION_INVITE')
        NOT NULL,
    MODIFY COLUMN state
        ENUM('CREATED',
        'PENDING',
        'REJECTED',
        'ACCEPTED',
        'WITHDRAWN',
        'OPEN',
        'READY_TO_SUBMIT',
        'SUBMITTED',
        'VERIFIED',
        'NOT_VERIFIED',
        'ASSIGNED',
        'NOT_ASSIGNED',
        'NOT_APPLICABLE',
        'NOT_APPLICABLE_INFORMED',
        'CONFLICT_OF_INTEREST')
        NOT NULL;


-- assessment panel application invite states
INSERT INTO activity_state (activity_type, state)
VALUES
  ('ASSESSMENT_PANEL_APPLICATION_INVITE', 'CREATED'),
  ('ASSESSMENT_PANEL_APPLICATION_INVITE', 'PENDING'),
  ('ASSESSMENT_PANEL_APPLICATION_INVITE', 'REJECTED'),
  ('ASSESSMENT_PANEL_APPLICATION_INVITE', 'ACCEPTED'),
  ('ASSESSMENT_PANEL_APPLICATION_INVITE', 'CONFLICT_OF_INTEREST');
