package org.innovateuk.ifs.activitylog.resource;

public enum ActivityType {

    APPLICATION_SUBMITTED,
    APPLICATION_INTO_PROJECT_SETUP, //TODO Test
    PROJECT_DETAILS_COMPLETE,
    PROJECT_MANAGER_NOMINATED,
    FINANCE_CONTACT_NOMINATED,
    DOCUMENT_UPLOADED,
    DOCUMENT_APPROVED,
    MONITORING_OFFICER_ASSIGNED,
    BANK_DETAILS_SUBMITTED,
    BANK_DETAILS_APPROVED,
    VIABILITY_APPROVED,
    ELIGIBILITY_APPROVED,
    FINANCE_QUERY,
    FINANCE_QUERY_RESPONDED, //TODO Test
    SPEND_PROFILE_GENERATED,
    SPEND_PROFILE_EDIT,
    SPEND_PROFILE_COMPLETE,
    SPEND_PROFILE_SENT,
    SPEND_PROFILE_APPROVED,
    FINANCE_REVIEWER_ADDED,
    GRANT_OFFER_LETTER_UPLOADED,
    GRANT_OFFER_LETTER_PUBLISHED,
    GRANT_OFFER_LETTER_SIGNED,
    GRANT_OFFER_LETTER_APPROVED,
    MANAGED_OFFLINE, //TODO
    COMPLETE_OFFLINE, //TODO
    WITHDRAWN, //TODO
    ON_HOLD, //TODO
    RESUMED_FROM_ON_HOLD //TODO

}
