FROM davidcaste/alpine-java-unlimited-jce:jdk8
MAINTAINER David Soff <dsoff@worth.systems>
RUN apk --update add curl
EXPOSE 8009
EXPOSE 8000
EXPOSE 8080
ENV JAVA_OPTS -Xmx300m
ENV JMX_OPTS -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
VOLUME /tmp

ADD @app_name@-@version@.jar app.jar
ADD coscale-monitoring.sh /root/coscale-monitoring.sh

ENTRYPOINT exec java $JAVA_OPTS $JMX_OPTS -jar app.jar