-- EU grant funding actions reference data

INSERT INTO eu_action_type (id, name, description, priority) VALUES
  ( 1,  'COFUND-EJP',     'European Joint Programme Cofund',                                         1),
  ( 2,  'CSA',            'Coordination and support action',                                         2),
  ( 3,  'ERA-NET-Cofund', 'ERA-NET Cofund',                                                          3),
  ( 4,  'ERC-ADG',        'European Research Council Advanced Grant',                                4),
  ( 5,  'ERC-COG',        'European Research Council Consolidator Grant',                            5),
  ( 6,  'ERC-POC',        'European Research Council Proof of Concept Grant',                        6),
  ( 7,  'ERC-STG',        'European Research Council Starting Grant',                                7),
  ( 8,  'ERC-SyG',        'European Research Council Synergy Grant',                                 8),
  ( 9,  'FP7',            'Framework Programme 7',                                                   9),
  (10,  'FPA',            'Framework Partnership Agreement',                                        10),
  (11,  'FTI',            'Fast track to Innovation',                                               11),
  (12,  'IA',             'Innovation action',                                                      12),
  (13,  'IPr',            'Inducement Prize',                                                       13),
  (14,  'KICS',           'Knowledge and Innovation Communities',                                   14),
  (15,  'MSCA-Cofund',    'Marie Skłodowska-Curie actions Cofund',                                  15),
  (16,  'MSCA-IF',        'Marie Skłodowska-Curie actions Individual Fellowships',                  16),
  (17,  'MSCA-ITN',       'Marie Skłodowska-Curie actions Innovative Training Networks',            17),
  (18,  'MSCA-RISE',      'Marie Skłodowska-Curie actions Research and Innovation Staff Exchange',  18),
  (19,  'PCP',            'Pre-Commercial Procurement',                                             19),
  (20,  'PPI',            'Public Procurement of Innovative solutions',                             20),
  (21,  'RIA',            'Research and Innovation action',                                         21),
  (22,  'RPr',            'Recognition Prize',                                                      22),
  (23,  'SME-1',          'SME Instrument phase 1',                                                 23),
  (24,  'SME-2',          'SME Instrument phase 2',                                                 24);