DELETE FROM cost where application_finance_id=7;
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('125', NULL, NULL, '123456', NULL, 'tsb_reference', '7', '20');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('126', '1000', NULL, NULL, NULL, 'incurred_staff', '7', '28');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('127', '1000', NULL, NULL, NULL, 'incurred_travel_subsistence', '7', '33');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('128', '1000', NULL, NULL, NULL, 'incurred_other_costs', '7', '30');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('129', '1000', NULL, NULL, NULL, 'allocated_investigators', '7', '28');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('120', '1000', NULL, NULL, NULL, 'allocated_estates_costs', '7', '34');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('131', '1000', NULL, NULL, NULL, 'allocated_other_costs', '7', '34');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('132', '1000', NULL, NULL, NULL, 'indirect_costs', '7', '29');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('133', '1000', NULL, NULL, NULL, 'exceptions_staff', '7', '28');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('134', '1000', NULL, NULL, NULL, 'exceptions_other_costs', '7', '34');

DELETE FROM cost where application_finance_id=9;
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('145', NULL, NULL, '123456', NULL, 'tsb_reference', '9', '20');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('146', '1000', NULL, NULL, NULL, 'incurred_staff', '9', '28');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('147', '1000', NULL, NULL, NULL, 'incurred_travel_subsistence', '9', '33');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('148', '1000', NULL, NULL, NULL, 'incurred_other_costs', '9', '30');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('149', '1000', NULL, NULL, NULL, 'allocated_investigators', '9', '28');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('150', '1000', NULL, NULL, NULL, 'allocated_estates_costs', '9', '34');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('151', '1000', NULL, NULL, NULL, 'allocated_other_costs', '9', '34');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('152', '1000', NULL, NULL, NULL, 'indirect_costs', '9', '29');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('153', '1000', NULL, NULL, NULL, 'exceptions_staff', '9', '28');
INSERT  IGNORE INTO `cost` (`id`, `cost`, `description`, `item`, `quantity`, `name`, `application_finance_id`, `question_id`) VALUES ('154', '1000', NULL, NULL, NULL, 'exceptions_other_costs', '9', '34');
