SET @programme_competition_id = (SELECT `template_competition_id` FROM `competition_type` WHERE name='Programme');
SET @sector_competition_id = (SELECT `template_competition_id` FROM `competition_type` WHERE name='Sector');

SET @assessment_scope='ASSESSMENT';

SET @assessor_research_category_type=21;
SET @assessor_scope_type=22;
SET @assessor_score_type=23;
SET @assessor_feedback_type=2;

INSERT INTO `form_input` (`question_id`, `competition_id`, `form_input_type_id`, `included_in_application_summary`, `description`, `priority`, `scope`, `guidance_question`, `guidance_answer`) VALUES
 -- Programme Assessment form inputs
 -- Application questions
 (301, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (301, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing business opportunity', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The applicants have a very clear understanding of the business opportunity and the problems that must be overcome to enable successful exploitation. The project is well aligned with these needs.<tr><th scope=\"row\">7-8</th><td>The applicants have a good idea of the potential market and opportunities. The needs of the customer are central to the project\'s objectives.<tr><th scope=\"row\">5-6</th><td>The business opportunity is plausible but not clearly expressed in terms of customer needs.<tr><th scope=\"row\">3-4</th><td>The business opportunity is unrealistic or poorly defined. The customer\'s true needs are not well understood and are not linked to the project\'s objectives.<tr><th scope=\"row\">1-2</th><td>There is little or no business drive to the project. The results are not relevant to the target customers or no customer interests are provided.</table>'),
 (302, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (302, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope,  'Guidance for assessing market opportunity', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The market size and dynamics are quantified clearly and to sufficient resolution to be relevant to the project. The market is clearly well understood. The return on investment is clearly stated, quantified and realistic.<tr><th scope=\"row\">7-8</th><td>The market size and dynamics are described with some quantification relevant to the project. Market understanding is acceptable and the return on investment is achievable.<tr><th scope=\"row\">5-6</th><td>The market size and dynamics are understood but poorly quantified or stated at a level not really relevant for the project. Return on investment is plausible or badly defined.<tr><th scope=\"row\">3-4</th><td>The market size is not quantified but there is some understanding. Return on investment is ill defined or unrealistic.<tr><th scope=\"row\">1-2</th><td>The market is not well defined or is wrong. No sensible return on investment is provided.</table>'),
 (303, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (303, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing project exploitation', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The principle exploitable outputs of the project are identified together with clear and achievable exploitation methods. Dissemination opportunities are also identified and appropriate.<tr><th scope=\"row\">7-8</th><td>The main exploitable output of the project is identified and a realistic method defined. Some dissemination is also explained.<tr><th scope=\"row\">5-6</th><td>An exploitation method is defined but lacking in detail or is only just feasible. Dissemination is mentioned.<tr><th scope=\"row\">3-4</th><td>The exploitation and dissemination methods described are unrealistic or ill-defined.<tr><th scope=\"row\">1-2</th><td>The exploitation method is missing or un-feasible and unlikely to succeed.</table>'),
 (304, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (304, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing project benefits', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>Inside and outside benefits are well defined, realistic and of significantly positive economic, environmental or social impact. Routes to exploit these benefits are also provided.<tr><th scope=\"row\">7-8</th><td>Some positive outside benefits are defined and are realistic. Methods of addressing these opportunities are described.<tr><th scope=\"row\">5-6</th><td>Some positive outside benefits are described but the methods to exploit these are not obvious. Or the project is likely to have a negative impact but some mitigation or a balance against the internal benefits is proposed.<tr><th scope=\"row\">3-4</th><td>The project has no outside benefits or is potentially damaging to other stakeholders. No mitigation or exploitation is suggested.<tr><th scope=\"row\">1-2</th><td>The project is damaging to other stakeholders with no realistic mitigation or balance described.</table>'),
 (305, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (305, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing technical approach', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The project plan is fully described and complete with milestones and timeframes. The plan is realistic and should meet the objectives of the project.<tr><th scope=\"row\">7-8</th><td>The plan is well described and complete. There is a reasonable chance that it will meet the objectives of the project.<tr><th scope=\"row\">5-6</th><td>The plan is not completely described or there may be deficiencies in some aspects. More work will be required before the plan can be said to be realistic.<tr><th scope=\"row\">3-4</th><td>The plan has serious deficiencies or major missing aspects. The plan has little chance of meeting the objectives of the project.<tr><th scope=\"row\">1-2</th><td>The plan is totally unrealistic or fails to meet the objectives of the project.</table>'),
 (306, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (306, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing innovation', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The project is significantly innovative either commercially or technically and will make a substantial contribution to the field. Solid evidence is presented to substantiate the level of innovation.<tr><th scope=\"row\">7-8</th><td>The project will be innovative and relevant to the market. There is high confidence that there is freedom to operate.<tr><th scope=\"row\">5-6</th><td>The project is innovative but there is a lack of presented evidence as to the freedom to operate.<tr><th scope=\"row\">3-4</th><td>The project lacks sufficient innovation both technically and commercially.<tr><th scope=\"row\">1-2</th><td>The project is either not innovative or there is no exploitable route due to previous IP.</table>'),
 (307, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (307, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing risks', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>A thorough risk analysis has been presented across all 3 risk categories. The mitigation and risk management strategies proposed are also appropriate and professional.<tr><th scope=\"row\">7-8</th><td>A good risk analysis has been carried out and the management methods and mitigation strategies proposed are realistic.<tr><th scope=\"row\">5-6</th><td>Most major risks have been identified but there are some gaps or the mitigation and management is insufficient to properly control the risks.<tr><th scope=\"row\">3-4</th><td>The risk analysis is poor or misses major areas of risk. The mitigation and management is poor.<tr><th scope=\"row\">1-2</th><td>The risk analysis is superficial with minimal mitigation or management suggested.</table>'),
 (308, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (308, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing team skills', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The consortium is ideally placed to carry out the project AND exploit the results. The skills are well balanced and the partners likely to form a strong consortium with good knowledge transfer.<tr><th scope=\"row\">7-8</th><td>The consortium is strong and contains all the required skills and experience. The consortium is likely to work well.<tr><th scope=\"row\">5-6</th><td>The consortium has most of the required skills and experience but there are a few gaps. The consortium will need to work hard to maintain a good working relationship.<tr><th scope=\"row\">3-4</th><td>There are significant gaps in the consortium or the formation objectives are unclear. There could be some passengers or the balance of work/commitment is poor.<tr><th scope=\"row\">1-2</th><td>The consortium is not capable of either carrying out the project or exploiting the results.</table>'),
 (313, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (313, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing financial commitment', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The project costs are entirely appropriate. Any mix of research and development types (eg industrial research with some work packages of experimental development) is justified and costed correctly.<tr><th scope=\"row\">7-8</th><td>The project costs are appropriate and should be sufficient to successfully complete the project. Any mix of research and development types is justified and costed correctly.<tr><th scope=\"row\">5-6</th><td>The project costs and justifications are broadly correct but there are some concerns. Any mix of research and development types is just about acceptable.<tr><th scope=\"row\">3-4</th><td>The costs are either too high or too low to carry out the project. Poor justification is provided for any research and development type mix.<tr><th scope=\"row\">1-2</th><td>The costs are not appropriate or justified. Any mix of research and development type is not justified.</table>'),
 (314, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (314, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing added value', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The project will significantly increase the industrial partners\' R&D spend during the project and afterwards. The additionality arguments are very strong and believable.<tr><th scope=\"row\">7-8</th><td>The project will increase the industrial partners\' commitment to R&D. The additionality arguments are good and justified.<tr><th scope=\"row\">5-6</th><td>The project will improve the industrial partners\' commitment to R&D. The additionality arguments are just about acceptable.<tr><th scope=\"row\">3-4</th><td>There is not likely to be any improvement to the industrial partner\'s commitment to R&D. The additionality arguments are poor or not sufficiently justified.<tr><th scope=\"row\">1-2</th><td>The work should be funded internally and does not deserve state funding.</table>'),
  -- Scope question
 (312, @programme_competition_id, @assessor_research_category_type, '0', 'Please select the research category for this project', '0', @assessment_scope, NULL, NULL),
 (312, @programme_competition_id, @assessor_scope_type, '0', 'Is the application in scope?', '0', @assessment_scope, NULL, NULL),
 (312, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing scope', '<p>Your answer should be based upon the following:<table><tr><th scope=\"row\">YES<td><p>The application contains the following:<ul><li>Is the consortia business led?<li>Are there two or more partners to the collaboration?<li>Does it meet the scope of the competition as defined in the competition brief?</ul><tr><th scope=\"row\">NO<td><p>One or more of the above requirements have not been satisfied.</table><p class=extra-margin>Your assessment of the project scope should be based upon the <a href=\"https://www.gov.uk/government/publications/funding-competition-connected-digital-additive-manufacturing/connected-digital-additive-manufacturing-competition-brief\">competition brief</a>.'),
 -- Sector Assessment form inputs
 -- Application questions
 (336, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (336, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing business opportunity', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The applicants have a very clear understanding of the business opportunity and the problems that must be overcome to enable successful exploitation. The project is well aligned with these needs.<tr><th scope=\"row\">7-8</th><td>The applicants have a good idea of the potential market and opportunities. The needs of the customer are central to the project\'s objectives.<tr><th scope=\"row\">5-6</th><td>The business opportunity is plausible but not clearly expressed in terms of customer needs.<tr><th scope=\"row\">3-4</th><td>The business opportunity is unrealistic or poorly defined. The customer\'s true needs are not well understood and are not linked to the project\'s objectives.<tr><th scope=\"row\">1-2</th><td>There is little or no business drive to the project. The results are not relevant to the target customers or no customer interests are provided.</table>'),
 (337, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (337, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope,  'Guidance for assessing market opportunity', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The market size and dynamics are quantified clearly and to sufficient resolution to be relevant to the project. The market is clearly well understood. The return on investment is clearly stated, quantified and realistic.<tr><th scope=\"row\">7-8</th><td>The market size and dynamics are described with some quantification relevant to the project. Market understanding is acceptable and the return on investment is achievable.<tr><th scope=\"row\">5-6</th><td>The market size and dynamics are understood but poorly quantified or stated at a level not really relevant for the project. Return on investment is plausible or badly defined.<tr><th scope=\"row\">3-4</th><td>The market size is not quantified but there is some understanding. Return on investment is ill defined or unrealistic.<tr><th scope=\"row\">1-2</th><td>The market is not well defined or is wrong. No sensible return on investment is provided.</table>'),
 (338, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (338, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing project exploitation', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The principle exploitable outputs of the project are identified together with clear and achievable exploitation methods. Dissemination opportunities are also identified and appropriate.<tr><th scope=\"row\">7-8</th><td>The main exploitable output of the project is identified and a realistic method defined. Some dissemination is also explained.<tr><th scope=\"row\">5-6</th><td>An exploitation method is defined but lacking in detail or is only just feasible. Dissemination is mentioned.<tr><th scope=\"row\">3-4</th><td>The exploitation and dissemination methods described are unrealistic or ill-defined.<tr><th scope=\"row\">1-2</th><td>The exploitation method is missing or un-feasible and unlikely to succeed.</table>'),
 (339, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (339, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing project benefits', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>Inside and outside benefits are well defined, realistic and of significantly positive economic, environmental or social impact. Routes to exploit these benefits are also provided.<tr><th scope=\"row\">7-8</th><td>Some positive outside benefits are defined and are realistic. Methods of addressing these opportunities are described.<tr><th scope=\"row\">5-6</th><td>Some positive outside benefits are described but the methods to exploit these are not obvious. Or the project is likely to have a negative impact but some mitigation or a balance against the internal benefits is proposed.<tr><th scope=\"row\">3-4</th><td>The project has no outside benefits or is potentially damaging to other stakeholders. No mitigation or exploitation is suggested.<tr><th scope=\"row\">1-2</th><td>The project is damaging to other stakeholders with no realistic mitigation or balance described.</table>'),
 (340, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (340, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing technical approach', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The project plan is fully described and complete with milestones and timeframes. The plan is realistic and should meet the objectives of the project.<tr><th scope=\"row\">7-8</th><td>The plan is well described and complete. There is a reasonable chance that it will meet the objectives of the project.<tr><th scope=\"row\">5-6</th><td>The plan is not completely described or there may be deficiencies in some aspects. More work will be required before the plan can be said to be realistic.<tr><th scope=\"row\">3-4</th><td>The plan has serious deficiencies or major missing aspects. The plan has little chance of meeting the objectives of the project.<tr><th scope=\"row\">1-2</th><td>The plan is totally unrealistic or fails to meet the objectives of the project.</table>'),
 (341, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (341, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing innovation', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The project is significantly innovative either commercially or technically and will make a substantial contribution to the field. Solid evidence is presented to substantiate the level of innovation.<tr><th scope=\"row\">7-8</th><td>The project will be innovative and relevant to the market. There is high confidence that there is freedom to operate.<tr><th scope=\"row\">5-6</th><td>The project is innovative but there is a lack of presented evidence as to the freedom to operate.<tr><th scope=\"row\">3-4</th><td>The project lacks sufficient innovation both technically and commercially.<tr><th scope=\"row\">1-2</th><td>The project is either not innovative or there is no exploitable route due to previous IP.</table>'),
 (342, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (342, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing risks', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>A thorough risk analysis has been presented across all 3 risk categories. The mitigation and risk management strategies proposed are also appropriate and professional.<tr><th scope=\"row\">7-8</th><td>A good risk analysis has been carried out and the management methods and mitigation strategies proposed are realistic.<tr><th scope=\"row\">5-6</th><td>Most major risks have been identified but there are some gaps or the mitigation and management is insufficient to properly control the risks.<tr><th scope=\"row\">3-4</th><td>The risk analysis is poor or misses major areas of risk. The mitigation and management is poor.<tr><th scope=\"row\">1-2</th><td>The risk analysis is superficial with minimal mitigation or management suggested.</table>'),
 (343, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (343, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing team skills', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The consortium is ideally placed to carry out the project AND exploit the results. The skills are well balanced and the partners likely to form a strong consortium with good knowledge transfer.<tr><th scope=\"row\">7-8</th><td>The consortium is strong and contains all the required skills and experience. The consortium is likely to work well.<tr><th scope=\"row\">5-6</th><td>The consortium has most of the required skills and experience but there are a few gaps. The consortium will need to work hard to maintain a good working relationship.<tr><th scope=\"row\">3-4</th><td>There are significant gaps in the consortium or the formation objectives are unclear. There could be some passengers or the balance of work/commitment is poor.<tr><th scope=\"row\">1-2</th><td>The consortium is not capable of either carrying out the project or exploiting the results.</table>'),
 (348, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (348, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing financial commitment', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The project costs are entirely appropriate. Any mix of research and development types (eg industrial research with some work packages of experimental development) is justified and costed correctly.<tr><th scope=\"row\">7-8</th><td>The project costs are appropriate and should be sufficient to successfully complete the project. Any mix of research and development types is justified and costed correctly.<tr><th scope=\"row\">5-6</th><td>The project costs and justifications are broadly correct but there are some concerns. Any mix of research and development types is just about acceptable.<tr><th scope=\"row\">3-4</th><td>The costs are either too high or too low to carry out the project. Poor justification is provided for any research and development type mix.<tr><th scope=\"row\">1-2</th><td>The costs are not appropriate or justified. Any mix of research and development type is not justified.</table>'),
 (349, @programme_competition_id, @assessor_score_type, '0', 'Question score', '0', @assessment_scope, NULL, NULL),
 (349, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing added value', '<p>Your score should be based upon the following:<table><tr><th scope=\"row\">9-10</th><td>The project will significantly increase the industrial partners\' R&D spend during the project and afterwards. The additionality arguments are very strong and believable.<tr><th scope=\"row\">7-8</th><td>The project will increase the industrial partners\' commitment to R&D. The additionality arguments are good and justified.<tr><th scope=\"row\">5-6</th><td>The project will improve the industrial partners\' commitment to R&D. The additionality arguments are just about acceptable.<tr><th scope=\"row\">3-4</th><td>There is not likely to be any improvement to the industrial partner\'s commitment to R&D. The additionality arguments are poor or not sufficiently justified.<tr><th scope=\"row\">1-2</th><td>The work should be funded internally and does not deserve state funding.</table>'),
 -- Scope question
 (347, @programme_competition_id, @assessor_research_category_type, '0', 'Please select the research category for this project', '0', @assessment_scope, NULL, NULL),
 (347, @programme_competition_id, @assessor_scope_type, '0', 'Is the application in scope?', '0', @assessment_scope, NULL, NULL),
 (347, @programme_competition_id, @assessor_feedback_type, '0', 'Feedback', '0', @assessment_scope, 'Guidance for assessing scope', '<p>Your answer should be based upon the following:<table><tr><th scope=\"row\">YES<td><p>The application contains the following:<ul><li>Is the consortia business led?<li>Are there two or more partners to the collaboration?<li>Does it meet the scope of the competition as defined in the competition brief?</ul><tr><th scope=\"row\">NO<td><p>One or more of the above requirements have not been satisfied.</table><p class=extra-margin>Your assessment of the project scope should be based upon the <a href=\"https://www.gov.uk/government/publications/funding-competition-connected-digital-additive-manufacturing/connected-digital-additive-manufacturing-competition-brief\">competition brief</a>.');


SET @row1_subject='1,2';
SET @scope_row1_subject='NO';
SET @row1_justification='The plan is totally unrealistic or fails to meet the objectives of the project.';
SET @row1_priority=0;

SET @row2_subject='3,4';
SET @scope_row2_subject='YES';
SET @row2_justification='The plan has serious deficiencies or major missing aspects. The plan has little chance of meeting the objectives of the project.';
SET @row2_priority=1;

SET @row3_subject='5,6';
SET @row3_justification='The plan is not completely described or there may be some deficiencies in some aspects. More work will be required before the plan can be said to be realistic.';
SET @row3_priority=2;

SET @row4_subject='7,8';
SET @row4_justification='The plan is well described and complete. There is a reasonable chance it will meet the objectives if the project.';
SET @row4_priority=3;

SET @row5_subject='9,10';
SET @row5_justification='The project is fully described with milestones and timeframes. The plan is realistic and should meet the objectives of the project.';
SET @row5_priority=4;

SET @programme_business_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=301 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_market_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=302 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_project_exploitation_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=303 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_project_benefits_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=304 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_technical_approach_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=305 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_innovation_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=306 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_risks_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=307 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_team_skills_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=308 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_funding_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=313 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_adding_value_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=314 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @programme_scope_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=312 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);

SET @sector_business_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=336 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_market_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=337 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_project_exploitation_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=338 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_project_benefits_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=339 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_technical_approach_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=340 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_innovation_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=341 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_risks_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=342 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_team_skills_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=343 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_funding_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=348 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_adding_value_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=349 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);
SET @sector_scope_form_input_id = (SELECT `id` FROM `form_input` WHERE question_id=347 AND form_input_type_id=@assessor_feedback_type AND scope=@assessment_scope);


INSERT INTO `guidance_row` (form_input_id, priority, subject, justification) VALUES
    -- Programme Guidance Rows
    -- Business Opportunity
    (@programme_business_form_input_id, @row1_priority, @row1_subject, 'There is little or no business drive to the project. The results are not relevant to the target customers or no customer interests are provided.'),
    (@programme_business_form_input_id, @row2_priority, @row2_subject, 'The business opportunity is unrealistic or poorly defined. The customer\'s true needs are not well understood and are not linked to the project\'s objectives.'),
    (@programme_business_form_input_id, @row3_priority, @row3_subject, 'The business opportunity is plausible but not clearly expressed in terms of customer needs.'),
    (@programme_business_form_input_id, @row4_priority, @row4_subject, 'The applicants have a good idea of the potential market and opportunities. The needs of the customer are central to the project\'s objectives.'),
    (@programme_business_form_input_id, @row5_priority, @row5_subject, 'The applicants have a very clear understanding of the business opportunity and the problems that must be overcome to enable successful exploitation. The project is well aligned with these needs.'),
    -- Market Opportunity
    (@programme_market_form_input_id, @row1_priority, @row1_subject, 'The market is not well defined or is wrong. No sensible return on investment is provided.'),
    (@programme_market_form_input_id, @row2_priority, @row2_subject, 'The market size is not quantified but there is some understanding. Return on investment is ill defined or unrealistic.'),
    (@programme_market_form_input_id, @row3_priority, @row3_subject, 'The market size and dynamics are understood but poorly quantified or stated at a level not really relevant for the project. Return on investment is plausible or badly defined.'),
    (@programme_market_form_input_id, @row4_priority, @row4_subject, 'The market size and dynamics are described with some quantification relevant to the project. Market understanding is acceptable and the return on investment is achievable.'),
    (@programme_market_form_input_id, @row5_priority, @row5_subject, 'The market size and dynamics are quantified clearly and to sufficient resolution to be relevant to the project. The market is clearly well understood. The return on investment is clearly stated, quantified and realistic.'),
    -- Project  Exploitation
    (@programme_project_exploitation_form_input_id, @row1_priority, @row1_subject, 'The exploitation method is missing or un-feasible and unlikely to succeed.'),
    (@programme_project_exploitation_form_input_id, @row2_priority, @row2_subject, 'The exploitation and dissemination methods described are unrealistic or ill-defined.'),
    (@programme_project_exploitation_form_input_id, @row3_priority, @row3_subject, 'An exploitation method is defined but lacking in detail or is only just feasible. Dissemination is mentioned.'),
    (@programme_project_exploitation_form_input_id, @row4_priority, @row4_subject, 'The main exploitable output of the project is identified and a realistic method defined. Some dissemination is also explained.'),
    (@programme_project_exploitation_form_input_id, @row5_priority, @row5_subject, 'The principle exploitable outputs of the project are identified together with clear and achievable exploitation methods. Dissemination opportunities are also identified and appropriate.'),
    -- Project  Benefits
    (@programme_project_benefits_form_input_id, @row1_priority, @row1_subject, 'The project is damaging to other stakeholders with no realistic mitigation or balance described.'),
    (@programme_project_benefits_form_input_id, @row2_priority, @row2_subject, 'The project has no outside benefits or is potentially damaging to other stakeholders. No mitigation or exploitation is suggested.'),
    (@programme_project_benefits_form_input_id, @row3_priority, @row3_subject, 'Some positive outside benefits are described but the methods to exploit these are not obvious. Or the project is likely to have a negative impact but some mitigation or a balance against the internal benefits is proposed.'),
    (@programme_project_benefits_form_input_id, @row4_priority, @row4_subject, 'Some positive outside benefits are defined and are realistic. Methods of addressing these opportunities are described.'),
    (@programme_project_benefits_form_input_id, @row5_priority, @row5_subject, 'Inside and outside benefits are well defined, realistic and of significantly positive economic, environmental or social impact. Routes to exploit these benefits are also provided.'),
    -- Technical Approach
    (@programme_technical_approach_form_input_id, @row1_priority, @row1_subject, 'The plan is totally unrealistic or fails to meet the objectives of the project.'),
    (@programme_technical_approach_form_input_id, @row2_priority, @row2_subject, 'The plan has serious deficiencies or major missing aspects. The plan has little chance of meeting the objectives of the project.'),
    (@programme_technical_approach_form_input_id, @row3_priority, @row3_subject, 'The plan is not completely described or there may be deficiencies in some aspects. More work will be required before the plan can be said to be realistic.'),
    (@programme_technical_approach_form_input_id, @row4_priority, @row4_subject, 'The plan is well described and complete. There is a reasonable chance that it will meet the objectives of the project.'),
    (@programme_technical_approach_form_input_id, @row5_priority, @row5_subject, 'The project plan is fully described and complete with milestones and timeframes. The plan is realistic and should meet the objectives of the project.'),
    -- Innovation
    (@programme_innovation_form_input_id, @row1_priority, @row1_subject, 'The project is either not innovative or there is no exploitable route due to previous IP.'),
    (@programme_innovation_form_input_id, @row2_priority, @row2_subject, 'The project lacks sufficient innovation both technically and commercially.'),
    (@programme_innovation_form_input_id, @row3_priority, @row3_subject, 'The project is innovative but there is a lack of presented evidence as to the freedom to operate.'),
    (@programme_innovation_form_input_id, @row4_priority, @row4_subject, 'The project will be innovative and relevant to the market. There is high confidence that there is freedom to operate.'),
    (@programme_innovation_form_input_id, @row5_priority, @row5_subject, 'The project is significantly innovative either commercially or technically and will make a substantial contribution to the field. Solid evidence is presented to substantiate the level of innovation.'),
    -- Risks
    (@programme_risks_form_input_id, @row1_priority, @row1_subject, 'The risk analysis is superficial with minimal mitigation or management suggested.'),
    (@programme_risks_form_input_id, @row2_priority, @row2_subject, 'The risk analysis is poor or misses major areas of risk. The mitigation and management is poor.'),
    (@programme_risks_form_input_id, @row3_priority, @row3_subject, 'Most major risks have been identified but there are some gaps or the mitigation and management is insufficient to properly control the risks.'),
    (@programme_risks_form_input_id, @row4_priority, @row4_subject, 'A good risk analysis has been carried out and the management methods and mitigation strategies proposed are realistic.'),
    (@programme_risks_form_input_id, @row5_priority, @row5_subject, 'A thorough risk analysis has been presented across all 3 risk categories. The mitigation and risk management strategies proposed are also appropriate and professional.'),
    -- Team Skills
    (@programme_team_skills_form_input_id, @row1_priority, @row1_subject, 'The consortium is not capable of either carrying out the project or exploiting the results.'),
    (@programme_team_skills_form_input_id, @row2_priority, @row2_subject, 'There are significant gaps in the consortium or the formation objectives are unclear. There could be some passengers or the balance of work/commitment is poor.'),
    (@programme_team_skills_form_input_id, @row3_priority, @row3_subject, 'The consortium has most of the required skills and experience but there are a few gaps. The consortium will need to work hard to maintain a good working relationship.'),
    (@programme_team_skills_form_input_id, @row4_priority, @row4_subject, 'The consortium is strong and contains all the required skills and experience. The consortium is likely to work well.'),
    (@programme_team_skills_form_input_id, @row5_priority, @row5_subject, 'The consortium is ideally placed to carry out the project AND exploit the results. The skills are well balanced and the partners likely to form a strong consortium with good knowledge transfer.'),
    -- Funding
    (@programme_funding_form_input_id, @row1_priority, @row1_subject, 'The costs are not appropriate or justified. Any mix of research and development type is not justified.'),
    (@programme_funding_form_input_id, @row2_priority, @row2_subject, 'The costs are either too high or too low to carry out the project. Poor justification is provided for any research and development type mix.'),
    (@programme_funding_form_input_id, @row3_priority, @row3_subject, 'The project costs and justifications are broadly correct but there are some concerns. Any mix of research and development types is just about acceptable.'),
    (@programme_funding_form_input_id, @row4_priority, @row4_subject, 'The project costs are appropriate and should be sufficient to successfully complete the project. Any mix of research and development types is justified and costed correctly.'),
    (@programme_funding_form_input_id, @row5_priority, @row5_subject, 'The project costs are entirely appropriate. Any mix of research and development types (eg industrial research with some work packages of experimental development) is justified and costed correctly.'),
    -- Addding Value
    (@programme_adding_value_form_input_id, @row1_priority, @row1_subject, 'The work should be funded internally and does not deserve state funding.'),
    (@programme_adding_value_form_input_id, @row2_priority, @row2_subject, 'There is not likely to be any improvement to the industrial partner\'s commitment to R&D. The additionally arguments are poor or not sufficiently justified.'),
    (@programme_adding_value_form_input_id, @row3_priority, @row3_subject, 'The project will improve the industrial partners\' commitment to R&D. The additionality arguments are just about acceptable.'),
    (@programme_adding_value_form_input_id, @row4_priority, @row4_subject, 'The project will increase the industrial partners\' commitment to R&D. The additionality arguments are good and justified.'),
    (@programme_adding_value_form_input_id, @row5_priority, @row5_subject, 'The project will significantly increase the industrial partners\' R&D spend during the project and afterwards. The additionality arguments are very strong and believable.'),
    -- Scope
    (@programme_team_skills_form_input_id, @row1_priority, @scope_row1_subject, 'One or more of the above requirements have not been satisfied.'),
    (@programme_team_skills_form_input_id, @row2_priority, @scope_row2_subject, 'The application contains the following:\nIs the consortia business led?\nAre there two or more partners to the collaboration?\nDoes it meet the scope of the competition as defined in the competition brief?'),
    -- Sector Guidance Rows
    -- Business Opportunity
    (@sector_business_form_input_id, @row1_priority, @row1_subject, 'There is little or no business drive to the project. The results are not relevant to the target customers or no customer interests are provided.'),
    (@sector_business_form_input_id, @row2_priority, @row2_subject, 'The business opportunity is unrealistic or poorly defined. The customer\'s true needs are not well understood and are not linked to the project\'s objectives.'),
    (@sector_business_form_input_id, @row3_priority, @row3_subject, 'The business opportunity is plausible but not clearly expressed in terms of customer needs.'),
    (@sector_business_form_input_id, @row4_priority, @row4_subject, 'The applicants have a good idea of the potential market and opportunities. The needs of the customer are central to the project\'s objectives.'),
    (@sector_business_form_input_id, @row5_priority, @row5_subject, 'The applicants have a very clear understanding of the business opportunity and the problems that must be overcome to enable successful exploitation. The project is well aligned with these needs.'),
    -- Market Opportunity
    (@sector_market_form_input_id, @row1_priority, @row1_subject, 'The market is not well defined or is wrong. No sensible return on investment is provided.'),
    (@sector_market_form_input_id, @row2_priority, @row2_subject, 'The market size is not quantified but there is some understanding. Return on investment is ill defined or unrealistic.'),
    (@sector_market_form_input_id, @row3_priority, @row3_subject, 'The market size and dynamics are understood but poorly quantified or stated at a level not really relevant for the project. Return on investment is plausible or badly defined.'),
    (@sector_market_form_input_id, @row4_priority, @row4_subject, 'The market size and dynamics are described with some quantification relevant to the project. Market understanding is acceptable and the return on investment is achievable.'),
    (@sector_market_form_input_id, @row5_priority, @row5_subject, 'The market size and dynamics are quantified clearly and to sufficient resolution to be relevant to the project. The market is clearly well understood. The return on investment is clearly stated, quantified and realistic.'),
    -- Project  Exploitation
    (@sector_project_exploitation_form_input_id, @row1_priority, @row1_subject, 'The exploitation method is missing or un-feasible and unlikely to succeed.'),
    (@sector_project_exploitation_form_input_id, @row2_priority, @row2_subject, 'The exploitation and dissemination methods described are unrealistic or ill-defined.'),
    (@sector_project_exploitation_form_input_id, @row3_priority, @row3_subject, 'An exploitation method is defined but lacking in detail or is only just feasible. Dissemination is mentioned.'),
    (@sector_project_exploitation_form_input_id, @row4_priority, @row4_subject, 'The main exploitable output of the project is identified and a realistic method defined. Some dissemination is also explained.'),
    (@sector_project_exploitation_form_input_id, @row5_priority, @row5_subject, 'The principle exploitable outputs of the project are identified together with clear and achievable exploitation methods. Dissemination opportunities are also identified and appropriate.'),
    -- Project  Benefits
    (@sector_project_benefits_form_input_id, @row1_priority, @row1_subject, 'The project is damaging to other stakeholders with no realistic mitigation or balance described.'),
    (@sector_project_benefits_form_input_id, @row2_priority, @row2_subject, 'The project has no outside benefits or is potentially damaging to other stakeholders. No mitigation or exploitation is suggested.'),
    (@sector_project_benefits_form_input_id, @row3_priority, @row3_subject, 'Some positive outside benefits are described but the methods to exploit these are not obvious. Or the project is likely to have a negative impact but some mitigation or a balance against the internal benefits is proposed.'),
    (@sector_project_benefits_form_input_id, @row4_priority, @row4_subject, 'Some positive outside benefits are defined and are realistic. Methods of addressing these opportunities are described.'),
    (@sector_project_benefits_form_input_id, @row5_priority, @row5_subject, 'Inside and outside benefits are well defined, realistic and of significantly positive economic, environmental or social impact. Routes to exploit these benefits are also provided.'),
    -- Technical Approach
    (@sector_technical_approach_form_input_id, @row1_priority, @row1_subject, 'The plan is totally unrealistic or fails to meet the objectives of the project.'),
    (@sector_technical_approach_form_input_id, @row2_priority, @row2_subject, 'The plan has serious deficiencies or major missing aspects. The plan has little chance of meeting the objectives of the project.'),
    (@sector_technical_approach_form_input_id, @row3_priority, @row3_subject, 'The plan is not completely described or there may be deficiencies in some aspects. More work will be required before the plan can be said to be realistic.'),
    (@sector_technical_approach_form_input_id, @row4_priority, @row4_subject, 'The plan is well described and complete. There is a reasonable chance that it will meet the objectives of the project.'),
    (@sector_technical_approach_form_input_id, @row5_priority, @row5_subject, 'The project plan is fully described and complete with milestones and timeframes. The plan is realistic and should meet the objectives of the project.'),
    -- Innovation
    (@sector_innovation_form_input_id, @row1_priority, @row1_subject, 'The project is either not innovative or there is no exploitable route due to previous IP.'),
    (@sector_innovation_form_input_id, @row2_priority, @row2_subject, 'The project lacks sufficient innovation both technically and commercially.'),
    (@sector_innovation_form_input_id, @row3_priority, @row3_subject, 'The project is innovative but there is a lack of presented evidence as to the freedom to operate.'),
    (@sector_innovation_form_input_id, @row4_priority, @row4_subject, 'The project will be innovative and relevant to the market. There is high confidence that there is freedom to operate.'),
    (@sector_innovation_form_input_id, @row5_priority, @row5_subject, 'The project is significantly innovative either commercially or technically and will make a substantial contribution to the field. Solid evidence is presented to substantiate the level of innovation.'),
    -- Risks
    (@sector_risks_form_input_id, @row1_priority, @row1_subject, 'The risk analysis is superficial with minimal mitigation or management suggested.'),
    (@sector_risks_form_input_id, @row2_priority, @row2_subject, 'The risk analysis is poor or misses major areas of risk. The mitigation and management is poor.'),
    (@sector_risks_form_input_id, @row3_priority, @row3_subject, 'Most major risks have been identified but there are some gaps or the mitigation and management is insufficient to properly control the risks.'),
    (@sector_risks_form_input_id, @row4_priority, @row4_subject, 'A good risk analysis has been carried out and the management methods and mitigation strategies proposed are realistic.'),
    (@sector_risks_form_input_id, @row5_priority, @row5_subject, 'A thorough risk analysis has been presented across all 3 risk categories. The mitigation and risk management strategies proposed are also appropriate and professional.'),
    -- Team Skills
    (@sector_team_skills_form_input_id, @row1_priority, @row1_subject, 'The consortium is not capable of either carrying out the project or exploiting the results.'),
    (@sector_team_skills_form_input_id, @row2_priority, @row2_subject, 'There are significant gaps in the consortium or the formation objectives are unclear. There could be some passengers or the balance of work/commitment is poor.'),
    (@sector_team_skills_form_input_id, @row3_priority, @row3_subject, 'The consortium has most of the required skills and experience but there are a few gaps. The consortium will need to work hard to maintain a good working relationship.'),
    (@sector_team_skills_form_input_id, @row4_priority, @row4_subject, 'The consortium is strong and contains all the required skills and experience. The consortium is likely to work well.'),
    (@sector_team_skills_form_input_id, @row5_priority, @row5_subject, 'The consortium is ideally placed to carry out the project AND exploit the results. The skills are well balanced and the partners likely to form a strong consortium with good knowledge transfer.'),
    -- Funding
    (@sector_funding_form_input_id, @row1_priority, @row1_subject, 'The costs are not appropriate or justified. Any mix of research and development type is not justified.'),
    (@sector_funding_form_input_id, @row2_priority, @row2_subject, 'The costs are either too high or too low to carry out the project. Poor justification is provided for any research and development type mix.'),
    (@sector_funding_form_input_id, @row3_priority, @row3_subject, 'The project costs and justifications are broadly correct but there are some concerns. Any mix of research and development types is just about acceptable.'),
    (@sector_funding_form_input_id, @row4_priority, @row4_subject, 'The project costs are appropriate and should be sufficient to successfully complete the project. Any mix of research and development types is justified and costed correctly.'),
    (@sector_funding_form_input_id, @row5_priority, @row5_subject, 'The project costs are entirely appropriate. Any mix of research and development types (eg industrial research with some work packages of experimental development) is justified and costed correctly.'),
    -- Addding Value
    (@sector_adding_value_form_input_id, @row1_priority, @row1_subject, 'The work should be funded internally and does not deserve state funding.'),
    (@sector_adding_value_form_input_id, @row2_priority, @row2_subject, 'There is not likely to be any improvement to the industrial partner\'s commitment to R&D. The additionally arguments are poor or not sufficiently justified.'),
    (@sector_adding_value_form_input_id, @row3_priority, @row3_subject, 'The project will improve the industrial partners\' commitment to R&D. The additionality arguments are just about acceptable.'),
    (@sector_adding_value_form_input_id, @row4_priority, @row4_subject, 'The project will increase the industrial partners\' commitment to R&D. The additionality arguments are good and justified.'),
    (@sector_adding_value_form_input_id, @row5_priority, @row5_subject, 'The project will significantly increase the industrial partners\' R&D spend during the project and afterwards. The additionality arguments are very strong and believable.'),
    -- Scope
    (@sector_team_skills_form_input_id, @row1_priority, @scope_row1_subject, 'One or more of the above requirements have not been satisfied.'),
    (@sector_team_skills_form_input_id, @row2_priority, @scope_row2_subject, 'The application contains the following:\nIs the consortia business led?\nAre there two or more partners to the collaboration?\nDoes it meet the scope of the competition as defined in the competition brief?');














