SELECT @comp_id := id FROM competition WHERE name = 'Internet of Things';
SELECT @app_id := id FROM application WHERE competition = @comp_id AND name = 'Sensing & Control network using the lighting infrastructure';
SELECT @project_id := id FROM project WHERE application_id = @app_id;
SELECT @finance_section_id := id FROM section WHERE competition_id = @comp_id AND parent_section_id IS NULL AND name ='Finances';
SELECT @your_finance_section_id := id FROM section WHERE competition_id = @comp_id AND parent_section_id = @finance_section_id AND name ='Your finances';
SELECT @your_organisation_section_id := id FROM section WHERE competition_id = @comp_id AND parent_section_id = @your_finance_section_id AND name ='Your organisation';
SELECT @question_id := id FROM question WHERE section_id = @your_organisation_section_id;
SELECT * FROM form_input WHERE competition_id = @comp_id AND question_id=@question_id AND form_input_type_id IN (24,25,26,27,28);
SELECT @turnover_id := id FROM form_input WHERE competition_id = @comp_id AND question_id=@question_id AND form_input_type_id =24;
SELECT @headcount_id := id FROM form_input WHERE competition_id = @comp_id AND question_id=@question_id AND form_input_type_id =25;
SELECT @user_id := id FROM user WHERE email = 'steve.smith@empire.com';
SELECT @user_id_4 := id FROM user WHERE email = 'jessica.doe@ludlow.co.uk';
SELECT @process_role_id := id FROM process_role WHERE user_id = @user_id;
SELECT @process_role_id_4 := id FROM process_role WHERE user_id = @user_id_4;
SELECT @financial_turnover_id := id FROM form_input WHERE competition_id = @comp_id AND question_id=@question_id AND form_input_type_id =26;
SELECT @financial_headcount_id := id FROM form_input WHERE competition_id = @comp_id AND question_id=@question_id AND form_input_type_id =28;
UPDATE form_input_response SET updated_by_id = @process_role_id WHERE value = '4560000' AND form_input_id =  @financial_turnover_id AND application_id = @app_id;
UPDATE form_input_response SET updated_by_id = @process_role_id WHERE value = '1230' AND form_input_id =  @financial_headcount_id AND application_id = @app_id;
UPDATE form_input_response SET updated_by_id = @process_role_id_4 WHERE value = '1230000' AND form_input_id =  @financial_turnover_id AND application_id = @app_id;
UPDATE form_input_response SET updated_by_id = @process_role_id_4 WHERE value = '4560' AND form_input_id =  @financial_headcount_id AND application_id = @app_id;

SELECT @comp_id_2 := id FROM competition WHERE name = 'Rolling stock future developments';
SELECT @app_id_2 := id FROM application WHERE competition = @comp_id_2 AND name = 'High-speed rail and its effects on air quality';
SELECT @project_id_2 := id FROM project WHERE application_id = @app_id_2;
SELECT @finance_section_id_2 := id FROM section WHERE competition_id = @comp_id_2 AND parent_section_id IS NULL AND name ='Finances';
SELECT @your_finance_section_id_2 := id FROM section WHERE competition_id = @comp_id_2 AND parent_section_id = @finance_section_id_2 AND name ='Your finances';
SELECT @your_organisation_section_id_2 := id FROM section WHERE competition_id = @comp_id_2 AND parent_section_id = @your_finance_section_id_2 AND name ='Your organisation';
SELECT @question_id_2 := id FROM question WHERE section_id = @your_organisation_section_id_2;
SELECT @user_id_2 := id FROM user WHERE email = 'ralph.young@ooba.example.com';
SELECT @user_id_3 := id FROM user WHERE email = 'tina.taylor@wordpedia.example.com';
SELECT @process_role_id_2 := id FROM process_role WHERE user_id = @user_id_2;
SELECT @process_role_id_3 := id FROM process_role WHERE user_id = @user_id_3;
SELECT @turnover_id := id FROM form_input WHERE competition_id = @comp_id_2 AND question_id=@question_id_2 AND form_input_type_id =24;
SELECT @headcount_id := id FROM form_input WHERE competition_id = @comp_id_2 AND question_id=@question_id_2 AND form_input_type_id =25;
UPDATE form_input_response SET updated_by_id = @process_role_id_2 WHERE value = '123000' AND form_input_id =  @turnover_id AND application_id = @app_id_2;
UPDATE form_input_response SET updated_by_id = @process_role_id_2 WHERE value = '456' AND form_input_id =  @headcount_id AND application_id = @app_id_2;
UPDATE form_input_response SET updated_by_id = @process_role_id_3 WHERE value = '456000' AND form_input_id =  @turnover_id AND application_id = @app_id_2;
UPDATE form_input_response SET updated_by_id = @process_role_id_3 WHERE value = '123' AND form_input_id =  @headcount_id AND application_id = @app_id_2;