FROM davidcaste/alpine-java-unlimited-jce:jdk8
MAINTAINER David Soff <dsoff@worth.systems>
EXPOSE 8080
EXPOSE 8090
EXPOSE 8081
EXPOSE 8000
EXPOSE 12345
ENV JAVA_OPTS -Xmx300m
RUN apk --update add curl
COPY certificate /certificate
WORKDIR $JAVA_HOME
RUN bin/keytool -import -trustcacerts -keystore jre/lib/security/cacerts -storepass changeit -noprompt -alias iuk-auth-localdev -file /certificate
WORKDIR /
VOLUME /mnt/ifs_storage

ADD ifs-data-service-@version@.jar app.jar
RUN sh -c 'touch /app.jar'
ENTRYPOINT exec java $JAVA_OPTS -jar app.jar

HEALTHCHECK --interval=15s --timeout=8s \
  CMD curl -f --connect-timeout 5 -m 5 http://localhost:8080/monitoring/health || exit 1
