package com.worth.ifs.application.resource;

public class ClosedCompetitionNotSubmittedApplicationSummaryPageResource extends PageResource<ClosedCompetitionNotSubmittedApplicationSummaryResource> {

}
