UPDATE `section` SET `description`='Please provide Innovate UK with information about your project. These sections are not scored but will provide background to the project.' WHERE `id`='1';

UPDATE `question` SET `guidance_answer`='<p>Describe all the benefits you expect your project to deliver, including:</p><strong>Economic</strong> - this is the real impact the project will have on its economic environment. This is not traditional corporate accounting profit and can include cost avoidance. You should identify and quantify any expected benefits to:</p><ul class=\"list-bullet\">         <li>users (intermediaries and end users)</li><li>suppliers</li><li>broader industrial markets</li><li>the UK economy</li></ul><p><strong>Social</strong> - quantify any expected social impacts, either positive or negative, on, for example:</p><ul class=\"list-bullet\">         <li>quality of life</li><li>social inclusion/exclusion</li><li>education</li><li>public empowerment</li><li>health and safety</li><li>regulation</li><li>diversity</li><li>government priorities</li></ul><p><strong>Environmental</strong> - show how your project will benefit or have a low impact on the environment. For example, this could include:<p><ul class=\"list-bullet\">         <li>careful management of energy consumption</li><li>reductions in carbon emissions</li><li>reducing manufacturing and materials waste</li><li>rendering waste less toxic before disposing of it in a safe and legal manner</li><li>re-manufacturing (cradle to cradle)</li></ul>' WHERE `id`='4';
UPDATE `question` SET `guidance_answer`='<p>You should:</p><ul class=\"list-bullet\">         <li>describe your technical approach including the main objectives of the work</li><li>explain how and why your approach is appropriate</li><li>tell us how you will make sure that the innovative steps in your project are achievable</li><li>describe rival technologies and alternative R&D strategies</li><li>explain why your proposed approach will offer a better outcome</li></ul>' WHERE `id`='5';
UPDATE `question` SET `guidance_answer`='<p>Please describe your plans for limiting and managing risk. You need to:</p><ul class=\"list-bullet\">         <li>identify the project\'s main risks and uncertainties</li><li>detail specific technical, commercial, managerial and environmental risks</li><li>list any other uncertainties such as ethical issues associated with the project</li><li>provide a detailed risk analysis</li><li>rate the main risks as high, medium or low</li><li>show how you\'ll limit the main risks</li><li>identify the project management resources you\'ll use to minimise operational risk</li><li>include arrangements for managing the project team and its partners</li></ul>' WHERE `id`='7';
UPDATE `question` SET `description`='Tell us the total costs of the project and how much funding you need from Innovate UK. Please provide details of your expected project costs along with any supporting information. Please justify any large expenditure in your project.' WHERE `id`='15';
UPDATE `question` SET `description`='Please tell us if you have ever applied for or received any other public sector funding for this project. You should also include details of any offers of funding you\'ve received.' WHERE `id`='35';
UPDATE `question` SET `description`='<p>Administration support costs are related expenses incurred as a result of delivering the project. They are eligible for project funding.</p>' WHERE `id`='22';
UPDATE `question` SET `description`='A common way of estimating administration support costs on Innovate UK projects is to use a flat rate of 20% of labour costs. This is the default rate. If you want to use a different rate, please enter it below and we will assess your administration support costs on this basis.  If your project is successful, you will need to justify this rate to our finance team. 3 methods of declaring administration support costs are available:' WHERE `id`='29';
UPDATE `question` SET `description`='<p>Subcontracting costs relate to work carried out by third party organisations. These organisations are not part of your project or collaboration. You may subcontract work if you don\'t have the expertise in your consortium. You can also subcontract if it is cheaper than developing your skills in-house.</p>' WHERE `id`='25';
UPDATE `question` SET `description`='Please note that legal or project audit and accountancy fees are not eligible and should not be included as an \'other cost’. Patent filing costs of NEW IP relating to the project are limited to £5,000 for SME applicants only.  Please provide estimates of other costs that do not fit within any other cost headings.' WHERE `id`='34';
UPDATE `question` SET `guidance_answer`='<p>Examples of other costs include:</p><p><strong>Training costs</strong> - these costs are eligible for support if they relate to your project. We may support management training for your project but will not support ongoing training.</p><p><strong>Preparation of technical reports</strong> - for example, if the main aim of your project is standards support or technology transfer. You should show how this is more than you would produce through good project management.</p><p><strong>Market assessment</strong> - we may support of market assessments studies. The study will need to help us understand how your project is a good match for your target market. It could also be eligible if it helps commercialise your product</p></p><strong>Licensing in new technologies</strong> - if new technology makes up a large part of your project, we will expect you to develop that technology. For instance, if the value of the technology is more than &pound;100,000. </p><p><strong>Patent filing costs for NEW IP generated by your project</strong> - these are eligible for SMEs up to a limit of &pound;7,500 per partner. You should not include legal costs relating to the filing or trademark related expenditure.</p><p>Regulatory compliance costs are eligible if necessary to carry out your project.</p>' WHERE `id`='27';
UPDATE `question` SET `description`='<h2 class=\"heading-medium\">Funding rules for this competition</h2> <p>We will fund projects between &pound;200,000 and &pound;1 million. We may consider projects with costs outside of this range. We expect projects to last between 12 and 24 months.</p> <p>Innovate UK aims to optimise the level of funding business receives whilst recognising the importance of the contribution of research organisations to R&amp;D projects. We require, therefore, the following levels of participation:</p> <ul class=\"list-bullet\"> <li>at least 70% of the total eligible project costs are incurred by commercial organisations and</li> <li>a maximum of 30% of total eligible project costs is available to research participants. Where there is more than one research participant, this maximum will be shared between them.</li> </ul>' WHERE `id`='41';

UPDATE `organisation_type` SET `name`='University (HEI)' WHERE `id`='5';
UPDATE `organisation_type` SET `name`='Non profit distributing Research & Technology Organisation (RTO)' WHERE `id`='6';
