ALTER TABLE activity_state MODIFY state ENUM('PENDING', 'REJECTED', 'ACCEPTED', 'OPEN', 'DECIDE_IF_READY_TO_SUBMIT', 'READY_TO_SUBMIT', 'SUBMITTED', 'VERIFIED', 'NOT_VERIFIED', 'ASSIGNED', 'NOT_ASSIGNED') NOT NULL;

INSERT INTO activity_state (activity_type, state) VALUES ('APPLICATION_ASSESSMENT', 'DECIDE_IF_READY_TO_SUBMIT');