INSERT INTO `competition` (`description`,`name`,`max_research_ratio`,`academic_grant_percentage`,`budget_code`,`code`,`paf_code`,`executive_user_id`,`lead_technologist_user_id`,`competition_type_id`,`activity_code`,`innovate_budget`,`multi_stream`,`collaboration_level`,`lead_applicant_type`,`stream_name`,`resubmission`,`setup_complete`,`full_application_finance`,`assessor_count`,`assessor_pay`,`template`,`use_resubmission_question`) VALUES (NULL,'Template for the Sector competition type',0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,'1',0,0.00,'1','1');
SET @sector_template_id=LAST_INSERT_ID();
UPDATE competition_type SET template_competition_id = @sector_template_id WHERE name = 'Sector';

INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES ('These sections give important background information on the project. They do not need scoring.','Please provide Innovate UK with information about your project. These sections are not scored but will provide background to the project.',1,'Project details',1,@sector_template_id,NULL,0,'GENERAL');
SET @s_project_details=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES ('Each question should be given a score out of 10. Written feedback should also be given.','These are the 10 questions which will be marked by assessors. Each question is marked out of 10 points.',1,'Application questions',2,@sector_template_id,NULL,0,'GENERAL');
SET @s_application_questions=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES ('Each partner is required to submit their own project finances and funding rates. The overall project costs for all partners can be seen in the Finances overview section','Each partner is required to submit their own project finances and funding rates. The overall project costs for all partners can be seen in the Finances overview section',1,'Finances',3,@sector_template_id,NULL,0,'GENERAL');
SET @s_finances=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Your finances',4,@sector_template_id,@s_finances,1,'FINANCE');
SET @s_your_finances=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,1,'Your project costs',5,@sector_template_id,@s_your_finances,1,'PROJECT_COST_FINANCES');
SET @s_your_project_costs=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,1,'Your organisation',6,@sector_template_id,@s_your_finances,1,'ORGANISATION_FINANCES');
SET @s_your_organisation=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,1,'Your funding',7,@sector_template_id,@s_your_finances,1,'FUNDING_FINANCES');
SET @s_your_funding=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Labour',1,@sector_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_labour=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Overhead costs',2,@sector_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_overheads=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Materials',3,@sector_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_materials=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Capital usage',4,@sector_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_capital_usage=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Subcontracting costs',5,@sector_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_subcontracting=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Travel and subsistence',6,@sector_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_travel=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,NULL,0,'Other Costs',7,@sector_template_id,@s_your_project_costs,0,'GENERAL');
SET @s_other_costs=LAST_INSERT_ID();
INSERT INTO `section` (`assessor_guidance_description`,`description`,`display_in_assessment_application_summary`,`name`,`priority`,`competition_id`,`parent_section_id`,`question_group`,`section_type`) VALUES (NULL,'This is the financial overview of all partners in this collaboration. Each partner should submit their organisation\'s finances in the \'your finances\' section. All partners will see this level of detail.',1,'Finances overview',8,@sector_template_id,@s_finances,1,'OVERVIEW_FINANCES');
SET @s_finance_overview=LAST_INSERT_ID();


-- Project details questions
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'Enter the full title of the project',1,0,'Application details','Application details',1,NULL,@sector_template_id,@s_project_details,NULL,'GENERAL');
SET @q_application_details=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,5,@sector_template_id,1,'Application details',NULL,NULL,0,@q_application_details,'APPLICATION',1);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide a short summary of your project. Make sure you include what is innovative about it.',1,0,'Project summary','Project summary',2,NULL,@sector_template_id,@s_project_details,NULL,'GENERAL');
SET @q_project_summary=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@sector_template_id,1,'Project summary','What should I include in the project summary?','<p>We will not score this summary, but it will give the assessors a useful introduction to your project. It should provide a clear overview of the whole project, including:</p> <ul class=\"list-bullet\">         <li>your vision for the project</li><li>key objectives</li><li>main areas of focus</li><li>details of how it is innovative</li></ul>',0,@q_project_summary,'APPLICATION',1);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide a brief description of your project. If your application is successful, we will publish this description. This question is mandatory but we will not assess this content as part of your application.',1,0,'Public description','Public description',3,NULL,@sector_template_id,@s_project_details,NULL,'GENERAL');
SET @q_public_description=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@sector_template_id,1,'Public description','What should I include in the project public description?','<p>Innovate UK publishes information about projects we have funded. This is in line with government practice on openness and transparency of public-funded activities.</p><p>Describe your project in a way that will be easy for a non-specialist to understand. Don\'t include any information that is confidential, for example, intellectual property or patent details.</p> ',0,@q_public_description,'APPLICATION',1);

INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'If your application doesn\'t align with the scope, we will reject it.',1,0,'How does your project align with the scope of this competition?','Scope',4,NULL,@sector_template_id,@s_project_details,NULL,'GENERAL');
SET @q_scope=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (400,2,@sector_template_id,1,'How does your project align with the scope of this competition?','What should I include in the project scope?','<p>It is important that you read the following guidance.</p><p>To show how your project aligns with the scope of this competition, you need to:</p><ul class=\"list-bullet\">         <li>read the competition brief in full</li><li>understand the background, challenge and scope of the competition</li><li>address the research objectives in your application</li><li>match your project\'s objectives and activities to these</li></ul> <p>Once you have submitted your application, you should not change this section unless:</p><ul class=\"list-bullet\">         <li>we ask you to provide more information</li><li>we ask you to make it clearer</li></ul> ',0,@q_scope,'APPLICATION',1);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,21,@sector_template_id,0,'Please select the research category for this project',NULL,NULL,0,@q_scope,'ASSESSMENT',1);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,22,@sector_template_id,0,'Is the application in scope?',NULL,NULL,0,@q_scope,'ASSESSMENT',1);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (100,2,@sector_template_id,0,'Feedback','Guidance for assessing scope','Your answer should be based upon the following:',0,@q_scope,'ASSESSMENT',1);
SET @f_scope=LAST_INSERT_ID();
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_scope,'NO','One or more of the above requirements have not been satisfied.',0);
INSERT INTO `guidance_row` (`form_input_id`,`subject`,`justification`,`priority`) VALUES (@f_scope,'YES','The application contains the following:\nIs the consortia business led?\nAre there two or more partners to the collaboration?\nDoes it meet the scope of the competition as defined in the competition brief?',1);


-- Application questions
-- ACTUAL TEMPLATE QUESTIONS

INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (760,'1','','1','0','What is the business need, technological challenge or market opportunity behind your innovation?','Need or challenge',5,'1',15,400,10,'GENERAL');
SET @q_need_or_challenge=LAST_INSERT_ID();
INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (761,'1','','1','0','What approach will you take and where will the focus of the innovation be?','Approach and innovation',6,'2',15,400,10,'GENERAL');
SET @q_approach_and_innovation=LAST_INSERT_ID();
INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (762,'1','','1','0','Who is in the project team and what are their roles?','Team and resources',7,'3',15,400,10,'GENERAL');
SET @q_team_and_resources=LAST_INSERT_ID();
INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (763,'1','','1','0','What does the market you are targeting look like?','Market awareness',8,'4',15,400,10,'GENERAL');
SET @q_market_awareness=LAST_INSERT_ID();
INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (764,'1','','1','0','How are you going to grow your business and increase your productivity into the long term as a result of the project?','Outcomes and route to market',9,'5',15,400,10,'GENERAL');
SET @q_outcomes=LAST_INSERT_ID();
INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (765,'1','','1','0','What impact might this project have outside the project team?','Wider impacts',10,'6',15,400,10,'GENERAL');
SET @q_wider_impact=LAST_INSERT_ID();
INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (766,'1','','1','0','How will you manage the project effectively?','Project management',11,'7',15,400,10,'GENERAL');
SET @q_project_management=LAST_INSERT_ID();
INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (767,'1','','1','0','What are the main risks for this project?','Risks',12,'8',15,400,10,'GENERAL');
SET @q_risks=LAST_INSERT_ID();
INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (768,'1','','1','0','Describe the impact that an injection of public funding would have on this project.','Additionality',13,'9',15,400,10,'GENERAL');
SET @q_additionality=LAST_INSERT_ID();
INSERT INTO `question` (`id`,`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (769,'1',' ','1','0','How much will the project cost and how does it represent value for money for the team and the taxpayer?','Costs and value for money',14,'10',15,400,10,'GENERAL');
SET @q_costs_and_value=LAST_INSERT_ID();

-- No questions for finances section
-- No questions for your finances section

-- Your project costs question
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'Only your organisation can see this level of detail. All members of your organisation can access and edit your finances. We recommend assigning completion of your finances to one member of your team. <a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\" rel=\"external\">Find out which project costs are eligible.</a> ',1,1,'Provide the project costs for \'{organisationName}\'','Project finances',15,NULL,@sector_template_id,@s_your_project_costs,NULL,'GENERAL');
SET @q_your_project_costs=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,15,@sector_template_id,1,NULL,'','',0,@q_your_project_costs,'APPLICATION',1);

-- Your organisation question
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'To determine the level of funding you are eligible to receive please provide your business size using the <a href=\"http://ec.europa.eu/growth/smes/business-friendly-environment/sme-definition/index_en.htm\" target=\"_blank\" rel=\"external\">EU Definition</a> for guidance.',1,1,'Organisation size','Business size',18,NULL,@sector_template_id,@s_your_organisation,NULL,'GENERAL');
SET @q_your_organisation=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,19,@sector_template_id,1,'Organisation Size',NULL,NULL,0,@q_your_organisation,'APPLICATION',1);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,4,@sector_template_id,1,'Appendix','What should I include in the appendix?','<p>You may include an appendix of additional information to support the technical approach the project will undertake.</p><p>You may include, for example, a Gantt chart or project management structure.</p><p>The appendix should:</p><ul class=\"list-bullet\"><li>be in a portable document format (.pdf)</li><li>be readable with 100% magnification</li><li>contain your application number and project title at the top</li><li>not be any longer than 6 sides of A4. Longer appendices will only have the first 6 pages assessed</li><li>be less than 1mb in size</li></ul>',1,@q_your_organisation,'APPLICATION',0);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,24,@sector_template_id,0,'Turnover (£)','Your turnover from the last financial year.','',1,@q_your_organisation,'APPLICATION',1);
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,25,@sector_template_id,0,'Full time employees','Number of full time employees at your organisation.','',2,@q_your_organisation,'APPLICATION',1);

-- Your funding question
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'Please tell us if you have ever applied for or received any other public sector funding for this project. You should also include details of any offers of funding you\'ve received.',1,1,'Other funding','Other funding',20,NULL,@sector_template_id,@s_your_funding,NULL,'COST');
SET @q_other_funding=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,17,@sector_template_id,1,'Other funding','What should I include in the other public funding section?','<p>You must provide details of other public funding that you are currently applying for (or have already applied for) in relation to this project. You do not need to include completed grants that were used to reach this point in the development process. This information is important as other public sector support counts as part of the funding you can receive for your project.</p>',0,@q_other_funding,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'Please enter the funding level that you would like to apply for in this application',1,1,'Funding level','Funding level',19,NULL,@sector_template_id,@s_your_funding,NULL,'GENERAL');
SET @q_funding_level=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,7,@sector_template_id,1,'Please enter the grant % you wish to claim for this project','What funding level should I enter?','<p>For a business or academic organisation, you can apply for any funding percentage between 0% and the maximum allowable for your organisation size. For other organisation types, you can apply for any funding percentage between 0% and 100%. The amount you apply for must reflect other funding you may have received. It must also be within participation levels which you can review on the Finances Overview page.</p>',0,@q_funding_level,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,NULL,1,1,'Upload a pdf copy of the Je-S output confirming a status of \'With Council\'','Je-s Output',20,NULL,@sector_template_id,@s_your_funding,NULL,'GENERAL');
SET @q_jes_output=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,20,@sector_template_id,1,'Upload a pdf copy of the Je-S output form once you have a status of \'With Council\'.','How do I create my Je-S output?','<p>You should include only supporting information in the appendix. You shouldn’t use it to provide your responses to the question.</p><p>Guidance for this section needs to be created</p>',0,@q_jes_output,'APPLICATION',1);

-- Labour question
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You may claim the labour costs of all individuals you have working on your project.</p> <p> If your application is awarded funding, you will need to account for all your labour costs as they occur. For example, you should keep timesheets and payroll records. These should show the actual hours worked by individuals and paid by the organisation.</p>',0,1,NULL,NULL,1,NULL,@sector_template_id,@s_labour,NULL,'GENERAL');
SET @q_labour_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@sector_template_id,1,NULL,'Labour costs guidance','<p>You can include the following labour costs, based upon your PAYE records:</p><ul class=\"list-bullet\"><li>gross salary</li><li>National Insurance</li><li>company pension contribution</li><li>life insurance</li><li>other non-discretionary package costs.</li></ul><p>You can\'t include:</p><ul class=\"list-bullet\"><li>discretionary bonuses</li><li>performance related payments of any kind</li></ul><p>You may include the total number of working days for staff but do not include:</p><ul class=\"list-bullet\"><li>sick days</li><li>waiting time</li><li>training days</li><li>non-productive time</li></ul><p>Enter the total number of working days in the year. List the total days worked by all categories of staff on your project. Describe their role.</p><p>We will review the total amount of time and cost of labour before we approve your application. The terms and conditions of the grant include compliance with these points.</p>',0,@q_labour_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,1,1,'Labour',NULL,2,NULL,@sector_template_id,@s_labour,NULL,'COST');
SET @q_labour_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,8,@sector_template_id,1,'Labour',NULL,NULL,0,@q_labour_cost,'APPLICATION',1);

-- Overheads question
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,0,1,NULL,NULL,1,NULL,@sector_template_id,@s_overheads,NULL,'GENERAL');
SET @q_overhead_empty=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@sector_template_id,1,NULL,NULL,NULL,0,@q_overhead_empty,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You may incur indirect support staff costs linked with your administrative work for the project. To be eligible, these costs should be directly attributable and incremental to the project. Indirect costs associated with commercial activities are not eligible and must not be included. For further information on which costs are eligible please read our <a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\">project costs guidance</a>.</p>',1,1,'Overheads','Indirect costs',2,NULL,@sector_template_id,@s_overheads,NULL,'GENERAL');
SET @q_overhead=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,9,@sector_template_id,1,'Overheads',NULL,NULL,0,@q_overhead,'APPLICATION',1);

-- Materials question
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You can claim the costs of materials used on your project providing:</p><ul class=\"list-bullet\"><li>they are not already purchased or included in the administration support costs</li><li>they are purchased from third parties</li><li>they won’t have a residual/resale value at the end of your project. If they do you can claim the costs minus this value</li></ul><p><a href=\"https://www.gov.uk/government/publications/innovate-uk-completing-your-application-project-costs-guidance\" rel=\"external\">Please refer to our guide to project costs for further information.</a></p>',0,1,NULL,NULL,1,NULL,@sector_template_id,@s_materials,NULL,'GENERAL');
SET @q_materials_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@sector_template_id,1,NULL,'Materials costs guidance','<p>Materials supplied by associated companies or project partners should be charged at cost.</p><p>Software that you have purchased specifically for use during your project may be included. If you already own the software then only additional costs which are incurred and paid during your project, will be eligible. For example, installation, training or customisation.</p><p>Material costs must be itemised to justify that they are eligible.</p>',0,@q_materials_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide a breakdown of the materials you expect to use during the project',1,1,'Materials','Materials',2,NULL,@sector_template_id,@s_materials,NULL,'COST');
SET @q_materials_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,10,@sector_template_id,1,'Materials',NULL,NULL,0,@q_materials_cost,'APPLICATION',1);

-- Capital usage
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You should provide details of capital equipment and tools you will buy for, or use on, your project.</p>',0,1,NULL,NULL,1,NULL,@sector_template_id,@s_capital_usage,NULL,'GENERAL');
SET @q_capital_usage_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@sector_template_id,1,NULL,'Capital usage guidance','<p>You will need to calculate a ‘usage’ value for each item. You can do this by deducting its expected value from its original price at the end of your project. If you owned the equipment before the project started then you should use its Net Present Value.</p><p>This value is then multiplied by the amount, in percentages, that is used during the project. This final value represents the eligible cost to your project.</p>',0,@q_capital_usage_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide a breakdown of the capital items you will buy and/or use for the project.',1,1,'Capital Usage','Capital items',2,NULL,@sector_template_id,@s_capital_usage,NULL,'COST');
SET @q_capital_usage_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,11,@sector_template_id,1,'Capital Usage',NULL,NULL,0,@q_capital_usage_cost,'APPLICATION',1);

-- Subcontracting costs
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You may subcontract work if you don’t have the expertise in your consortium. You can also subcontract if it is cheaper than developing your skills in-house.</p>',0,1,NULL,NULL,1,NULL,@sector_template_id,@s_subcontracting,NULL,'GENERAL');
SET @q_subcontracting_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@sector_template_id,1,NULL,'Subcontracting costs guidance','<p>Subcontracting costs relate to work carried out by third party organisations. These organisations are not part of your project or collaboration.</p><p>Subcontracting is eligible providing it’s justified as to why the work cannot be performed by a project partner.</p><p>Where possible you should select a UK based contractor. You should name the subcontractor (where known) and describe what they will be doing. You should also state where the work will be undertaken. We will look at the size of this contribution when assessing your eligibility and level of support.</p>',0,@q_subcontracting_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please provide details of any work that you expect to subcontract for your project.',1,1,'Sub-contracting costs','Sub-contracts',2,NULL,@sector_template_id,@s_subcontracting,NULL,'COST');
SET @q_subcontracting_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,12,@sector_template_id,1,'Sub-contracting costs',NULL,NULL,0,@q_subcontracting_cost,'APPLICATION',1);

-- Travel costs
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>You should include travel and subsistence costs that relate only to this project. </p>',0,1,NULL,NULL,1,NULL,@sector_template_id,@s_travel,NULL,'GENERAL');
SET @q_travel_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@sector_template_id,1,NULL,NULL,NULL,0,@q_travel_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,1,1,'Travel and subsistence',NULL,2,NULL,@sector_template_id,@s_travel,NULL,'COST');
SET @q_travel_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,13,@sector_template_id,1,'Travel and subsistence',NULL,NULL,0,@q_travel_cost,'APPLICATION',1);

-- Other costs
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'<p>Please tell us if you have applied for or received any other public sector funding for this project. Any other funding received will need to be deducted from the total value of any funding you are claiming for this project.</p>',0,1,NULL,NULL,1,NULL,@sector_template_id,@s_other_costs,NULL,'GENERAL');
SET @q_other_content=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@sector_template_id,1,NULL,'Other costs guidance','<p>Examples of other costs include:</p><p><strong>Training costs:</strong> these costs are eligible for support if they relate to your project. We may support management training for your project but will not support ongoing training.</p><p><strong>Preparation of technical reports:</strong> if, for example, the main aim of your project is standard support or technology transfer. You should show how this is more than you would produce through good project management.</p><p><strong>Market assessment:</strong> we may support market assessments studies. The study will need to help us understand how your project is a good match for your target market. It could also be eligible if it helps commercialise your product.</p><p><strong>Licensing in new technologies:</strong> if new technology makes up a large part of your project, we will expect you to develop that technology. For instance, if the value of the technology is more than &pound;100,000.</p><p><strong>Patent filing costs for NEW IP generated by your project:</strong> these are eligible for SMEs up to a limit of &pound;7,500 per partner. You should not include legal costs relating to the filing or trademark related expenditure.</p><p>Regulatory compliance costs are eligible if necessary to carry out your project.</p>',0,@q_other_content,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,'Please note that legal or project audit and accountancy fees are not eligible and should not be included as an \'other cost’. Patent filing costs of NEW IP relating to the project are limited to £7,500 for SME applicants only.  Please provide estimates of other costs that do not fit within any other cost headings.',1,1,'Other costs','Other costs',2,NULL,@sector_template_id,@s_other_costs,NULL,'COST');
SET @q_other_cost=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,14,@sector_template_id,1,'Other costs',NULL,NULL,0,@q_other_cost,'APPLICATION',1);


--Finance overview questions
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (1,NULL,0,0,'FINANCE_SUMMARY_INDICATOR_STRING',NULL,17,NULL,@sector_template_id,@s_finance_overview,NULL,'GENERAL');
SET @q_finance_summary_indicator=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,16,@sector_template_id,1,NULL,NULL,NULL,0,@q_finance_summary_indicator,'APPLICATION',1);
INSERT INTO `question` (`assign_enabled`,`description`,`mark_as_completed_enabled`,`multiple_statuses`,`name`,`short_name`,`priority`,`question_number`,`competition_id`,`section_id`,`assessor_maximum_score`,`question_type`) VALUES (0,'<h2 class=\"heading-medium\">Funding rules for this competition</h2><p>We will fund projects between &pound;500,000 and &pound;1.5 million. We may consider projects with costs outside of this range. We expect projects to last between 12 and 36 months.</p><p>Innovate UK\'s aim is to optimise the level of funding businesses receive. We also recognise the importance of research organisations\' contribution to R&amp;D projects. Therefore we require the following levels of participation:</p><ul class=\"list-bullet\"> <li>at least 70% of the total eligible project costs are incurred by commercial organisations and</li> <li>a maximum of 30% of total eligible project costs are available to research participants. Where there is more than one research participant, this maximum will be shared between them.</li></ul>',0,0,NULL,NULL,16,NULL,@sector_template_id,@s_finance_overview,NULL,'GENERAL');
SET @q_funding_rules=LAST_INSERT_ID();
INSERT INTO `form_input` (`word_count`,`form_input_type_id`,`competition_id`,`included_in_application_summary`,`description`,`guidance_title`,`guidance_answer`,`priority`,`question_id`,`scope`,`active`) VALUES (NULL,6,@sector_template_id,1,NULL,NULL,NULL,0,@q_funding_rules,'APPLICATION',1);

