ALTER TABLE `ifs`.`thread` CHANGE COLUMN `id` `id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ifs`.`thread` CHANGE COLUMN `created_on` `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `ifs`.`post` CHANGE COLUMN `id` `id` BIGINT(20) NOT NULL AUTO_INCREMENT;
ALTER TABLE `ifs`.`post` CHANGE COLUMN `created_on` `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
