FROM debian:jessie-slim

LABEL maintainer "infrastructure@orangebus.co.uk"

ENV HTTP_PORT=9080 \
    HTTPS_PORT=9443 \
    WEBAPPS_PROTO=ajp \
    SP_DOMAIN=ifs.local-dev \
    IDP_DOMAIN=idp \
    IDP_PORT=8443 \
    TRUSTED_IP=@auth_service_trusted_ip@ \
    PROXY_CERTIFICATE=@auth_sp_proxy_certificate@ \
    PROXY_KEY=@auth_sp_proxy_key@ \
    PROXY_CA_CERTIFICATE=@auth_sp_proxy_ca_certificate@

WORKDIR /usr/local/bin

COPY files /usr/local/files/

RUN apt-get update --fix-missing && \

# install apache and shibboleth sp module \
  apt-get -y install apache2 libapache2-modsecurity libapache2-mod-shib2 && \
  apt-get autoclean && apt-get --purge -y autoremove && rm -rf /var/lib/apt/lists/* && \

# put certificates in place \
  mkdir /etc/apache2/certs && \
  echo "$PROXY_CERTIFICATE" > /etc/apache2/certs/server.crt && \
  echo "$PROXY_KEY" > /etc/apache2/certs/server.key && \
  echo "$PROXY_CA_CERTIFICATE" > /etc/apache2/certs/DigiCertCA.crt && \

# configure apache \
  rm -f /etc/apache2/sites-enabled/000-default.conf && \
  a2enmod shib2 socache_shmcb slotmem_shm ssl proxy_balancer status lbmethod_byrequests proxy_ajp proxy headers rewrite proxy_http reqtimeout && \
  sed -i -e "s/Listen 80/Listen $HTTP_PORT/" -e "s/Listen 443/Listen $HTTPS_PORT/" /etc/apache2/ports.conf && \
  mv /usr/local/files/apache2/z-defaults.conf /etc/apache2/conf-available/ && a2enconf z-defaults.conf && \

# put holding pages in place. A dedicated container is probably a better idea \
  mv /usr/local/files/apache2/locking /var/www/html/ && \
  mv /usr/local/files/scripts/* /usr/local/bin/ && \

# configure ifs virtual host \
  mv "/usr/local/files/apache2/ifs-services.conf.$WEBAPPS_PROTO" /etc/apache2/sites-available/ifs-services.conf && a2ensite ifs-services && \

# put static files in place \
  mkdir -p /var/www/html/files && \
  mv /usr/local/files/files/* /var/www/html/files/ && \

# run apache as its own user \
  mkdir -p /var/run/apache2 && \
  chown -R www-data:0 /etc/apache2 /var/cache/apache2 /run/lock/apache2 /var/run/apache2 /var/www/html/ && \
  chmod -R u=rwX,g=rwX,o= /etc/apache2 /var/cache/apache2 /run/lock/apache2 /var/www/html/ && \

# configure shibboleth module
  mv /usr/local/files/sp/* /etc/shibboleth/ && \
  mkdir /var/www/html/Logout &&  mv /usr/local/files/apache2/index.html /var/www/html/Logout/ && \
  mkdir /var/run/shibboleth && \
  sed -i "s#\/\/ifs.local-dev#\/\/$SP_DOMAIN#g" /etc/shibboleth/* /var/www/html/Logout/index.html && \
  sed -i "s/idp:8443/$IDP_PORT/g" /etc/shibboleth/metadata.xml && \
  sed -i "s#\/\/idp#\/\/$IDP_DOMAIN#g" /etc/shibboleth/shibboleth2.xml /etc/shibboleth/metadata.xml /var/www/html/Logout/index.html && \
  sed -i "/^log4j\.appender/d" /etc/shibboleth/shibd.logger && cat /etc/shibboleth/appenders.shibd.logger >> /etc/shibboleth/shibd.logger &&  rm /etc/shibboleth/appenders.shibd.logger && \

# run shibboleth sp as its own user (same as apache)
  mkdir -p /var/run/shibboleth && \
  chown -R www-data:0 /etc/shibboleth /var/www/html/Logout /var/run/shibboleth && \
  chmod -R u=rwX,g=rwX,o= /etc/shibboleth /var/www/html/Logout /var/run/shibboleth && \

  rm -Rf /usr/local/files/

ENTRYPOINT [ "run-shibboleth-sp.sh" ]

HEALTHCHECK --interval=15s --timeout=8s \
  CMD curl --connect-timeout 5 -m 5 -k -f https://localhost:$HTTPS_PORT/Shibboleth.sso/Metadata || exit 1
