FROM debian:jessie-slim

LABEL maintainer "infrastructure@orangebus.co.uk"

ENV HTTP_PORT=9180 \
    HTTPS_PORT=9143 \
    WEBAPPS_PROTO=ajp \
    MPM_STARTSERVERS=2 \
    MPM_MINSPARETHREADS=25 \
    MPM_MAXSPARETHREADS=75 \
    MPM_THREADLIMIT=64 \
    MPM_THREADSPERCHILD=25 \
    MPM_MAXREQUESTWORKERS=150 \
    MPM_MAXCONNECTIONSPERCHILD=0 \
    SP_DOMAIN=ifs.local-dev \
    IDP_DOMAIN=idp \
    IDP_PORT=8443 \
    TRUSTED_IP="@auth_service_trusted_ip@" \
    SP_PROXY_KEY="@auth_sp_proxy_key@" \
    SP_PROXY_CERTIFICATE="@auth_sp_proxy_certificate@" \
    SP_PROXY_CACERTIFICATE="@auth_sp_proxy_cacertificate@" \
    IDP_SIGNING_CERTIFICATE="@auth_idp_signing_certificate@" \
    IDP_ENCRYPTION_CERTIFICATE="@auth_idp_encryption_certificate@" \
    MEMCACHE_ENDPOINT=

WORKDIR /usr/local/bin

COPY files /usr/local/files/

RUN apt-get update --fix-missing && \

# install apache and shibboleth sp module \
  apt-get -y install curl apache2 libapache2-modsecurity libapache2-mod-shib2 && \
  apt-get autoclean && apt-get --purge -y autoremove && rm -rf /var/lib/apt/lists/* && \

# directory for certificates, added in entrypoint \
  mkdir /etc/apache2/certs && \

# configure apache \
  rm -f /etc/apache2/sites-enabled/000-default.conf && \
  a2enmod shib2 socache_shmcb ssl status proxy_ajp proxy headers rewrite proxy_http reqtimeout && \
  a2disconf other-vhosts-access-log && \
  mv /usr/local/files/apache2/mpm_event.conf /etc/apache2/mods-available/ && \
  sed -i -e 's/Listen 80/Listen ${HTTP_PORT}/' -e 's/Listen 443/Listen ${HTTPS_PORT}/' /etc/apache2/ports.conf && \
  mv /usr/local/files/apache2/z-defaults.conf /etc/apache2/conf-available/ && a2enconf z-defaults.conf && \

# put holding pages in place. A dedicated container is probably a better idea \
  mv /usr/local/files/apache2/locking /var/www/html/ && \
  mv /usr/local/files/scripts/* /usr/local/bin/ && \

# configure ifs virtual host \
  mv "/usr/local/files/apache2/ifs-services.conf.$WEBAPPS_PROTO" /etc/apache2/sites-available/ifs-services.conf && a2ensite ifs-services && \

# put static files in place \
  mkdir -p /var/www/html/files && \
  mv /usr/local/files/files/* /var/www/html/files/ && \

# run apache as its own user \
  mkdir -p /var/run/apache2 && \
  chown -R www-data:0 /etc/apache2 /var/cache/apache2 /run/lock/apache2 /var/run/apache2 /var/cache/modsecurity /var/www/html/ && \
  chmod -R u=rwX,g=rwX,o= /etc/apache2 /var/cache/apache2 /run/lock/apache2 /var/run/apache2 /var/cache/modsecurity /var/www/html/ && \

# configure shibboleth module \
  mv /usr/local/files/sp/* /etc/shibboleth/ && \
  mkdir /var/www/html/Logout &&  mv /usr/local/files/apache2/index.html /var/www/html/Logout/ && \
  sed -i "/^log4j\.appender/d" /etc/shibboleth/shibd.logger && cat /etc/shibboleth/appenders.shibd.logger >> /etc/shibboleth/shibd.logger &&  rm /etc/shibboleth/appenders.shibd.logger && \
# see also certificates and substitutions in entrypoint script \

# run shibboleth sp as its own user (same as apache) \
  mkdir -p /var/run/shibboleth && \
  chown -R www-data:0 /etc/shibboleth /var/cache/shibboleth /var/www/html/Logout /var/run/shibboleth && \
  chmod -R u=rwX,g=rwX,o= /etc/shibboleth /var/cache/shibboleth /var/www/html/Logout /var/run/shibboleth && \

  rm -Rf /usr/local/files/

#USER www-data
ENTRYPOINT [ "run-shibboleth-sp.sh" ]
