*** Variables ***
${BROWSER}        Firefox
${SERVER_BASE}    localhost:8085
${SERVER_BASE}    localhost
${PROTOCOL}       http://
${SERVER}         ${PROTOCOL}${SERVER_BASE}
${LOGIN_URL}      ${SERVER}/login
${DASHBOARD_URL}    ${SERVER}/applicant/dashboard
${SCOPE_SECTION_URL}    ${SERVER}/application-form/1/section/2/
${YOUR_BUSINESS_URL}    ${SERVER}/application-form/1/section/3/
${PROJECT_URL}    ${SERVER}/application-form/1/section/4/
${FUNDING_URL}    ${SERVER}/application-form/1/section/5/
${FINANCES}       ${SERVER}/application-form/1/section/6/
${SUMMARY_URL}    ${SERVER}/application/1/summary
${APPLICATION_URL}    ${SERVER}/application-form/1/section/1/
${SUMMARY_URL}    ${SERVER}/application/1/summary
${QUESTION11_URL}    ${SERVER}/application-form/1/section/1/#question-11
${FINANCES}       ${SERVER}/application-form/1/section/6/
${YOUR_FINANCES}    ${SERVER}/application-form/1/section/7/
${APPLICATION_OVERVIEW_URL}    ${SERVER}/application/1
${APPLICATION_SUBMITTED_URL}    ${SERVER}/application/1/submit
${APPLICATION_DETAILS_URL}    ${SERVER}/application-form/1/section/1/#question-9
${APPLICATION_COLLABORATION_QUESTION}    ${SERVER}/application-form/1/section/2/#question-13
${applicant_dashboard_url}    ${SERVER}/applicant/dashboard
${assessor_dashboard_url}    ${SERVER}/assessor/dashboard
${COMPETITION_DETAILS_URL}    ${SERVER}/competition/1/details/
${LOG_OUT}        ${SERVER}/logout
${APPLICATION_QUESTIONS_SECTION_URL}    http://localhost/application-form/1/section/2/
${SEARCH_COMPANYHOUSE_URL}    ${SERVER}/application/create/find-business
