*** Variables ***
&{lead_applicant_credentials}             email=steve.smith@empire.com    password=Passw0rd1357
&{lead_applicant2_credentials}            email=jesse.edwards@example.com  password=Passw0rd1357
&{collaborator1_credentials}              email=jessica.doe@ludlow.co.uk    password=Passw0rd1357
&{collaborator2_credentials}              email=pete.tom@egg.com    password=Passw0rd1357
&{worth_test_credentials}                 email=${test_mailbox_one}+submit@gmail.com    password=Passw0rd1357
&{Comp_admin1_credentials}                email=john.doe@innovateuk.test    password=Passw0rd1357
&{successful_applicant_credentials}       email=${test_mailbox_one}+fundsuccess@gmail.com    password=Passw0rd1357
&{successful_released_credentials}        email=${test_mailbox_two}+releasefeedback@gmail.com    password=Passw0rd1357
&{unsuccessful_applicant_credentials}     email=${test_mailbox_two}+fundfailure@gmail.com    password=Passw0rd1357
&{unsuccessful_released_credentials}      email=james.lewis@example.com    password=Passw0rd1357
&{assessor_credentials}                   email=paul.plum@gmail.com    password=Passw0rd1357
&{assessor2_credentials}                  email=felix.wilson@gmail.com    password=Passw0rd1357
&{assessor_bob_credentials}               email=bob.malone@gmail.com    password=Passw0rd1357
&{existing_assessor1_credentials}         email=${test_mailbox_one}+jeremy.alufson@gmail.com    password=Passw0rd1357
&{nonregistered_assessor2_credentials}    email=${test_mailbox_one}+david.peters@gmail.com    password=Passw0rd1357
&{nonregistered_assessor3_credentials}    email=${test_mailbox_one}+thomas.fister@gmail.com    password=Passw0rd1357123
&{internal_finance_credentials}           email=lee.bowman@innovateuk.test    password=Passw0rd1357
&{innovation_lead_one}                    email=ian.cooper@innovateuk.test    password=Passw0rd1357
&{innovation_lead_two}                    email=peter.freeman@innovateuk.test    password=Passw0rd1357
&{stakeholder_user}                       email=Rayon.Kevin@gmail.com    password=Passw0rd1357
&{Multiple_user_credentials}              email=jo.peters@ntag.example.com    password=Passw0rd1357
&{Ineligible_user}                        email=nancy.peterson@gmail.com    password=Passw0rd1357
&{support_user_credentials}               email=support@innovateuk.test    password=Passw0rd1357
&{ifs_admin_user_credentials}             email=arden.pimenta@innovateuk.test    password=Passw0rd1357
&{Assessor_e2e}                           email=${test_mailbox_one}+AJE2E@gmail.com    password=Passw0rd1357123
&{lead_applicant_alternative_user_credentials}    email=${test_mailbox_one}+mario@gmail.com    password=Passw0rd1357
&{collaborator1_alternative_user_credentials}     email=kevin.summers@ludlow.co.uk    password=Passw0rd1357
&{collaborator2_alternative_user_credentials}     email=casey.evans@egg.com    password=Passw0rd1357
&{RTO_lead_applicant_credentials}                 email=dave.adams@gmail.com   password=Passw0rd1357
&{Research_lead_applicant_credentials}            email=heather.ross@example.com   password=Passw0rd1357
&{PublicSector_lead_applicant_credentials}        email=becky.mason@gmail.com   password=Passw0rd1357
&{monitoring_officer_one_credentials}             email=orville.gibbs@gmail.com    password=Passw0rd1357
&{monitoring_officer_two_credentials}             email=nilesh.patti@gmail.com    password=Passw0rd1357
&{assessor_stakeholder_credentials}               email=blake.wood@gmail.com    password=Passw0rd1357
&{applicant_stakeholder_credentials}              email=gene.bowman@jetpulse.example.com    password=Passw0rd1357
&{triple_user_credentials}                        email=carolyn.reed@example.com    password=Passw0rd1357
&{PS_EF_Application_Partner_Email_credentials}    email= ${test_mailbox_one}+karen@gmail.com   password=Passw0rd1357
&{troy_ward_crendentials}                         email=troy.ward@gmail.com  password=Passw0rd1357
&{becky_mason_credentials}                        email=becky.mason@gmail.com  password=Passw0rd1357
&{abby_gallagher_credentials}                     email=abby.gallagher@example.com	password=Passw0rd1357
##### DO NOT USE THIS USER FOR ANYTHING ELSE ######
&{terms_and_conditions_login_credentials}         email=laura.jackson@example.com  password=Passw0rd1357
###################################################