*** Variables ***
&{lead_applicant_credentials}             email=steve.smith@empire.com    password=Passw0rd
&{collaborator1_credentials}              email=jessica.doe@ludlow.co.uk    password=Passw0rd
&{collaborator2_credentials}              email=pete.tom@egg.com    password=Passw0rd
&{worth_test_credentials}                 email=${test_mailbox_one}+submit@gmail.com    password=Passw0rd
&{Comp_admin1_credentials}                email=john.doe@innovateuk.test    password=Passw0rd
&{successful_applicant_credentials}       email=worth.email.test+fundsuccess@gmail.com    password=Passw0rd
&{unsuccessful_applicant_credentials}     email=worth.email.test.two+fundfailure@gmail.com    password=Passw0rd
&{assessor_credentials}                   email=paul.plum@gmail.com    password=Passw0rd
&{assessor2_credentials}                  email=felix.wilson@gmail.com    password=Passw0rd
&{existing_assessor1_credentials}         email=worth.email.test+assessor1@gmail.com    password=Passw0rd
&{nonregistered_assessor2_credentials}    email=worth.email.test+assessor2@gmail.com    password=Passw0rd
&{nonregistered_assessor3_credentials}    email=worth.email.test+assessor3@gmail.com    password=Passw0rd123
&{internal_finance_credentials}           email=lee.bowman@innovateuk.test    password=Passw0rd
&{comp_tech_one}                          email=ian.cooper@innovateuk.test    password=Passw0rd
&{comp_tect_two}                          email=peter.freeman@innovateuk.test    password=Passw0rd
