## Originally sourced from https://github.com/primait/docker-proxysql/blob/master/1.3/Dockerfile.  Maintained locally to offer more security.
FROM debian:jessie

MAINTAINER Duncan Watson <duncan@hiveit.co.uk>

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/sysown/proxysql/releases/download/1.3.0f/proxysql_1.3.0f-debian8_amd64.deb -O /opt/proxysql_1.3.0f-debian8_amd64.deb && \
    dpkg -i /opt/proxysql_1.3.0f-debian8_amd64.deb && \
    rm -f /opt/proxysql_1.3.0f-debian8_amd64.deb && \
    rm -rf /var/lib/apt/lists/*

COPY proxysql.cfg /etc/proxysql.cfg

ENTRYPOINT ["proxysql", "-f"]

