## Originally sourced from https://github.com/primait/docker-proxysql/blob/master/1.3/Dockerfile.  Maintained locally to offer more security and additional functionality.
FROM debian:jessie

## Original maintainer Andrea Usuelli <andreausu@gmail.com>
MAINTAINER Duncan Watson <duncan@hiveit.co.uk>

RUN apt-get update && \
    apt-get install -y wget && \
    wget https://github.com/sysown/proxysql/releases/download/1.3.0f/proxysql_1.3.0f-debian8_amd64.deb -O /opt/proxysql_1.3.0f-debian8_amd64.deb && \
    dpkg -i /opt/proxysql_1.3.0f-debian8_amd64.deb && \
    apt-get install -y mysql-client && \
    apt-get install -y rsync && \
    rm -f /opt/proxysql_1.3.0f-debian8_amd64.deb && \
    rm -rf /var/lib/apt/lists/*

COPY proxysql.cnf entrypoint.sh make-mysqldump.sh /etc/

RUN useradd -m dumpuser
#RUN chown -R dumpuser:dumpuser /etc
#RUN chown -R dumpuser:dumpuser /var/lib/proxysql

RUN chmod -R 777 /etc
RUN chmod -R 777 /var/lib/proxysql
RUN chmod 0644 /etc/mysql/my.cnf

USER dumpuser

ENTRYPOINT ["/etc/entrypoint.sh"]