FROM dhoer/flyway:4.1.2
MAINTAINER Lukasz Guminski <lukasz.guminski@container-solutions.com>
VOLUME /tmp
RUN apt-get update -y && apt-get install -y mysql-client ldap-utils
COPY db/ /flyway/sql/db
ADD ldap-sync-from-ifs-db.sh /

RUN touch /flyway/flyway.conf && chgrp -R 0 /flyway/flyway.conf && chmod -R g+rwX /flyway/flyway.conf

RUN chgrp -R 0 /ldap-sync-from-ifs-db.sh && chmod -R g+rwX /ldap-sync-from-ifs-db.sh && \
    chgrp -R 0 /usr/local/bin/flyway && chmod -R g+rwX /usr/local/bin/flyway && \
    chgrp -R 0 /flyway && chmod -R g+rwX /flyway

RUN echo 'TLS_REQCERT allow' >> /etc/ldap/ldap.conf